### ISSUE TITLE
Filter nodes based on related aggregations

### ISSUE THREAD

**Issue by matthiasak** [prisma/prisma1#110]
I'd like to add a few more pragmas for filtering. Currently we can filter a direct entity for certain `in`, `contains`, `startsWith`, etc filters, like:

```graphql
{
  allGroups(filter: {
    members_every: { verified: true }
  }){
    name
  }
}
```

But, we can't make a query on allGroups filtering by metadata or aggregates. One idea is to enable special filters that test sub-entities such as the below example query where I would like to filter for groups who have atleast 1 member

```graphql
{
  allGroups(filter: {
    count_gte: [0, {members: {verified: true}}]
  }){
    name
  }
}
```

**Comment by marktani** [comment]
Related to #70.

**Comment by kabriel** [comment]
I need to be able to query for all objects (lets say Cars) that do not have an owner (User) relation set. I'm not sure of the best syntax:
```
{
  allCars(
    filter: {
      owner_none
    }
  ) {
    id
  }
}
```

**Comment by marktani** [comment]
I think for **to-one** relations this works best:

```graphql
{
  allCars(
    filter: {
      owner: null
    }
  ) {
    id
  }
}
```

and for **to-many**:

```graphql
{
  allOwners(
    filter: {
      cars: []
    }
  ) {
    id
  }
}
```

**Comment by marktani** [comment]
@kabriel, it's now possible to query nodes that are not related in *to-one* relation:

```graphql
{
  allCars(
    filter: {
      owner: null
    }
  ) {
    id
  }
}
```

**Comment by matthiasak** [comment]
@marktani @kabriel this feature seems incomplete.

Graphcool console is giving errors on the following:

![selection_027](https://cloud.githubusercontent.com/assets/900775/25368428/01b49a56-2942-11e7-811e-aa1ed9d1ab20.jpg)
![selection_028](https://cloud.githubusercontent.com/assets/900775/25368429/01b4f49c-2942-11e7-9ceb-ea76f2a879ec.jpg)
![selection_029](https://cloud.githubusercontent.com/assets/900775/25368430/01b550ae-2942-11e7-87a7-bddfbcb8a205.jpg)


null works, but I can't check for not_null or exists...

**Comment by matthiasak** [comment]
workaround is slightly varied checks based on nesting level and ways to check...

```js
persons: allPersons(
            filter:{
                verified: false
                ${valid ? `, avatar: {id_not:null}, name_not: "", bio_not: null, bio_not: "", user: {id_not:null}` : ''}
                ${invalid ? `, OR: [{avatar: {id: null}}, {name: ""}, {bio: null}, {user: {id: null}}]` : ''}
            }
            , first: ${pageSize}
            , skip: ${pageSize * page}
            , orderBy: ${orderBy}
        )
```

**Comment by marktani** [comment]
@matthiasak the syntax is `avatar: null` and `avatar_not: null`. Did you try that?

**Comment by matthiasak** [comment]
I did. avatar_not was giving errors

Cheers,

Matt Keas
http://mkeas.org

**Comment by marktani** [comment]
Please create a issue report here: https://github.com/graphcool/api-bugs/issues :slightly_smiling_face:

**Comment by marktani** [comment]
Thanks to @mewdriller for this workaround to query nodes that are not connected in a **to-many** relation:

```graphql
{
  allOwners(
    filter: {
      cars_every: {
        id: "-1"
      }
    }
  ) {
    id
  }
}
```

**Comment by adrianocola** [comment]
The following syntax seems to be working now for filtering nodes that are not connected in a **to-many** relation:

```graphql
{
  allOwners(
    filter: {
      cars_every: {
        id: null
      }
    }
  ) {
    id
  }
}
```

And to do the opposite (filter nodes that *have connections* in a **to-many** relation), this is working:

```graphql
{
  allOwners(
    filter: {
      cars_some: {
        id_not: null
      }
    }
  ) {
    id
  }
}
```

`cars_some: { id_not: "-1" }` works too. 

This is the right way to do it, comparing id to `null`?

**Comment by sorenbs** [comment]
Thank you for this great suggestion!

Please have a look in the spec proposal to see if all your needs are met:-) https://github.com/graphcool/framework/issues/1279

**Comment by samuela** [comment]
I came across this problem today as well. I have a data model that looks something like:

```graphql
type User {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!

  emailAndPassAuth: EmailAndPasswordAuth @relation(name: "UserEmailAndPassAuth", onDelete: CASCADE)
  # githubAuth: GithubAuth
  # etc...
}

type EmailAndPasswordAuth {
  id: ID! @unique
  email: String! @unique
  passwordHashed: String!
  user: User! @relation(name: "UserEmailAndPassAuth")
}
```

Now, I get a new login attempt with an email and a password. I can find the corresponding `EmailAndPasswordAuth` node without any trouble, but getting the ID of the corresponding User is a real pain. In SQL it wouldn't be an issue since it's right there in the joint table, but now I'm stuck with two different queries: one to find the `EmailAndPasswordAuth` and then check that it matches, and yet another to then find the `User` node matching it.

**Comment by sorenbs** [comment]
@samuela - I might be missing something obvious, so please let me know if I am :-)

Can you not do a single query like this?

```graphql
query {
  EmailAndPasswordAuths(where: email: $email, passwordHashed: $password) {
    user {
      id
    }
  }
}
```
