### ISSUE TITLE
Query/filter for random items

### ISSUE THREAD

**Issue by matthiasak** [prisma/prisma1#114]
**Update**: See [this comment for the accepted proposal](https://github.com/prisma/prisma/issues/114#issuecomment-439639218).

---

It would be awesome to be able to request N random items from a table:

```graphql
persons(random: 10){ # get 10 random people
    name
    avatarImage
    id
    groups { name id slug }
  }
```

The corresponding JS/TS client code could look like this:

```ts
const persons = await prisma.persons({ random: 10 })
```

**Comment by marktani** [comment]
Great suggestion! A few more questions:
* What's your use case for this?
* What do you mean when you say random? [Uniformly distributed](https://en.wikipedia.org/wiki/Discrete_uniform_distribution)? Obviously this would be pseudo-random either way :slightly_smiling_face:

**Comment by matthiasak** [comment]
> Is a client-side randomization not suitable?

why pull a  of elements into client side when a SQL query will do it much faster? :)

> What do you mean when you say random? Uniformly distributed? Obviously distribthis would be pseudo-random either way

As uniformly distributed as possible; having this done on 100 let alone 1000+ unique records will be increasingly more costly to a browser on a low-powered phone.

**Comment by marktani** [comment]
> why pull a of elements into client side when a SQL query will do it much faster? :)

I agree. Just exploring possible use cases here! If we implement this, it should tie in with

* `orderBy`
* `filter`

Should be illegal to be used with

* `first`/`before`
* `last`/`after`

**Comment by sedubois** [comment]
I'd love to have this too, as there is in my current app. E.g if I have a collection of "thoughts of the day":

- should be able to show a different thought every day
- the thought should be random but not get repeated until all the other thoughts have been used
- should be able to cluster/filter the thoughts according to some property (e.g an English speaking user should only see the ones in English)

**Comment by marktani** [comment]
> the thought should be random but not get repeated until all the other thoughts have been used

This would be possible using the `filter` argument. I think this API would work great:

```graphql
query nextThought($previousIds: [ID!]!) {
  allThoughts(filter: {
    id_not_in: $previousIds
    language: "en-US"
  }
  first: 1 
  random: UNIFORM
) {
    id
  }
}
```

**Comment by sedubois** [comment]
Yes but then how is this `previousIds` list stored, and how is it cleared? That sounds like pushing the problem to the client, which would need to make one more roundtrip to get the list of previousIds from some storage. Maybe use the custom queries feature https://github.com/graphcool/feature-requests/issues/40. In any case, one call should be enough otherwise the benefit of GraphQL is a bit lost.

Or maybe instead of random I can live with some basic predefined formulae (just give all thoughts incrementally, 1-3-2-4-6-5-..., decrementally, etc....).

**Comment by marktani** [comment]
> Or maybe instead of random I can live with some basic predefined formulae (just give all thoughts incrementally, 1-3-2-4-6-5-..., decrementally, etc....).

Ahh I see. There's a difference in a random distribution (duplicates are possible) and a random permutation (no duplicates). I think @matthiasak was also referring to permutations but I thought it's about a distribution.

Then I'd suggest this API:

```
query thoughtsPermutation {
  allThoughts(
    orderBy: RANDOM
    first: 100
  ) {
    id
  }
}
```

**Comment by matthiasak** [comment]
Hey @marktani In addition to this, it would be nice to just be able to order by edge data just like we can filter by edge data:

```graphql
{
  items: allProducts(
  filter: {
    group: { verified: true }
  }
  , orderBy: {member: { id } }
){
    id
    name
    images { url }
    basePrice
    description
    existingWillSign: willsigns(filter: {person:{id:"${id}"}}){ id signingCost }
    group { id name logo { url } }
  }
}
```

**Comment by Huvik** [comment]
I agree with @marktani to make it like: 
```graphql
query {
  items(orderBy: RANDOM first: 100) {
    id
  }
}
```
Wordpress have random like: `'orderby' => 'rand', 'showposts' => 100` so it could be good fit

**Comment by Huvik** [comment]
Because currently its not possible to do random in one query, because you can't for example query first and last item combined, just items next to each other. Or its possible?

**Comment by marktani** [comment]
You can do this:

```graphql
query randoms($first: Int!, $second: Int!) {
  first: items(first: 1 skip: $first) {
    id
  }

  second: items(first: 1 skip: $second) {
    id
  }
}
```

and choose `first` and `second` randomly.

**Comment by Huvik** [comment]
Any news on it? :)

**Comment by schickling** [comment]
Not yet but seems like a very useful feature that shouldn't take too much time to implement. For the next few weeks the focus of our core development team is mostly on implementing the Postgres + MongoDB connectors but this should also be a great feature for someone to contribute!

**Comment by Huvik** [comment]
So is this proposal final? I was thinking to trying to implement it in near future maybe

**Comment by schickling** [comment]
I really like this API proposal. It would look like the following using the JS/TS client:

```ts
const persons = await prisma.persons({ orderBy: RANDOM, first: 100 })
```

**Comment by adrianescat** [comment]
Any update on this? This would be very helpfull
```javascript
const persons = await prisma.persons({ orderBy: RANDOM, first: 100 })
```
