### ISSUE TITLE
Extra endpoint with mock data

### ISSUE THREAD

**Issue by schickling** [prisma/prisma1#1187]
**What feature are you missing?**

When prototyping a new backend it would be very helpful to have a ready-to-use endpoint which returns mock data.

**Design suggestions (can be challenged):**

- Use additional `/{database-id}/mock` API endpoint
- Endpoint always returns mock data regardless of actual data exists in the database
- API is read-only. It successfully accepts mutations and return the expected payload but doesn't actually change the server-side state.
- Incorporate behavior/API of [GraphQL Faker](https://github.com/APIs-guru/graphql-faker)

**Comment by lgandecki** [comment]
Any news on that?  I'd love to help if you guys give me some pointers :) 
Not being able to run locally or use prisma with integration tests makes it a no-go for me and my clients projects :(
I'm not sure those are not possible - just an assumption based on the fact that this issue is still open.

**Comment by prolink007** [comment]
Also, looking for update on how to mock/test.

**Comment by Jaikant** [comment]
Same here, looking for suggestions. Is [GraphQL Faker](https://github.com/APIs-guru/graphql-faker) the way to go?

**Comment by viztor** [comment]
Is put a new endpoint a good idea

Cons
* if the data is completely random and one-time-temporary, serve it from local is just as good.

Pros:
* use different implementation on the server and while mocking may result in non-complete tests. a working product with mock data on the local server may be breaking with the actual server.
