### ISSUE TITLE
Add tracing information

### ISSUE THREAD

**Issue by kbrandwijk** [prisma/prisma1#1209]
**What feature are you missing?**
Generic support for tracing information. When using tracing/Apollo Engine in the Gateway, the Graphcool endpoint is still a black box with regards to tracing, because the information is not available. It would be very, very useful if this information was exposed from Graphcool.

**How could this feature look like in detail? Tradeoffs?**
https://gist.github.com/OlegIlyenko/124b55e58609ad45fcec276f15158d16

More information: https://github.com/apollographql/apollo-tracing

**Comment by loganvolkers** [comment]
Apollo tracing is great and all, but there's also a similar and robust standard called OpenTracing: http://opentracing.io/

I'm not sure it's an either-or decision, but just FYI.

**Comment by kbrandwijk** [comment]
Thank you for the suggestion. I haven't looked at OpenTracing before. Do you have any experience with it in regard to GraphQL?

**Comment by loganvolkers** [comment]
Sorry, I don't have a ton of experience. We're just in the formative stages of adopting open tracing at my company.

I would love to see Apollo Tracing provide a standard for GraphQL OpenTracing implementations. I'll add comments to the core spec ticket.

**Comment by ntziolis** [comment]
We def need the ability to trace what is going on in the prisma engine. Any update on this? Dont really care if apollo or open or whatever but black box is a nogo for production.
