### ISSUE TITLE
Support new description definitions from recent GraphQL spec

### ISSUE THREAD

**Issue by kbrandwijk** [prisma/prisma1#1405]
Descriptions have changed from comment to string literal blocks in the latest version of the GraphQL spec. I created this issue to track support for it with Graphcool. 

More details here: https://github.com/graphql/graphql-js/pull/927. 
Sangria is already up to date with it: https://github.com/sangria-graphql/sangria/issues/303.

**Comment by jgoux** [comment]
This feature would be awesome for codegen too.

For the database, it could create (COMMENT)[https://www.postgresql.org/docs/current/static/sql-comment.html] on tables and columns.

We could also use these descriptions as labels for autogenerated forms using something like https://github.com/vazco/uniforms.
