### ISSUE TITLE
JSON filters

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#148]
The ability to filter a node based on the keys or values of a JSON field. Suggestion:

```graphql
query {
  allPosts(filter: {
    myJsonField: {
      has_key: "myKey"
      int_gte: {
        key: "count"
        value: 23
      }
    }
  }) {
    id
  }
}
```

**Comment by marktani** [comment]
Inspiration: https://docs.puppet.com/puppetdb/4.3/api/query/examples-pql.html#fact-resource-and-resource-parameter-filtering

**Comment by matthiasak** [comment]
would it be possible to filter on Json columns? maybe for just testing if empty or null?

```graphql
allRecords(filter:{ jsonColumn_empty: true}){ ... }
```

**Comment by PierBover** [comment]
Could Algolia be used for querying JSON fields?

**Comment by jdbence** [comment]
Add `JSON` nested object support using dot notation

```JS
// Example JSON
{
  "some": {
    "deep": {
      "value": 99
    }
  }
}

// Filter
query {
  allPosts(filter: {
    jsonFieldName.some.deep.value_gte : 23
  }
}) {
    id
  }
}

```

**Comment by johnslemmer** [comment]
This is something I'm interested in.  But I also think we could start iteratively.

First, I think there needs to be a way to query scalar list fields and Json type fields for whether or not they are null (or unset).  Maybe something like this:

```gql
query {
  allPosts(where: {
    myJsonField_null: true
  }) {
    id
  }
}
```

Or maybe just providing a raw strict equality and that way you could use the NOT query if you want or even do strict comparison of one JSON value to another.: 

```gql
query {
  allPosts(where: {
    myJsonField: null
  }) {
    id
  }
}
```

This seems like something that I hope could happen sooner rather than later without needing to decide on a whole schema for deep Json field queries.

**Comment by yocheved** [comment]
Is there any estimated date for this feature? We really need this!!

**Comment by carstenbaumhoegger** [comment]
hey!
We're also desperately waiting for this to be implemented!
@marktani is this still on the roadmap?

**Comment by davidboom95** [comment]
Any advice on this feature?

**Comment by entrptaher** [comment]
Given this mongo schema, 
```
{
  name: String,
  data: Array
}
```

I can push data like below,
```
var example = new Instance({
  name: "Example.com",
  data: [
    {"Property 1": "Example.com"},
    {"Property 2": "Something else"},
  ]
});
```

And query like this,
```
Instance.findOne({
  name: "Example.org",
  "data.2.Property 3": "Something else 3"
})
```
I cannot find any way to get similar result with prisma/graphql.

**Comment by entrptaher** [comment]
If anyone want's to see the minimal implementation I did for JSON filter, check my [playground-json-query-mingo](https://github.com/entrptaher/playground-json-query-mingo) repo.

Any suggestions are welcome.

**Comment by kiano0sh** [comment]
Any solution ?

**Comment by m1m6** [comment]
any solution?
