### ISSUE TITLE
Publish pre-packaged Prisma CLI build on NPM

### ISSUE THREAD

**Issue by schickling** [prisma/prisma1#1480]
Installing global binaries via NPM/Yarn can take quite a while. An increasingly popular strategy (see [zeit/now](https://github.com/zeit/now-cli)) is to pre-package the CLI via `webpack` or pkg and distribute a single binary.

**Comment by wtgtybhertgeghgtwtg** [comment]
The reasons `now-cli` [gives for packaging](https://github.com/zeit/now-cli#why-ship-a-pkg-ed-binary) don't seem as relevant for this project.  And won't packaging dependencies negate any caching NPM or Yarn can do?

**Comment by schickling** [comment]
Let's tackle this soon so we can speed up the install speed when using `npm i -g prisma`. This should be fairly simple by reusing the brew build setup.

**Comment by wtgtybhertgeghgtwtg** [comment]
I think [removing unused dependencies](https://github.com/prisma/prisma/pull/2994) would be a better start for this goal.

**Comment by pantharshit00** [comment]
I think using ncc will be best choice here

**Comment by pantharshit00** [comment]
Added feature label to avoid stalebot
