### ISSUE TITLE
Improve comment header of generated database schema file

### ISSUE THREAD

**Issue by schickling** [prisma/prisma1#1483]
The generated database schema file is one of the most important "artefacts" when working with Graphcool in combination with GraphQL servers (& bindings). To make it easier for people to understand how this file fits into the bigger picture of a project, I suggest to include the following information in the header comment section:

* Data model source file(s)
* Date of generation/last change
* Note that file shouldn't be edited directly

## Design Proposal

```graphql
# NOTE: This database schema file was automatically generated when running `graphcool deploy`
# based on the datamodel (types.graphql, enum.graphql) at 2018-01-02T09:57:33.448Z.
# Please do not edit this file directly. Learn more: http://bit.ly/graphcool-database-schema

type Post {
  id: ID! @unique
  title: String
}

# more types...
```

**Comment by marktani** [comment]
The timestamp will lead to merge conflicts - on the other hand it's a file generated at build time so it should probably not be checked into source control anyway. Thoughts?

**Comment by kbrandwijk** [comment]
It should be checked in, but it should not change unless there is an actual change. In which case the contents change anyways, and it wouldn't hurt to update the timestamp.

**Comment by schickling** [comment]
100% agree with @kbrandwijk!

**Comment by bkniffler** [comment]
I don't understand the reason why it should be checked in. Isn't it a file that will always look the same if the sources don't change? Just like a compiled .js file thats based on .ts? Why pollute our repos with it then?

I'd much prefer if it wasn't in my src directory. I got no files inside the src directory that are generated and thus shouldn't be modified. Maybe we could customize the path where its generated to (in my case smth like `{projectroot}/.dev/graphql/schema.graphql`).

**Comment by schickling** [comment]
@bkniffler another reason why the file could possibly change is through a version upgrade of Prisma. I would encourge you to still check the file into your VCS.
