### ISSUE TITLE
Alternatives for secret management

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#1553]
> Why not allow to manage secrets with CLI tool? In my opinion, it's way more secure and less awkward than having such security measure in plain text. It could be even write-only operation. Then you can either add another secret or "deprecate" existing ones. This approach would prevent accidental commits of secrets to source control. Furthermore, this allows having a different set of secrets per stage more naturally since CLI is already working with stages.

Thanks @FredyC for this proposal 🙂

**Comment by FredyC** [comment]
I might add some other key points:

 * each stage can have separate secrets
 * secrets are securely stored on the server and shared (no files floating around between developers)
 * possibly write-only secrets prevent theft from new/untrusted members of the team
 * it's easy to manage multiple secrets and deprecate existing ones with a single command (no need to inform other developers that *this* secret is obsolete now)
 * no hassle with env variables (it's rather painful on Windows to work with those)

**Comment by k00k** [comment]
We would definitely like to see an alternative secure mechanism for storing and/or retrieving secrets. I would vote for the way Serverless Framework does it by allowing for retrieval of AWS SSM Parameters. Currently with Prisma, we check in our .env files which isn't a good solution. Alternatively, we could add the .env files to our .gitignore but then we'd need to pass them from dev to dev, which is also not a good solution.
