### ISSUE TITLE
Floats represented as decimals

### ISSUE THREAD

**Issue by dgb** [prisma/prisma1#1576]
**Current behavior**

Graphcool stores floats as fixed-point decimals (with 65 digits, 30 of which are to the right of the decimal) as opposed to doubles. This causes errors when a number larger or smaller than the decimal precision. In other words, the largest number that can be represented in Graphcool is:

`99999999999999999999999999999999999.999999999999999999999999999999`

... and the smallest:

`0.000000000000000000000000000001`

However, a double-precision floating point number can be much bigger or smaller than this, since there's eight bits of (base 2) exponent in either direction (I think it's something like +-127, since there's a bias about 0, and all bits being set corresponds to "Infinity").

**Reproduction**

Make a model with a float field:

```
type Animal @model {
  id: ID! @isUnique
  name: String!
  atomCount: Float!
}
```

Within the bounds we're ok:
```
mutation {
  createAnimal(
    name: "Cat"
    atomCount: 3.6893488e19
  ) {
    id
    name
    atomCount
  }
} 
```

```
{
  "data": {
    "createAnimal": {
      "id": "cjca3f2pbxt4s0115c7a0n6ab",
      "name": "Cat",
      "atomCount": 36893488000000000000
    }
  }
}
```

But using a fine number like 2.658456e36, we get an error:

```
mutation {
  createAnimal(
    name: "Gorilla"
    atomCount: 2.658456e36
  ) {
    id
    name
    atomCount
  }
}
```

```
{
  "data": {
    "createAnimal": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createAnimal"
      ],
      "code": 3007,
      "message": "Value for field atomCount is too long.",
      "requestId": "eu-west-1:simple:cjca3h7m29bzo0137f4udd958"
    }
  ]
}
```

**Expected behavior?**

GraphQL [defines](http://graphql.org/learn/schema/#scalar-types) `Float` as "A signed double-precision floating-point value". I would expect to be able to store any sort of double precision float value in a `Float` field.

**Comment by kbrandwijk** [comment]
It is a `BigDecimal` on the Scala (server) side...

**Comment by dgb** [comment]
Is there a limitation that prevents it from being a true float on the server side? I'm not super familiar with Scala.

**Comment by sorenbs** [comment]
We made a decision in the early days to only support one complex number type as that is what was included in the GraphQL spec. We picked MySql Decimal to not loose precision.

I think the time has come to support both Float and Decimal. Thanks for bringing this up!
