### ISSUE TITLE
Show me a new token if I change my secret

### ISSUE THREAD

**Issue by kbrandwijk** [prisma/prisma1#1607]
It would be nice if the cli would show me a new jwt token if I deploy with a changed secret.

**Comment by marktani** [comment]
Not sure if that's always a desired behaviour. Maybe that could be controlled using a flag.

You can also run `graphcool token` to print a new token.

**Comment by kbrandwijk** [comment]
Well, I won't be able to connect to my recently deployed endpoint until I get that token. So I think it can be part of the standard workflow (maybe only in tty mode, so not in CI).
