### ISSUE TITLE
'Out of the box' Subscriptions for GraphQL Servers hosted on AWS Lambda

### ISSUE THREAD

**Issue by RishitKedia** [prisma/prisma1#1626]
Hey there! 👋

Now that `Subscriptions` have been implemented for Prisma, and since GraphQL Servers hosted on AWS Lambda cannot support them due to its limitations, it'd be awesome if Prisma could support 'out of the box' `Subscriptions` just like the Graphcool `Framework` so that clients could directly subscribe to Prisma instead of going through the server. This will help avoid hosting another server (just for `Subscriptions`), which is one of the main reasons for going serverless in the first place. 💪

Talked to @marktani about this, and he asked me to create a FR here. 🙃

Cheers! 😃

**Comment by sorenbs** [comment]
I love this idea @RishitKedia!

**Comment by deamme** [comment]
This could be awesome! Clients could directly connect to the Prisma server since it's going be deployed as a server anyways and the Graphcool server can remain a cloud function on AWS or Google.

**Comment by janat08** [comment]
while we die waiting for that, any ideas for https://serverless.com/blog/how-to-manage-your-aws-step-functions-with-serverless/ or at least documentation?>

**Comment by janat08** [comment]
The above link is trash, this is definitely on topic: https://docs.fanout.io/docs/overview

**Comment by janat08** [comment]
this is the open source counterpart: https://pushpin.org/

**Comment by jkarneges** [comment]
Thanks for the Fanout mention, @janat08 ! I'm the founder, and happy to answer any questions or explore how to integrate.

Fanout provides a gateway between raw WebSockets and HTTP. Hopefully we support the necessary primitives to be able to speak Prisma's GraphQL subscription protocol, but if not then we could add whatever's needed.
