### ISSUE TITLE
Oracle Connector

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#1644]
This feature requests serves as a central place to discuss development and progress for the Oracle connector.

**Comment by jschilperoord** [comment]
This would be a great thing to have as we use Oracle for some internal applications 👍

**Comment by wanghaisheng** [comment]
When will i get a oracle connector?

**Comment by jacob-lester** [comment]
Any update on this?

**Comment by gaui** [comment]
This would be very useful.

**Comment by sblack4** [comment]
If there a good generic how-to for creating a database connector?  

Or would you just look at how the others are written?

Anyone can answer. Thank 😸

**Comment by dmcghan** [comment]
I'd love to see an Oracle Database connector added. But it's important that it supports bind variables!

**Comment by casajarm** [comment]
Seconding @dmcghan. Would love to see this feature.

**Comment by hanming2033** [comment]
Yes. Oracle please. Many large financial firms use oracle.

**Comment by jpallaresStacks** [comment]
This will be amazing feature

**Comment by rayelnigma** [comment]
Yes, please add support for Oracle :-)

**Comment by ricardo-aspira** [comment]
What is the road map for having this?

**Comment by Koshux** [comment]
Would be great to have Oracle support :)  As @hanming2033 said, many large financial firms use oracle!

**Comment by tsenseval** [comment]
we using Oracle EBS, would be great if have Oracle Support.

**Comment by dmcghan** [comment]
Hello, any updates on this?

**Comment by joaop-oliveira** [comment]
We've been use Oracle for twenty-five years we would love to see Prisma working with Oracle

**Comment by mike20007** [comment]
Same here. Looking forward to Prisma/Oracle. Now, I am using objection.js/knex.js

**Comment by ledinscak** [comment]
Oracle db support +1

**Comment by dgielis** [comment]
I would be interested in an Oracle DB Connector too

**Comment by bilalak** [comment]
Any updates on this issue?
How can we contribute to the dev of an Oracle connector? 

I am new to Prisma but it looks promising.

**Comment by mgarciajr** [comment]
also interested.
if supported we'll use prisma with oracle across the board in this company 

sogematech.com

**Comment by baloniet** [comment]
This would be lifesaving feature. Were I work all legacy systems are Oracle based. Prisma is super concept. Can't wait. Where can I help? How can I help?

**Comment by YElyousfi** [comment]
The demand for this seems to be super high but this post has been around about 2 years now. When can we expect support? Prisma is awesome

**Comment by charleaux** [comment]
Oracle db support +1

**Comment by Elijen** [comment]
Wanted to give Prisma or Prisma2 a try, but seems there is now way without Oracle DB support :-(

**Comment by praburajan** [comment]
With oracle support, we would use prisma as the db access layer for all our microservices

**Comment by nadilas** [comment]
+1

**Comment by davipolita06** [comment]
+1

**Comment by itayganor** [comment]
+1

**Comment by mikelogaciuk** [comment]
+1

**Comment by raphaelpc** [comment]
+1

**Comment by joelespinozaro** [comment]
+1

**Comment by jongomes** [comment]
+1

**Comment by davide-malagoli** [comment]
+1

**Comment by davide-malagoli** [comment]
Is there a guide to write a connector for prisma?

I see there are also JS drivers supported by Oracle, I would try to integrate them.

https://github.com/oracle/node-oracledb

**Comment by MrR4P70R** [comment]
Hi, any news on this ?
I need an Oracle connector too, it would be really great !
Is this ever planned or investigated ?

**Comment by joseviniciusnunes** [comment]
Can anyone give me a directional?
I'm interested in contributing to the project for integration with oracle database.

**Comment by chadelofson** [comment]
I definitely have interest in helping out as well

**Comment by Gari-sincere** [comment]
Please make this! Cannot consider using this without it

**Comment by escline** [comment]
Look like main discussion for this feature is over on https://github.com/prisma/prisma/issues/2853
