### ISSUE TITLE
ArangoDB Connector

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#1645]
This feature requests serves as a central place to discuss development and progress for the ArangoDB connector.

**Comment by bionicles** [comment]
ArangoDB is cool

**Comment by pluma** [comment]
Hi folks, Alan from ArangoDB here. If there's anything we can do to help you with the connector feel free to ping me.

**Comment by joelgetaction** [comment]
I could use this connector.  Any progress or any tips if I want to take a shot at it myself?

**Comment by pluma** [comment]
@joelgetaction I don't think I've heard from anyone working on one and we don't have one listed at https://www.arangodb.com/arangodb-drivers/ at the moment, so give it a shot if you want.

If you need assistance on the ArangoDB side of things you can hang around in our community slack: https://www.arangodb.com/community/ -- there's a `#driverdev` channel for community-maintained drivers and connectors like this and you can find me there as `@pluma.arangodb`.

**Comment by leeDav** [comment]
This would be really cool!

Any docs on how to write connectors/drivers?

**Comment by andyhu** [comment]
Has anyone started working on it?

**Comment by armenr** [comment]
I found this, today, during a search for prisma + arangodb --> https://github.com/AEB-labs/cruddl

**Comment by homerjam** [comment]
@armenr would you be able to share how you implemented subscriptions with cruddl please?

**Comment by itsezc** [comment]
> @armenr would you be able to share how you implemented subscriptions with cruddl please?

Unfortunately Cruddl doesn't support subscriptions just yet, however it is in active development.

**Comment by qin-guan** [comment]
any developments in this?

**Comment by armenr** [comment]
@itsezc - Any progress on the subscriptions front? What would be the easiest way to find out?

**Comment by itsezc** [comment]
> @itsezc - Any progress on the subscriptions front? What would be the easiest way to find out?

The last we heard for Cruddl about Subscriptions is https://github.com/AEB-labs/cruddl/issues/16 

However afaik they will likely be added, I'm getting really impatient with waiting on Prisma so I've gone full on Cruddl and I'm really interested in making a PR for subscription support, if there doesn't seem to be any progress on it.

**Comment by mysticaltech** [comment]
https://github.com/AEB-labs/cruddl is not really ideal because it forces you to write and control ArangoDB from GraphQL SDL, not the other way around. So it not really a solution here! We need a proper Prisma connector.
