### ISSUE TITLE
DynamoDB connector

### ISSUE THREAD

**Issue by joshuadutton** [prisma/prisma1#1655]
This feature requests serves as a central place to discuss development and progress for the DynamoDB connector.

**Comment by joshuadutton** [comment]
I didn't see DynamoDB as one of the options here: https://github.com/graphcool/prisma/issues/1006, but it gets my vote. If you have established patterns and guidelines for creating connectors, I would consider implementing it myself and doing a PR.

**Comment by lolcoolkat** [comment]
+1 for this :)

**Comment by pavelvlasov** [comment]
@joshuadutton will be happy to help with that

**Comment by tecnocrata** [comment]
great initiative, I'll be more than excited to help

**Comment by dangdennis** [comment]
quarter 4! i'm excited to see progression on this. hoping to see ways to help later.

**Comment by sorenbs** [comment]
We have not yet started work on the DynamoDB connector, and we will not be able to start this year. I will update this thread when we have a clear roadmap.

If you are interested in the general concept on non-sql database connectors you can already check out the [Mongo Preview](https://github.com/prisma/prisma/issues/1643)

**Comment by schickling** [comment]
AWS just released support for transactions in DynamoDB (see [announcement post](https://aws.amazon.com/blogs/aws/new-amazon-dynamodb-transactions/)). This is a very exciting addition and should be considered in our spec. 👌

**Comment by Elijen** [comment]
I've noticed DynamoDB is listed as supported DB on the web. Is it coming soon?

**Comment by anthgur** [comment]
Is this something that would be released with/after prisma 2? I imagine it would be a nice step up from the DocumentClient sdk

**Comment by daxter1987** [comment]
DynamoDB would be amazing, it get my vote

**Comment by MisterEmpyrean** [comment]
Pretty please??
