### ISSUE TITLE
Elastic Search Connector

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma1#1665]
Prisma supports two kinds of database connectors:

* Active connectors - manage and migrate the database schema
* Passive connectors - read and write data only

This is a living document outlining all considerations for an active SQL connector. This is not a final spec - please contribute by commenting below.

Simple query

```graphql
{
  Match: {
    last_name: "Smith"
  }
}
```

Combined filter and query

```graphql
{
  filtered: {
    filter: {
      range: {
        age: { gt: 30 }
      }
    }
    query: {
      match: {
        last_name: "Smith"
      }
    }
  }
}
```

returns

```graphql
{
  ...
  "hits": {
    "total": 1,
    "max_score": 0.30685282,
    "hits": [
      {
        ...
        "_source": {
          "first_name": "Jane",
          "last_name": "Smith",
          "age": 32,
          "about": "I like to collect rock albums",
          "interests": [ "music" ]
        }
      }
    ]
  }
}
````

## Questions

* Should we keep the `_` prefixes used by elastic search in many places?

**Comment by siddharthlatest** [comment]
Love that you are thinking about the Elasticsearch adaptor.

I am not sure how this would map to the full Elasticsearch Query DSL? Even if you narrowly consider `match`, `term` and `bool` as three clauses to support - there are numerous parameters each of them can support. Can you share how an example spec might look like?

Also, if the idea isn't to fully support the DSL (imo really hard to do), what is the fallback mechanism?

**Comment by sorenbs** [comment]
@siddharthlatest With all connectors we aim to support 90+ % of the underlying functionality. The reason we don't aim for 100% is that adding the last bit of functionality would add significant clutter to the API degrading the developer experience. We will support arbitrary queries defined as a string in the data model as fallback. While this is more tedious, it enables the full power of Elastic while keeping most common functionality easily accessible. We will expand on the spec in the next couple weeks and look forward to your feedback :-)

**Comment by siddharthlatest** [comment]
@sorenbs Looking forward to the expanded spec. In the meanwhile, is there any example spec (may be for a different DB) that can give an idea on how this might work?

**Comment by nimi** [comment]
Any updates on the spec and/or progress on this feature?

**Comment by thebetterjort** [comment]
Does anybody have an example?

**Comment by Disturbing** [comment]
Yes, looking forward to this - is it still on track?

**Comment by mrimran** [comment]
Looking forward for this feature. Please update on this.

**Comment by siddharthlatest** [comment]
I am interested in contributing and/or collaborating on this in some way - do we have any initial plans?

**Comment by sorenbs** [comment]
Thank you all for the interest in this! We have not yet started work on the Elastic connector, and we will not be able to start this year. I will update this thread when we have a clear roadmap.

If you are interested in the general concept on non-sql database connectors you can already check out the [Mongo Preview](https://github.com/prisma/prisma/issues/1643)

We would like critical feedback from the community on the proposed API spec above. If anybody would be willing to jump in and create a complete specification, that would also be tremendously helpful. Feel free to open a separate issue and link it here.

**Comment by ali-habibzadeh** [comment]
Will this still happen?

**Comment by Disturbing** [comment]
Anyone want to take this up on a bounty?  We'll pay for it :)

**Comment by dzcpy** [comment]
@Disturbing I would give a try, how do I contact you?

**Comment by Disturbing** [comment]
To refrain from putting my email address up - please join our slack on https://www.kintohub.com and reach out to me directly (Same alias as here)

**Comment by janat08** [comment]
why not prioritize arangodb which has arangosearch as competitor to elasticsearch.

**Comment by suminda123** [comment]
any updates

**Comment by tvvignesh** [comment]
@sorenbs Hope this is still under consideration for prisma2 as well. I am using Postgres & ELK combination in my stack with ELK being used for time series data. Just wanted to make sure since this issue is filed under Prisma1 repo.

**Comment by bionicles** [comment]
+1

**Comment by lucasbastianik** [comment]
+1
