### ISSUE TITLE
TimeScaleDB connector

### ISSUE THREAD

**Issue by joshhopkins** [prisma/prisma1#1672]
TimeScaleDB is a very cool Postgres Extension with time-series in mind – http://www.timescale.com

Should technically work out of the box with the Postgres connector. This is a placeholder request if that isn't the case, for any reason.

**Comment by mytototo** [comment]
Hi there,

Any status regarding the TimescaleDB connector ?

Even though the PostgreSQL connector should work for Timescale out-of-the-box, what do you think are the changes or constraints to respect for hypertables with Prisma ?

Thanks.

**Comment by ragujayaraj** [comment]
Hi,
Does timescaledb work fine with Prisma? Is timescaledb officially supported by prisma.
This thread does not conclude this topic.

**Comment by ZenSoftware** [comment]
TimescaleDB is actually an extension ontop of PostgreSQL.  It is not too difficult to turn a Prisma generated table into a TimescalebDB hypertable.  Here is the process:

Run a Prisma migration that creates the table that stores your time series data 
#### datamodel.prisma
```graphql
type EventTrainer {
  id: Int! @id
  user: User
  time: DateTime! @createdAt
  meta: Json
}
```

Then install TimescaleDB extension on your prisma database, it's probably named **default$default**
```sql
CREATE EXTENSION timescaledb; 
```

With TimescaleDB hypertables, the PRIMARY KEY must include all dimensions you are partitioning by. You have to drop the PRIMARY KEY Prisma generated during the data migration and create one that also includes the "time" dimension.
```sql
ALTER TABLE "default$default"."EventTrainer" DROP CONSTRAINT "EventTrainer_pkey";

ALTER TABLE "default$default"."EventTrainer" ADD CONSTRAINT "EventTrainer_pkey" PRIMARY KEY("id", "time");
```

Then convert the table into a hypertable
```sql
SELECT * FROM create_hypertable('"default$default"."EventTrainer"', 'time');
```

I am able to insert and query data using Prisma client/bindings just fine with the above hypertable.  All while gaining the efficiencies of TimescaleDB's query engine. Cheers my friend (-‿◦)

**Comment by ragujayaraj** [comment]
Thanks for the detailed explanation ZenSoftware! 
It is fantastic and rest of the reply is coming from a different perspective and in no way disrespecting this approach and your help.

Yes, it is understandable that prisma and TimeseriesDB have PostGreSQL in common.

However there seems to  bunch of manual edits we need to do to make prisma to support TimeseriesDB; first we need to do to update table to hypertables and then followed by edits to prisma client to make it work with the edited hypertables. As the complexity of the data model grows, amount of manual work that needs to be done will increase as well. Imagine a scenario, we want to make future edits to the schema during the course of the project. These manual edits might even defeat the original purpose of prisma (Declarative data modeling)

But if prisma officially supports TimeseriesDB, none of this manual work would be required. 

Does prisma officially support TimeseriesDB today or we need to come up approaches such as what is proposed above. If it does not support today, is there any plan in the near future?

**Comment by akulkarni** [comment]
👋🏽Ajay from TimescaleDB. If there are things we can to do help with this please let us know.
