### ISSUE TITLE
Google Cloud Datastore Connector

### ISSUE THREAD

**Issue by ChristopherBiscardi** [prisma/prisma1#1708]
This feature requests serves as a central place to discuss development and progress for the 
 [Datastore](https://cloud.google.com/datastore/docs/concepts/overview) connector.

**Comment by SeanningTatum** [comment]
How's the progress so far?

**Comment by ChristopherBiscardi** [comment]
@SeanningTatum I'm not working on it. @schickling asked me to create an issue for it. I don't think I had access to the resources I needed at the time I was asked to create the issue :)

**Comment by SeanningTatum** [comment]
@schickling Hope you don't mind me asking the progress on the Google Cloud Datastore Connector. I'm planning to pitch making prisma the standard at our company, and they'll probably adopt it depending on how close it is to completion.
