### ISSUE TITLE
AWS Neptune Connector

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma1#1752]
AWS is a fully managed Graph Database. This feature request serves as a central place to discuss development and progress for the Neptune connector.

**Comment by kbrandwijk** [comment]
It's supports the Sparql query language, so supporting Neptune will also be implemented by the new `graphql-binding-sparql` :tada:

**Comment by corysimmons** [comment]
This is the only one I care about. 😬

**Comment by iamclaytonray** [comment]
I think a lot of people will not use this connector when they realize that Neptune is only vertically scalable. Just something to consider 😄

**Comment by bjm88** [comment]
Graph DBs obviously make a ton of sense for "GraphQL" even though they aren't directly related, building a data oriented API fits well with having a DB optimized for data relationships.  Very excited to see a Neo4J and Neptune/SparQL adapter in the works.

**Comment by kendall** [comment]
It's not open source, but at Stardog(.com) we shipped GraphQL support for our Knowledge Graph platform months ago, have an active roadmap to expand GraphQL support. Already support 20+ relational databases, MongoDB and Cassandra in the Fall, etc.

**Comment by geekyvin** [comment]
> It's supports the Sparql query language, so supporting Neptune will also be implemented by the new `graphql-binding-sparql` 🎉

Can you give a link to this implementation please?

**Comment by bionicles** [comment]
Would use
