### ISSUE TITLE
Add inner connection fields

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#1780]
For this datamodel:

```graphql
type Post {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  isPublished: Boolean! # @default(value: false)
  title: String!
  text: String!
  author: User! @relation(name: "UserPosts")
}

type User {
  id: ID! @unique
  email: String! @unique
  password: String!
  name: String!
  posts: [Post!]! @relation(name: "UserPosts")
}
```

this is the generated `User` type:

![image](https://user-images.githubusercontent.com/1780597/34491733-e9a46404-efe4-11e7-813c-e8439b22778f.png)

It is lacking another field `postsConnection: PostConnection!`.

**Comment by JazzJupiter** [comment]
Is there an ETA on when this will be implemented? This seems like a rather large missing feature.

**Comment by marktani** [comment]
Thanks for your feedback, @vanimschootrein! I agree, this is a great feature to add. It's on our roadmap and we'll tackle it soon :slightly_smiling_face:

**Comment by virtualirfan** [comment]
IIUC, without this fix, I shouldn't move to the hosted Prisma service if my client is using Relay. Can someone please check my thinking on this.

**Comment by virtualirfan** [comment]
Any ETA on this bug? In a decent-sized schema, the workaround gets to be a bit much.

**Comment by virtualirfan** [comment]
Update: I've spent hour today trying to make workaround scale. The missing inner edge is just too hard to workaround in any generic way. I feel like my time might have been better spent fixing the actual deficiency in the `Prisma` code base :-( Can someone point me to the right part of the prisma code base?

FWIW, I'll mention two issues from a resolver perspective, to be specific.

- For subscriptions, there isn't a clear opportunity to insert an edge from a resolver
- For a schema that has lots of connections and queries that pull lots of nested objects, I am ending up doing crazy things to rewrite the return objects to nest them in `{edge: {node}}` to conform to the `Relay` specs.

How is anyone making Prisma work with `Relay` in the presence of these for a non-trivial, non-toy schema/app.

**Comment by patrick-samy** [comment]
Is there any workaround on the client side to update the relay store?

Based on the schema above, I'm essentially adding a post to the User and need to update the store record and have react-relay re-render the components.

**Comment by martinseanhunt** [comment]
I would love to see this implemented!

**Comment by lookapanda** [comment]
Anything new here? I'd love to see this!

**Comment by rojobuffalo** [comment]
This is a bummer that Connections and Edges aren't fully supported for a Relay client. Seems like a critical omission. Is there any outline of what work needs to be done on this?
