### ISSUE TITLE
Rename `prisma-database` to `prisma` in `docker-compose.yml`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma1#1791]
Currently both services configured in `docker-compose.yml` are called `prisma-db` and `prisma-database`. The latter should be renamed to just `prisma`.

Also, the `prisma-database` (soon `prisma`) service should also have a `container_name` specified, it should probably be called `prisma` as well.

**Comment by marktani** [comment]
can this be combined with #1653?

**Comment by nikolasburk** [comment]
Hmm I'm not sure, guess that's up to @timsuchanek & @dpetrick to decide.

**Comment by ForsakenHarmony** [comment]
docker-compose prefixes the containers anyway, so you could also just call `prisma-db` `db`
