### ISSUE TITLE
Fine grained service tokens

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#1809]
Currently, service tokens generated by `prisma token` are a JWT signed with the `secret` specified in `prisma.yml`. They grant full read/write access to the Prisma service, via the `admin` role: https://www.prismagraphql.com/docs/reference/prisma-api/concepts-utee3eiquo#authentication

This concept can be expanded to more roles and actions, here are a couple of ideas:

* read vs. write
* Prisma API vs. Deploy/Cluster API
* logs

**Comment by donedgardo** [comment]
@marktani Do they have an expire date?

**Comment by tehsphinx** [comment]
I would love to see some different secrets for read/write.

**Comment by remorses** [comment]
It would also be cool to separate the jet payload data for prisma in a specific key, so that a single token can be shared between prisma and other kind of apps.
Something like this:
```json
{
  "data": {
        "prisma": {
            "service": "myservice@prod",
            "roles": [
                "admin"
            ]
        }
  },
  "iat": 1532530208,
  "exp": 1533135008
}
```

**Comment by yezarela** [comment]
Is there any workaround for now to implement this ?
