### ISSUE TITLE
Allow glob patterns for Datamodel Files

### ISSUE THREAD

**Issue by Saeris** [prisma/prisma1#1815]
Couldn't find anything in the documentation about this. Seems right now you can only specify a single path or a list of absolute paths that will be concatenated.

As data models grow more complex, it makes sense to split them up into multiple files, preferably into a directory structure, such that some related files can be organized via co-location. While the GraphQL SDL is remarkably concise, files can still become long pretty fast, especially when you include descriptions for documentation. For this reason, I like to isolate each object (type, enum, interface, etc) to their own file. I just hate scrolling that much.

So with that in mind, it would be great to be able to use a glob pattern in `prisma.yml` to recursively search through all the sub-directories of a given path for either `.graphql` or `.gql` files.

**Comment by hyphaene** [comment]
Hi,
Is this feature planned in any way ?

**Comment by hyphaene** [comment]
Hi, 
For your information, I published a cli on npm which regenerate the datamodels Prisma entry with glob config

Available at https://www.npmjs.org/package/prismafire 

Feel free to send any feedback if needed :) 

Cheers
