### ISSUE TITLE
Failing seed.graphql does not fail the deployment

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma1#1887]
# Bug Report

**Current behavior**
If there is an issue with `seed.graphql` the deployment continues. I am not sure if this is a bug or intended behavior but in my opinion deployment should fail when there is an issue with `seed.graphql`

**Reproduction**
Setup biolerplate with `prisma init` command. 

Nuke the local cluster with `prisma local nuke` command. 

Introduce an issue in `seed.graphql` file, say, two unbatched mutatons (I got an error for this).

Run `prisma deploy`.

The deploy will succeed but the seed will fail. 

**Expected behavior?**
The deploy should fail (fast) if there is a problem with `seed.graphql`. We can even statically check the `seed.graphql` file against the schema before executing the other parts of `prisma deploy` command.

**Comment by vincenzo** [comment]
Just ran into this myself. +1, definitely.
