### ISSUE TITLE
Enhancement: Support remote schema stitching/execution over other transports (e.g. gRPC)

### ISSUE THREAD

**Issue by henry74** [prisma/prisma1#1921]
# Feature Request

**What feature are you missing?**
Alternatives for more efficient transport protocol support for remote schema binding/execution.  HTTP has unnecessary overhead for service-to-service communications.
**How could this feature look like in detail? Tradeoffs?**
Posting as a possible enhancement per conversation with @schickling on the Slack channel:

Remote schema stitching and execution requires every remote service run as a GraphQL Server exposed over a HTTP-based API. In a microservices-based architecture where those remote services are only involved in service-to-service communication, leveraging HTTP as the transport introduces a fair amount of unnecessary overhead. Consider adding a way to leverage other back-end efficient transport protocols to communicate between the root GraphQL API server and the remote services.

Issue also cross-posted to graphql-bindings repository: https://github.com/graphql-binding/graphql-binding/issues/53

**Comment by bazaglia** [comment]
This would be amazing!!
