### ISSUE TITLE
Support cascading delete with deleteMany

### ISSUE THREAD

**Issue by huv1k** [prisma/prisma1#1936]
**Current behavior**
Currently cascade delete don't work with deleteManyTYPE only with deleteTYPE

**Reproduction**
Just create relation with `onDelete: CASCADE` and run mutation `deleteManyTYPE`

**Expected behavior?**
Cascade delete work with both deleteManyTYPE and deleteTYPE

**Comment by Fi1osof** [comment]
Still waiting for...

**Comment by steve-a-jones** [comment]
@marktani  - Is there an ETA on this feature?

**Comment by SilencerWeb** [comment]
@marktani any updates? :)

**Comment by mxstbr** [comment]
I stumbled upon this issue by running into the "The change you are trying to make would violate the required relation" error, would love to see support for this!

**Comment by prilutskiy** [comment]
Any progress on this?

**Comment by Steveeeie** [comment]
Is there any progress on this? 

In the mean time does anyone know of a sensible work around? This is a huge blocker for me 😞

**Comment by LawJolla** [comment]
We really need help on features like these (and basic text search).  I know you can't send out press releases like Nexus or the next DB adaptor, but it's these issues that keep everyone writing SQL queries and not bothering.

**Comment by domekol** [comment]
#3796

**Comment by do4gr** [comment]
For the SQL connectors cascading delete support for deleteMany and nestedDeleteMany will go into beta today.
