### ISSUE TITLE
Prisma deploy with arguments

### ISSUE THREAD

**Issue by huv1k** [prisma/prisma1#1983]
# Prisma deploy with arguments

**What feature are you missing?**
I would like to see that `prisma deploy` command could take arguments for deploy from parameters not only env files. It could be used in CI for automatic deployment, because storing values in env's its not recommended. https://github.com/motdotla/dotenv#should-i-commit-my-env-file

**How could this feature look like in detail? Tradeoffs?**
So for example you could use CircleCI env's:
`prisma deploy --cluster=${PRISMA_CLUSTER} --secret=${PRISMA_SECRET}` etc

**Comment by matteozambon89** [comment]
It would be good also to pass the file `prisma.yaml` and the `prisma.graphql` to `prisma deploy`
```
$ prisma deploy --config prisma.development.yaml --schema prisma.graphql
```
Where on `--config` we can feed the `prisma.yaml` and on `--schema` we can feed the already computed `schema` to avoid the schema generation during deploy.
