### ISSUE TITLE
Multiple concurrent requests temporarily locking local Prisma cluster

### ISSUE THREAD

**Issue by LawJolla** [prisma/prisma1#2048]
# Bug Report

** This may be a http-link-dataloader issue, but I can't tell 🤣 **

**Current behavior**

Multiple concurrent request overwhelm the Prisma batch process, local deployment.

[GraphQL error]: Message: Whoops. Looks like an internal server error. Search your cluster logs for request ID: api:api:cjejgjtkr01fn01002wmakco8, Location: [object Object], Path: createFile
[Network error]: Error: Whoops. Looks like an internal server error. Search your cluster logs for request ID: api:api:cjejgjtkr01fn01002wmakco8
{ Error: Whoops. Looks like an internal server error. Search your cluster logs for request ID: api:api:cjejgjtkr01fn01002wmakco8
    at BatchedGraphQLClient.<anonymous> (/Users/dennismacbookpro/PhpstormProjects/imageserver/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:74:39)
    at step (/Users/dennismacbookpro/PhpstormProjects/imageserver/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/Users/dennismacbookpro/PhpstormProjects/imageserver/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/Users/dennismacbookpro/PhpstormProjects/imageserver/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  message: 'Whoops. Looks like an internal server error. Search your cluster logs for request ID: api:api:cjejgjtkr01fn01002wmakco8',
  locations: [],
  path: [ 'createFile' ] }

And in the logs...

prisma-database_1  | {"@timestamp":"2018-03-09T04:45:26.523+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"api:api:cjejgjtkr01fn01002wmakco8\"}","logger_name":"com.prisma.api.server.ApiServer","thread_name":"single-server-akka.actor.default-dispatcher-38","level":"INFO","level_value":20000,"HOSTNAME":"d94b12a9a036"}
prisma-database_1  | {"@timestamp":"2018-03-09T04:45:26.529+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"api:api:cjejgjtkx01fo0100fcc5n65b\"}","logger_name":"com.prisma.api.server.ApiServer","thread_name":"single-server-akka.actor.default-dispatcher-17","level":"INFO","level_value":20000,"HOSTNAME":"d94b12a9a036"}
prisma-database_1  | PUBLISHING SUBSCRIPTION EVENT TO Only(subscription:event:imageserver@dev:createFile)
prisma-database_1  | {"key":"error/unhandled","requestId":"api:api:cjejgjtkr01fn01002wmakco8","clientId":"imageserver@dev","payload":{"exception":"java.sql.SQLTransactionRollbackException: (conn=1609) Deadlock found when trying to get lock; try restarting transaction","query":"mutation ($_data: FileCreateInput!) {\n  createFile(data: $_data) {\n    id\n  }\n}\n","variables":"{\"_data\":{\"Bucket\":\"wk-images\",\"fileType\":\"ImageOriginal\",\"cache\":31536000,\"fileGroup\":{\"connect\":{\"id\":\"cjejgj0k7014e010078a3pslx\"}},\"ETag\":\"\\\"df674ff505e265e186dd2f95a4d98159\\\"\",\"Key\":\"vehicles/11630/39969528394_2a41ece63a_o_11630__original.jpg\"}}","code":"0","stack_trace":"org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:165)\\n org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:106)\\n org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)\\n org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224)\\n org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)\\n com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)\\n com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)\\n slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)\\n slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)\\n slick.jdbc.Invoker.first(Invoker.scala:31)\\n slick.jdbc.Invoker.first$(Invoker.scala:30)\\n slick.jdbc.StatementInvoker.first(StatementInvoker.scala:16)\\n slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)\\n slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)\\n slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:240)\\n scala.collection.Iterator.foreach(Iterator.scala:929)\\n scala.collection.Iterator.foreach$(Iterator.scala:929)\\n scala.collection.AbstractIterator.foreach(Iterator.scala:1417)\\n scala.collection.IterableLike.foreach(IterableLike.scala:71)\\n scala.collection.IterableLike.foreach$(IterableLike.scala:70)\\n scala.collection.AbstractIterable.foreach(Iterable.scala:54)\\n slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:240)\\n slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:238)\\n slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:240)\\n scala.collection.Iterator.foreach(Iterator.scala:929)\\n scala.collection.Iterator.foreach$(Iterator.scala:929)\\n scala.collection.AbstractIterator.foreach(Iterator.scala:1417)\\n scala.collection.IterableLike.foreach(IterableLike.scala:71)\\n scala.collection.IterableLike.foreach$(IterableLike.scala:70)\\n scala.collection.AbstractIterable.foreach(Iterable.scala:54)\\n slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:240)\\n slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:238)\\n slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:534)\\n slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:534)\\n scala.collection.Iterator.foreach(Iterator.scala:929)\\n scala.collection.Iterator.foreach$(Iterator.scala:929)\\n scala.collection.AbstractIterator.foreach(Iterator.scala:1417)\\n scala.collection.IterableLike.foreach(IterableLike.scala:71)\\n scala.collection.IterableLike.foreach$(IterableLike.scala:70)\\n scala.collection.AbstractIterable.foreach(Iterable.scala:54)\\n slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:534)\\n slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:571)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)\\n java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n java.lang.Thread.run(Thread.java:748)","message":"(conn=1609) Deadlock found when trying to get lock; try restarting transaction"}}

Once this error occurs, the Prisma operations stop until a new query hits.

**Reproduction**

Specifically, I'm developing an image manipulation sever.  Here's the flow.  FlickrAPI -> Download up to 10 images at a time (when one completes, another can start so there are only 10 downloads at once) -> buffer downloaded file into 5 different sizes (capped at 10) -> save to s3 (10) -> save result to Prisma (10).

There are no errors when concurrency is reduced to 1.  (and presumably more, though I haven't tried other numbers)

**Expected behavior?**

Saved to data base.

Is this expected behavior?  I'm not spawning child nodes, so nothing is truly concurrent.

**Comment by marktani** [comment]
Hey @LawJolla, this has nothing to do with `http-link-dataloader`, but is happening in the actual Prisma/DB layer.

This is unexpected/unintended behaviour.

I described the situation in more detail here: https://github.com/graphcool/prisma/issues/1788

**Comment by andreas-groos** [comment]
> Hi,
> where can I get more info about this?
> 
> I'm running into this issue by querying ~3000 records and updating each inside a loop without await. This basically fires all the requests at once and crashes the prisma server. Isn't this supposed to be handled by prisma in some way?
> 
> Thanks

You should really handle this in a queue with async/await. or limit your concurrent requests with an [async library](https://caolan.github.io/async/v3/). Having 3000 requests at once is obviously taxing your server. Updating 3000 records at once also will tax your database engine.
