### ISSUE TITLE
Support for multiple databases from single cluster

### ISSUE THREAD

**Issue by etcook** [prisma/prisma1#2049]
# Feature Request

Due to our use of Heroku and our desire to keep different maintenance and recovery schedules for our various internal databases, we would require multiple databases to be accessible from a single cluster. We could still use a single endpoint with shared auth, but requests would need to be properly routed.

**Comment by JensMadsen** [comment]
We really need this feature :-) We provide apps where companies can access their own data in combination with a common dataset. If a single prisma service could access two or more databases (mysql) it would save us a lot of work. Another option is of course to duplicate data on the rdb level but seems like a bad idea :-)
