### ISSUE TITLE
Automatically generate missing ids when importing data

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#2134]
# Feature Request

**What feature are you missing?**

When importing data using `prisma import`, you receive this error message for nodes missing an `id`:

>  ▸    Object {"name":"test","updatedAt":"2018-03-21T16:34:04.000Z","_typeName":"Test","createdAt":"2018-03-21T16:34:04.000Z"} needs an id property

It would be great if the id would be automatically generated in such a case.

**How could this feature look like in detail? Tradeoffs?**

This could either be implemented in the CLI import logic, or in the raw import endpoint.

I suggest to do this in the CLI, because that's where the high-level logic like validation and transformation takes place. I would also like to see a parameter to switch this automatic id generation on and off. Because sometimes, getting an error that cancels the import is the desired behaviour.

**Comment by w0wka91** [comment]
I'll start working on this issue and will open a PR soon!
