### ISSUE TITLE
Public Roadmap

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#2142]

**Comment by vanimschootrein** [comment]
For transparency and clarity's sake, I think this is a good idea.

**Comment by schickling** [comment]
Quick update: We're currently working on substantial improvements of our documentation which will include a public roadmap. This will land in the coming weeks!

**Comment by jhalborg** [comment]
Is it "SoonTM", or real-soon? 😄

**Comment by jhalborg** [comment]
Any ETA on the roadmap, @schickling ? Personally, I'm hoping for and dreaming of geo-queries and interface/union types support, in that order! 😂

**Comment by reinvanimschoot** [comment]
Any update on this?

**Comment by jhalborg** [comment]
"Soon TM", it seems 😂

**Comment by FluorescentHallucinogen** [comment]
This issue has [`roadmap/2018-Q3`](https://github.com/prisma/prisma/labels/roadmap%2F2018-Q3) label. Q3 2018 is over. Any news?
