### ISSUE TITLE
Ability to configure the max node limit

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma1#2162]
By default Prisma limits queries to return 1000 nodes. Developers are required to use pagination techniques to retrieve more data.

When setting up a Prisma cluster it should be possible to override this limit to either disable it or set a different limit.

Introduce an environment variable called `MAX_NODE_LIMIT`.

- if it is not set, default to 1000
- if set too 0, disable the limit
- if set to any other integer, use as the value

**Comment by ragzor** [comment]
Hey! What is the status on this issue?

**Comment by alan345** [comment]
Any news?

**Comment by louisrli** [comment]
+1 to this
