### ISSUE TITLE
Add 'paranoid delete' option to data types

### ISSUE THREAD

**Issue by tsdexter** [prisma/prisma1#218]
Please add a feature for paranoid delete on a per data type basis. 

For example, when creating a new data type the user should be able to set a boolean field for paranoid delete. If the the value is true it will add a `deletedAt` system field to the data type and when a user calls the `deleteType` mutation rather than removing the record from the database it will set a timestamp in the `deletedAt` field and any queries against such data types will automatically exclude any records where the `deletedAt` has a timestamp set (except where explicitly requesting soft deleted records with a 'deleted' boolean parameter). 

This is similar to the sequelize.js option by the same name and would be helpful for enabling 'soft delete' on sensitive records.

**Comment by djGrill** [comment]
this feature's been discussed here https://github.com/graphcool/prisma/issues/1816
