### ISSUE TITLE
Nested upsert in create mutations (correct: nested connectOrCreate)

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#2194]
# Feature Request

**What feature are you missing?**

A nested `upsert` mutation inside `create` mutations.

**How could this feature look like in detail? Tradeoffs?**

Consider this datamodel:

```graphql
type Album {
  id: ID! @unique
  title: String!
  artist: Artist!
}

type Artist {
  id: ID! @unique
  name: String! @unique
  works: [Album!]!
}
```

`createAlbum` accepts an input type `artist` that looks like this:

```graphql
type ArtistCreateOneWithoutWorksInput {
  create: ArtistCreateWithoutWorksInput
  connect: ArtistWhereUniqueInput
}
```

There is no `upsert` mutation. Adding this would add convenience, while not polluting the API, in my opinion.

# Workarounds

**Check existence before mutation**

One current workaround is to check the existence of the to-be connected node before running the mutation. This is how you can do so in your application resolver (semi pseudo code):

```js
async createAlbum(parent, { title, authorName }, ctx, info) {
  const artistExists = await ctx.db.exists.Artist({
    name: authorName
  })
  if (!artistExists) {
    return ctx.db.mutation.createAlbum(
      {
        data: {
          title,
          artist: { create: { name: authorName } }
        }
      },
      info
    )
  } else {
    return ctx.db.mutation.createAlbum(
      {
        data: {
          title,
          artist: { connect: { name: authorName } }
        }
      },
      info
    )
  }
},
```

**Upsert from the other side of the relation**

You can run the following mutation:

```graphql
mutation {
  upsertArtist(
    where: {
      name: "unique artist name"
    }
    update: {
      works: {
        create: {
          title: "album title"
        }
      }
    } 
    create: {
      name: "unique artist name"
      works: {
        create: {
          title: "album title"
        }
      }
    }
  ) {
    id
  }
}
```

**Comment by LawJolla** [comment]
I've run into this exact pain point and would love an upsert method.

**Comment by williamluke4** [comment]
@marktani Has there been any progress on this?

**Comment by marktani** [comment]
Hey @williamluke4, there has not been any work on this feature.
However, the second workaround I mentioned above is now available.

**Comment by mavilein** [comment]
We implemented this a few weeks ago. Closing therefore.

**Comment by samburgers** [comment]
@mavilein is there any code example of how to implement a nested upsert? thanks

**Comment by mavilein** [comment]
@samburgers : There is a page about nested mutations in our docs. Have you checked this one? https://www.prisma.io/docs/prisma-graphql-api/reference/mutations-qwe2/#nested-mutations

**Comment by nolandg** [comment]
@mavilein I'm confused when you say you've implemented this a few weeks ago. The OP is talking about nested upserts within create mutations. When I read through the docs and look at the generated schema, there seems to only be nested upserts within update or upsert mutations.

ie. When creating a node, I want to upsert a connected node. Is this possible yet? The workarounds don't seem to be transactional thus I need to manually deal with orphaned nodes on failures. Thanks!

**Comment by mavilein** [comment]
@nolandg : Ah i misunderstood this issue then. That original feature request does not make sense though with our semantics. An `upsert` in our API either update the connected node or create a new node and connect it.
So i guess what we really want is an `connectOrCreate`.

**Comment by do4gr** [comment]
We are thinking about implementing this soon, so here is a draft of what it could look like: 

```GraphQL
type User {
  id: ID! @unique
  name: String
  post: [Post!]!  
}

type Post {
  id: ID! @unique
  title: String  @unique
  content: String
  author: User!
}


mutation createOrConnect {createUser(data:{
  name: "Paul", 
  posts:{
    createOrConnect:[
      {
        where: {title: "First"},
        create: {title: "First", content: "Test"}
      },
      {
        where: {title: "Second"},
        create: {title: "AnotherTitle", content: "Test"}
      }   
    ]
  }
  }){id}}
```

The where would accept any field marked as unique in the datamodel, and the create would require the normal CreateInputType. It is not required to have the same value of the where for the respective field in the create. 

In the mutation above we would check for a Post with the specified unique title and set a connection to this one if one is found. If none is found we would create a new one with the provided values and establish a relation to this one. 

We will not generated the mutation in cases where it would always error on the connect case. In these cases a simple create should be used.

| Author      |      Post        |      Nested CreateOrConnect on Author|
|---|---|---|
|[Posts!]!   |   [Authors!]!   |  generate        |
|[Posts!]!   |    Author!      |  generate        |
|[Posts!]!   |    Author       |  generate        |
| Post!      |   [Author!]!    |  generate        |
| Post!      |    Author!      |  do not generate |
| Post!      |    Author       |  do not generate |
| Post       |   [Author!]!    |  generate        |
| Post       |    Author!      |  generate        |
| Post       |    Author       |  generate        |

This way only the create part can error - due to unique violations for example.

**Comment by saratitan** [comment]
This looks great. Are there any updates on this?

**Comment by cmoses8626** [comment]
Awesome, am also looking for exactly this mutation, proposal looks great

**Comment by joshhopkins** [comment]
Keep coming up against this. Very much needed!

**Comment by Soliseum** [comment]
Any updates on createOrConnect? This would be an amazingly helpful feature, thanks either way!
@mavilein  @do4gr

**Comment by aarshaw** [comment]
Any word on this? Desperately needed

**Comment by saeedseyfi** [comment]
This is my temp solution, might help you as well.
I use a helper function that generates create/connect.

**defenition**
```javascript
const createOrConnect = async (entity, items) =>
  (await Promise.all(items.map(({ where }) => entity(where))))
    .reduce((acc, itemInDb, i) => {
      if (itemInDb) {
        if (!acc.connect) {
          acc.connect = [];
        }
        acc.connect.push(items[i].where);
      } else {
        if (!acc.create) {
          acc.create = [];
        }
        acc.create.push(items[i].create);
      }

      return acc;
    }, {});
```

**usage**
```javascript
  const toCreate = {
    name: 'saeed',
    posts: {
      ...await createOrConnect(prisma.post, [
        {
          where: {title: "First"},
          create: {title: "First", content: "Test"}
        },
        {
          where: {title: "Second"},
          create: {title: "AnotherTitle", content: "Test"}
        } 
      ])
    }
  };
  await prisma.createUser(toCreate)
```

<details>
<summary>tests</summary>
<p>

     const createOrConnect = require('./createOrConnect');

     describe('createOrConnect', () => {
      let prisma;
      let prismaEntityResult;
    
      beforeEach(() => {
        let called = 0;
        prismaEntityResult = [];
        prisma = { exampleEntity: async () => prismaEntityResult[called++] };
      });
      
      it('should be a function', () => {
        expect(typeof createOrConnect).toBe('function');
      });
    
      it('should handle create', async () => {
        prismaEntityResult.push(undefined);
        const result = await createOrConnect(prisma.exampleEntity, [
          {
            where: { title: 'First' },
            create: { title: 'First', content: 'Test' }
          }
        ]);
    
        expect(result).toEqual({
          create: [{ title: 'First', content: 'Test' }]
        });
      });
    
      it('should handle connect', async () => {
        prismaEntityResult.push({ id: 1 });
        const result = await createOrConnect(prisma.exampleEntity, [
          {
            where: { title: 'First' },
            create: { title: 'First', content: 'Test' }
          }
        ]);
    
        expect(result).toEqual({
          connect: [{ title: 'First' }]
        });
      });
    
      it('should handle connect and create', async () => {
        prismaEntityResult.push(undefined);
        prismaEntityResult.push({ id: 2 });
        const result = await createOrConnect(prisma.exampleEntity, [
          {
            where: { title: 'First' },
            create: { title: 'First', content: 'Test' }
          },
          {
            where: { title: 'Second' },
            create: { title: 'Second', content: 'Test' }
          }
        ]);
    
        expect(result).toEqual({
          create: [{ title: 'First', content: 'Test' }],
          connect: [{ title: 'Second' }]
        });
      });
    });

</p>
</details>

**Comment by BoraALAP** [comment]
Any news on this?

**Comment by pantharshit00** [comment]
This is available in Prisma 2 now see: https://github.com/prisma/prisma-client-js/issues/336#issuecomment-642233623
