### ISSUE TITLE
Error sources

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma1#2199]
## Motivating the Problem
Let's say you're writing an application with the common Yoga/Binding/Prisma stack:

```
+-----+   +------------+   +---------------+   +------+
| App |---|GraphQL Yoga|---|GraphQL Binding|---|Prisma|
+-----+   +------------+   +---------------+   +------+
```

This has many benefits as better flexibility and less code, but makes locating GraphQL Errors right now pretty hard. That's the case, because in this stack we have 3 GraphQL Schemas that are involved to process a query.

1. **GraphQL Yoga**: Yoga exposes the application schema, an instance of `GraphQLSchema` from graphql js.
2. **GraphQL Binding**: In order to provide the nice args experience for bindings, another schema is needed here - under the hood a "remote executable schema" is used.
3. **Prisma**: Prisma, using Sangria, also provides a GraphQL Schema.

### Where did the error happen?
Let's say we get a response like this: (taken from https://github.com/graphcool/graphql-server-example/issues/92)
```
{
  "data": null,
  "errors": [
    {
      "message": "Field 'places' of type 'Place' must have a sub selection. (line 2, column 3):\n  places(where: $_where, orderBy: $_orderBy, skip: $_skip, after: $_after, before: $_before, first: $_first, last: $_last)\n  ^",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "homesInPriceRange"
      ]
    }
  ]
}
```
We now know that a subselection is missing. We suspect this error to occur in either the Yoga schema or the binding schema. But where did it actually happen? We don't know.

This is a simple example, where only one source is used in Yoga. There could be hundreds of microservices used by Yoga, where the overview would be totally lost. We need a solution for this.

## Proposal
In order to know where an error comes from, we could add a property to it, that describes its source.

Right now the spec for the error type looks like this:
```graphql
type Error {
  message: String!
  path: [String!]
  location: [Location!]
}
```

In Prisma we added 2 more properties, `requestId` and `code`:
```graphql
type Error {
  message: String!
  path: [String!]
  location: [Location!]
  requestId: String!
  code: Int
}
```

The **proposal** is, too add a property called `source: String`. In our example from above, it would look like this:
```js
{
  "data": null,
  "errors": [
    {
      "message": "Field 'places' of type 'Place' must have a sub selection. (line 2, column 3):\n  places(where: $_where, orderBy: $_orderBy, skip: $_skip, after: $_after, before: $_before, first: $_first, last: $_last)\n  ^",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "homesInPriceRange"
      ],
      "source": "yoga"
    }
  ]
}
```
Now we can see, that the error has been triggered in the yoga schema.

## Moving forward
This is a rough proposal, how a solution for finding the error source could look like.
If you're interested in working on this, please let us know in a comment or join our public Graphcool Slack!

**Comment by peterschussheim** [comment]
@timsuchanek i'd be happy to work on this.  Feeling the pain right now trying to debug missing sub selection errors and something like your proposal would be very helpful.

**Comment by divyenduz** [comment]
Extending the original proposal, what we essentially want to do is to recursively preserve the `errors` from graphql spec for multiple schemas across a delegation path. 

This can be achieved by adding `delegrationErrors` and `schemaId` key to [error extensions](https://github.com/facebook/graphql/pull/407).

- `delegationErrors` will recursively capture all errors across the delegation path and preserve them in a similar structure to the [`errors` field](http://facebook.github.io/graphql/June2018/#sec-Errors). 

- `schemaId` will be a string/url as a unique identifier for any schema on the delegation path.

An example response of graphql server implementing such a sources solution would look like this:

```
{
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "locations": [{"line": 6, "column": 7}],
      "path": ["hero", "heroFriends", 1, "name"],

      "extensions": {
        "schemaId": "schema_1",
        "code": "CAN_NOT_FETCH_BY_ID",
        "timestamp": "Fri Feb 9 14:33:09 UTC 2018",
        "delegationErrors": [
          {
            "message": "Name for character with ID 1002 could not be fetched.",
            "locations": [{"line": 6, "column": 7}],
            "path": ["hero", "heroFriends", 1, "name"],
            "extensions": {
              "schemaId": "schema_2",
              "code": "CAN_NOT_FETCH_BY_ID",
              "timestamp": "Fri Feb 9 14:33:09 UTC 2018"
            }
          }
        ]
      }
    }
  ]
}

```

**Comment by jgoux** [comment]
I'm having a hard time dealing with my errors from Prisma as they aren't machine readable. Please fill the `extensions` key with useful infos (code, path, field...). 🙏
