### ISSUE TITLE
Run Prisma anywhere

### ISSUE THREAD

**Issue by jferrettiboke** [prisma/prisma1#2207]
Hi all!

I came up with this because I want to use Prisma in the Cloud in a very easy way. I already read "[How to deploy a Prisma cluster to AWS Fargate using Docker & CloudFormation](https://blog.graph.cool/how-to-deploy-a-prisma-cluster-to-aws-fargate-using-docker-cloudformation-293aa8727b89)" but still complicated for some people and many things to do. In order to alleviate this, I wondered if it is possible to deploy Prisma with Zeit Now.

I found out a little bit and I also talked with a guy from Zeit Team (@sergiodxa) about deploying Prisma using Now. Basically this is what he said.

> It is not possible yet to use Prisma in Now. The reason that it is possible to use AWS Fargate is that the Prisma CLI has native support to deploy this service directly.
>
> When Prisma has a way to run it anywhere without using “docker-compose” and just running Prisma (without the associated DB), it could be used in Now.
>
> Surely it will be possible when https://github.com/graphcool/prisma#database-connectors is working.

As you can note, the title of this issue is "Run Prisma anywhere", not only using Zeit Now. I would like to see Prisma working in the Cloud in an easier way. I think some things must be changed on its core. If we give a solution to this, it will mean a lot, since anyone could deploy to the Cloud very easy (where Docker is allowed).

What are, guys, your thoughts about this?

**Comment by delta98** [comment]
I think once the database connectors are fully formed, it will be a great batteries optional application. But I also understand the need for a default vendor.

**Comment by LawJolla** [comment]
For a quick soap box... we need to support the people that support us.  The graph cool team did an outstanding job with Prisma Cloud, and if you can use it, you should.

I was a big supporter of RethinkDB and HorizonJS.  A big freeloading supporter.  Now that RethinkDB the company is gone for lack of dev support, I lost hundreds of hours time wasted with their products.  Let's not do the same thing here.

Soapbox off.

**Comment by jferrettiboke** [comment]
@LawJolla If there are easier ways to people for deploying anywhere, more developers will use Prisma. Not everyone wants/can deploy to Prisma Cloud due to several reasons such as company policies, costs or whatever their reasons are. Precisely, I think Prisma Cloud is living thanks to this open sourced repository which is supported by an entire community. Prisma Cloud is a very good option but it shouldn't be the only one to exist. The Graphcool team published "How to deploy a Prisma cluster to AWS Fargate using Docker & CloudFormation" in order to let developers know more options to use Prisma in other infrastructures.

I strongly believe running Prisma anywhere is a really nice option for developers and also the future of Prisma. Prisma will be more flexible, adaptable and customizable with adaptors. Why not allow people to have Prisma running anywhere?

**Comment by sorenbs** [comment]
Thank you all for the input :-)

And especially @LawJolla for the support!

Prisma is designed to be able to run in any environment that can support long-running docker containers. This includes Zeit now, Fargate, Kubernetes etc. We are currently working on simplifying the experience of running Prisma on your own, and you should expect to see great improvements within the next month.

Prisma Cloud will continue to be the easiest way to run Prisma in a secure production ready environment, but we want to assist you in running Prisma on your own if you need to do so for cost or compliance reasons.

**Comment by eliezedeck** [comment]
I have played around with Prisma. I really liked it so far.

What I'd like to also have: **run Prisma on ARM devices**, like Raspberry Pi (probably memory constraint), Orange Pi (quite a large amount of RAM available), etc... Since those devices have builds of Node for them, serving an app off of them would open-up interesting use cases. It might even be possible to serve an app off an Android phone this way.

Obviously, the first obstacle is the requirements to run it in Docker. Running Prisma manually, and pointing it to use a MySQL DB would probably solve this (?).
