### ISSUE TITLE
RethinkDB Connector

### ISSUE THREAD

**Issue by khoahuynh162** [prisma/prisma1#2216]
This feature request is a central place to discuss the development of RethinkDB connector. Please contribute in the comments below.

**Comment by LawJolla** [comment]
Given RethinkDB's baked in and performant reactive data layer, I think this connector could be interesting for the first step(s) towards a live query implementation!

**Comment by khoahuynh162** [comment]
Where do you guys think I should start with this connector? I will focus on mutation, query, and synchronization between Prisma data storage and MongoDB collections

**Comment by QuantumlyTangled** [comment]
Any progress on this suggestion?

**Comment by QuantumlyTangled** [comment]
Bump

**Comment by QuantumlyTangled** [comment]
Any updates on this?

**Comment by ghiscoding** [comment]
@QuantumlyTangled 
Considering that even the [MS SQL Connector](https://github.com/prisma/prisma/issues/1642) (which a lot more people are waiting for) is still not ready either, I doubt the RethinkDB one will be dealt before the MS SQL one. Just guessing here...
