### ISSUE TITLE
FoundationDB Connector

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma1#2240]
This feature request serves as a central place to discuss development and progress for the FoundationDB connector.

**Comment by netspencer** [comment]
I'd be down to help build this. I'm a huge FoundationDB fan and planning to start using it more widely in production.

**Comment by orefalo** [comment]
well, let's put things in order.. first you need a stable fdb nodejs driver.

it's coming: https://github.com/josephg/node-foundationdb

**Comment by mogui** [comment]
I'm willing to help too, huge fan of both technologies

**Comment by likeabbas** [comment]
Any updates on this?

**Comment by mavilein** [comment]
@likeabbas: So far we did not get to start on this Connector yet. We are currently working on polishing the connector for MongoDB. In the first quarter of 2019 we will probably start the implementation of a new connector. In order to decide which one to built it would be really amazing if you could describe your usecase for this connector. Why do you want it? What are the features you would expect it to have that are different from a SQL connector for example? 
Use case descriptions like this really help us understand what our users want. 🙏

**Comment by akeating** [comment]
Huh, do you just get FoundationDB support for free? https://www.foundationdb.org/blog/announcing-document-layer/ :)

**Comment by do4gr** [comment]
They unfortunately do not support all Mongo functionality. We'll have to do a deep dive at some point to see which features they are missing that we rely on for the Mongo connector and whether we can somehow mitigate them.

**Comment by namesphill** [comment]
What is the status of this feature?
