### ISSUE TITLE
A particular mutation between User Type and a custom type returns internal server error

### ISSUE THREAD

**Issue by Alosies** [prisma/prisma1#2247]
When I try to apply a mutation that connects my **User** and **Question** fields through a relationship named **QuestionEditedby**, it returns **internal server error**.  But a mutation connecting the same two types using the relationship **QuestionCreatedby** happens correctly. Please find below the screenshots of my types and the mutation I'm trying to apply.

Related Types

<img width="615" alt="screen shot 2018-04-21 at 1 39 39 pm" src="https://user-images.githubusercontent.com/24241029/39082014-a20ceb0e-4569-11e8-85d9-71323e969135.png">
<img width="782" alt="screen shot 2018-04-21 at 1 39 57 pm" src="https://user-images.githubusercontent.com/24241029/39082015-a23ef2f2-4569-11e8-9b83-141d6eaad244.png">

Failing Mutation

<img width="1419" alt="screen shot 2018-04-21 at 1 41 54 pm" src="https://user-images.githubusercontent.com/24241029/39082029-daa43b20-4569-11e8-9f1c-8203f53920b5.png">

**Comment by marktani** [comment]
Does that also happen when you deploy your project to a fresh service?

**Comment by Alosies** [comment]
I installed a fresh service with just the fields required for applying the mutation and there was no error, the mutation worked. 

Schema in fresh service
<img width="611" alt="screen shot 2018-04-21 at 8 28 35 pm" src="https://user-images.githubusercontent.com/24241029/39085596-9b4e07f6-45a2-11e8-8579-40f0c74e5828.png">

mutation in fresh service
<img width="1337" alt="screen shot 2018-04-21 at 8 29 23 pm" src="https://user-images.githubusercontent.com/24241029/39085606-b9da2f1a-45a2-11e8-8526-0e90b1a0212f.png">

What could be the issue with my old service?

**Comment by marktani** [comment]
There are a couple of known migrations that result in inconsistencies. Did you do something described here: #2018?

If not, it would be great if you could share the "before" and "after" schema so I can look into a reproduction 🙂

In such a case, a manual intervention on on the database level is required to resolve the inconsistency. As this is on the development cluster, you cannot do so yourself. Please reach out to `support@prisma.io` and describe your situation 🙂

**Comment by Alosies** [comment]
I tried to create a new service and tried to upload the old service data to the new service. When I do so, only nodes and lists are getting exported. Relations are not getting exported. Please find the image below. 
<img width="499" alt="screen shot 2018-04-23 at 4 33 48 pm" src="https://user-images.githubusercontent.com/24241029/39123011-2a249112-4714-11e8-9a89-a77386d0a3af.png">

This is what i get when i export DEBUG
<img width="951" alt="screen shot 2018-04-23 at 4 35 21 pm" src="https://user-images.githubusercontent.com/24241029/39123100-677e5fc0-4714-11e8-9ee5-0d295d99c84a.png">
