### ISSUE TITLE
Use environment variable for `managementApiSecret`

### ISSUE THREAD

**Issue by jferrettiboke** [prisma/prisma1#2295]
# Feature Request

**What feature are you missing?**

Use environment variable for `managementApiSecret` on `docker-compose.yml` by default.

**Comment by FredyC** [comment]
Um, how to actually supply env variables for a docker commands? I mean I have a couple of different `.env` files in the project for different deployments and each of those has different `PRISMA_MANAGEMENT_API_SECRET`. It's easy to run `prisma deploy -e envFile`, but I am unsure how to do the same with `docker-compose`.

I can understand you are trying to give more control to power users, but rookies like me are having a hard time now :/
