### ISSUE TITLE
Support database migrations for existing databases

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma1#2345]
Starting with the 1.8 release Prisma will support existing databases. 

Initially it will not be possible to use the Prisma migration system to change the structure of a preexisting database. The reason for this is that databases that has not been set up using Prisma can be configured in many different ways to achieve the same result. Prisma supports queries and mutations for most of these cases.

We should adapt the migration system to also work with databases of any shape.

This feature will allow you to use Prisma with a legacy database and perform all future database migrations using the convenient SDL based migration system.

**Comment by chj-damon** [comment]
@sorenbs Hi, I want to know if you can use prisma v1.8 to connect to an existed database now. I tried with its command `prisma init` and follow the steps after choosing to connect to existed database but it will fail for some reason. (the existed database is hosted in docker enviornment BTW.)

**Comment by sorenbs** [comment]
Hi @chj-damon - you should be able to connect to an existing Postgres database with Prisma 1.8. Did you manage to make it work? Otherwise I'd suggest you start a conversation in the forum so we can help you figure it out :-)

**Comment by chj-damon** [comment]
@sorenbs https://www.prisma.io/forum/t/how-to-connect-with-existing-database-with-v1-8/3454?u=damon.chen
I've already started a conversation in the forum. Would you like to help me figure out what is wrong?
Thanks for your help.
