### ISSUE TITLE
Also return relational data in delete mutations

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#2347]
**Current behavior**

Delete mutations don't return relation data.

**Reproduction**

```graphql
type A {
  id: ID! @unique
  title: String
  b: B
}

type B {
  id: ID! @unique
  title: String
  a: A
}
```

```graphql
mutation a {
  createA(data: {
    title: "A"
    b: {
      create: {
        title: "B"
      }
    }
  }) {
    id
  }
}

mutation b {
  deleteA(where: { id: "ID" } ) {
    id
    # b is null
    b { 
      id 
    }
  }
}
```

**Expected behavior?**

The node `b` is returned, instead of `null`, in the previous example.

**Workaround**

In your GraphQL Server, you can follow this pattern as a workaround for now:

1. query node + related data
2. delete node

**Comment by andrewjmead** [comment]
Can this be reopened?

**Comment by jacobdo2** [comment]
Is there any progress on this?

**Comment by Cherubeam** [comment]
Issue seems to be still unsolved.

**Comment by seunggs** [comment]
Still seems to be problem

**Comment by TsumiNa** [comment]
Still unsolved.

**Comment by bahamagician** [comment]
Experiencing the same. I cannot get relational data during a delete with SET_NULL relations.

**Comment by Mohammed-Farid** [comment]
It's still there
