### ISSUE TITLE
Limitations when connecting an existing Postgres database

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma1#2377]
Prisma 1.8 introduced alpha support for connecting to an existing Postgres database. This is a list of known limitations that we will address over the next month:

- [x] Model types must always have an id field. If the name in the schema diverges use the `pgColumn` directive: `id: Int! @unique @pgColumn(name: "my_id_column")`
- [ ] Only foreign keys to the column backing the id field of a type is supported, e.g. `my_id_column` in the previous example.
- [x] Model types must have at least one other field besides id.
- [ ] Currently we support exactly one flavour of relation tables. A relation table must have exactly 2 columns that have foreign key constraints to the tables of the connected models. Other columns without foreign key constraints are ignored.
- [x] If relations are ambiguous the @relation directive must be used to disambiguate. This means one will have a @pgRelation/@pgRelationTable directives and additionally the @relation directive.
- [x] The validation done against the existing database currently does not honor `not null` constraints. One can specify a SDL that uses an optional relation field while the sql schema has a not null constraint on that column.
- [ ] The user used to connect to Postgres must have a password.
- [ ] Nested mutations for inline relations only work in one direction. 
    Example: A Todo has a required Relation to a List.
    Works: Creating a Todo as a nested mutation inside creating a List works. 
    Does *not* work: Creating a List as a nested mutation inside creating a Todo does *not* work.
- [ ] Scalar Lists are not supported.
- [ ] no built-in support for views. As a workaround you can define a normal type. Mutations for this type will fail. Querying works.
- [x] system fields must be named exactly like we expect it: `id`, `createdAt`, `updatedAt`
- [ ] support for the following Postgres types is missing: `bigint`, `json`, `jsonb`, Enums, Arrays, geometric types, network address types, `xml`, PostGIS types, text search types
- [ ] composite primary keys

**Comment by jptissot** [comment]
To add to this. I am getting this error when attempting to run a migration with the following model:

datamodel.graphql
``` graphql
type Category @pgTable(name: "category") {
  id: ID! @unique
  createdAt: DateTime!
  description: String
  name: String! @unique
  updatedAt: DateTime!
  tags: [Tag!]!
}

type Tag @pgTable(name: "tag") {
  id: ID! @unique
  category: Category @pgRelation(column: "category_id")
  createdAt: DateTime!
  description: String
  name: String! @unique
  updatedAt: DateTime!
}
```

When running this mutation: 
``` graphql
mutation {
  createTag(data:{ name: "SomeTag", category:{
    connect:{
      name:"Missing"
    }
  }}){
    id
    name
  }
}
```

I get the following error: 

``` json

 {"key":"error/unhandled","requestId":"local:api:cjjhb9vak006r08795veioykf","clientId":"default$default","payload":{"exception":"org.postgresql.util.PSQLException: ERROR: cached plan must not change result type","query":"mutation {\n  createTag(data: {name: \"SomeTag\", category: {connect: {name: \"Missing\"}}}) {\n    id\n    name\n  }\n}\n","variables":"{}","code":"0","stack_trace":"org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)\\n org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)\\n org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)\\n org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)\\n org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)\\n org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)\\n org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)\\n com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)\\n com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)\\n com.prisma.api.connector.postgresql.database.PostgresApiDatabaseMutationBuilder.$anonfun$createDataItem$1(PostgresApiDatabaseMutationBuilder.scala:50)\\n slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)\\n slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)\\n slick.dbio.DBIOAction$$anon$1.$anonfun$run$1(DBIOAction.scala:187)\\n scala.collection.Iterator.foreach(Iterator.scala:929)\\n scala.collection.Iterator.foreach$(Iterator.scala:929)\\n scala.collection.AbstractIterator.foreach(Iterator.scala:1417)\\n scala.collection.IterableLike.foreach(IterableLike.scala:71)\\n scala.collection.IterableLike.foreach$(IterableLike.scala:70)\\n scala.collection.AbstractIterable.foreach(Iterable.scala:54)\\n slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:187)\\n slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:184)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)\\n java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n java.lang.Thread.run(Thread.java:748)","message":"ERROR: cached plan must not change result type"}}
```

**Comment by marktani** [comment]
@jptissot could you please create a [new bug report](https://github.com/prismagraphql/prisma/issues/new?template=bug_report.md) for this error? 🙂

**Comment by brandonmikeska** [comment]
> Only foreign keys to the column backing the id field of a type is supported, e.g. my_id_column in the previous example.

Does this mean prisma will only try to join two tables by the id field even if mark another field as ID! @unique?

I am trying to use a different field other than the built in system field Id, and getting the following error: 

`ERROR: operator does not exist: integer = character varying`

**Comment by mavilein** [comment]
@brandonmikeska : Yes this is a limitation we currently have. However your error message looks like you rather have type conversion error at the database level.

**Comment by brandonmikeska** [comment]
@mavilein so in my use case, there is a system id field, and another field sfid. The sfid is varying char and that's how the tables are linked together.

But it looks like prisma still tries to join through the system Id field which won't work.

Example: 
type User @pgTable(name: "user") {
  id: Int! @unique
  createddate: DateTime
  email: String
  firstname: String
  isactive: Boolean
  name: String
  phone: String
  **sfid: ID! @unique**
  systemmodstamp: DateTime
  title: String
  accounts: [Account!]!
}

type Account @pgTable(name: "account") {
  id: Int! @unique
  **sfid: ID! @unique**
  shippingcity: String
  shippingcountry: String
  shippinggeocodeaccuracy: String
  shippinglatitude: Float
  shippinglongitude: Float
  shippingpostalcode: String
  shippingstate: String
  shippingstreet: String
  systemmodstamp: DateTime
  accounts: [Account!]! @relation(name: "ChildAccounts")
  parent: Account
    @relation(name: "ParentAccount")
    @pgRelation(column: "parentid")
  owner: User! @pgRelation(column: "ownerid")
}

And the foreign keys are joined by the sfid highlighted. I am assuming this is not supported.

**Comment by mavilein** [comment]
@brandonmikeska : Ah i see. We currently only support joining by the id field only. Sorry!

**Comment by mavilein** [comment]
@brandonmikeska : Currently there is no specific issue. Feel free to open one. 
Can you show it to management although that feature is not there yet?

**Comment by brandonmikeska** [comment]
@mavilein I have shown it to management, but we can't really use prisma without this as our consumers will complain that they will have to make multiple API calls to get relational data.

If appropriate, I would like to make an issue separately for this request to track / help in any way to get this working by the fields marked as "ID" instead of defaulting to the system generated "ID" field.

**Comment by epitaphmike** [comment]
How do these limitations affect what is in the docs and what is specified in the following issue?
https://github.com/prisma/prisma/issues/3614

**Comment by HariSeldon23** [comment]
Any idea when Postgres views will be available?

**Comment by gregbelyea71** [comment]
I decided to take a stab at this to present as a possible option in the near future for putting GraphQL into play...  i worked my way through some expected issues with duplicate variable declarations and missing id fields following the introspection.... however once it all looked good and appeared to deploy, i got this message in the docker console..   

 [Debug] Error during deployment for project default$default: java.lang.RuntimeException: Encountered unknown SQL type -5 with column total_count. MColumn(MQName(public.article_stats),total_count,-5,int8,Some(19),Some(0),10,Some(true),None,None,19,2,Some(true),None,None,Some(false))

Seems to be an error while "sending to the backend"  but what is it sending? I followed the steps outlined for setting up with an existing database.  i tried looking around for "unknown SQL type" in particular but doesn't appear anyone else encountered this prob

Any ideas?

**Comment by rhythnic** [comment]
@gregbelyea71 I also got that error.  I've finally gotten it to work consistently.  I've had to use the datamodel that was introspected by prisma version 1.27 and then deploy it with version 1.28.

When deploying the 1.27 datamodel with version 1.27, I got the error you mentioned.  When deploying the 1.28 datamodel with version 1.28, I get datamodel-related errors that I'm in the process of fixing.

**Comment by rhythnic** [comment]
It might be a constraint that a table cannot contain a foreign key reference to itself.  It's causing 2 records to be inserted, the first is the intended record, and the second has an ID and all fields are null.
Removing the foreign key constraint from the postgres dump corrects the behavior, and only one record is inserted.
### SQL
```
--
-- Name: networkProtocols; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."networkProtocols" (
    id bigint NOT NULL,
    name text,
    "protocolHandler" text,
    "networkTypeId" bigint,
    "networkProtocolVersion" text,
    "masterProtocol" bigint
);

--
-- Name: networkProtocols_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."networkProtocols" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."networkProtocols_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public."networkProtocols"
   ADD CONSTRAINT "networkProtocols_masterProtocol_fkey" FOREIGN KEY ("masterProtocol") REFERENCES public."networkProtocols"(id) ON DELETE SET NULL;
```

### Datamodel
```
type NetworkProtocol @pgTable(name: "networkProtocols") {
  id: Int! @unique
  name: String
  protocolHandler: String @unique
  networkType: NetworkType! @pgRelation(column: "networkTypeId") @relation(name: "NetworkTypeNetworkProtocols")
  networkProtocolVersion: String
  masterProtocol: NetworkProtocol @pgRelation(column: "masterProtocol") @relation(name: "NetworkProtocolMasterProtocol")
  networkProtocols: [NetworkProtocol] @relation(name: "MasterProtocolNetworkProtocols")
  networks: [Network]
  protocolData: [ProtocolData]
}
```

![null-record](https://user-images.githubusercontent.com/8162640/54441831-e7c66380-4713-11e9-94ff-364ae2e052c4.png)

**Comment by asktree** [comment]
It also seems to be the case that you cannot use a foreign key as a primary key.
