### ISSUE TITLE
Extend subscriptions to return initial data

### ISSUE THREAD

**Issue by kbrandwijk** [prisma/prisma1#239]
GraphQL subscriptions are, by specification, not designed to guarantee completeness of data. The delay between an initial query, and activating the subscription on the data, can cause missing data on the client.

The RFC allows subscription queries to return a response (other than the connection ack), so returning an initial data set is within specs.

**Comment by marktani** [comment]
It's not immediately clear what the initial data should return?

For this subscription

```graphql
subscription createPost {
  Post(
    filter: {
      mutation_in: [CREATED]
    }
  ) {
    mutation
    node {
      description
      imageUrl
      author {
        id
      }
    }
  }
}
```

We *could* return the most recently created 1000 `Post` nodes. Is that the behaviour that is always desired?

For this subscription

```graphql
subscription changedPost {
  Post(
    filter: {
      OR: [{
        mutation_in: [CREATED, DELETED]
      }, {
        mutation_in: [UPDATED]
        updatedFields_contains: "imageUrl"
      }]
    }
  ) {
    mutation
    node {
      id
      description
    }
    updatedFields
    previousValues {
      description
      imageUrl
    }
  }
}
```

I can't even come up with an initial data response that makes sense.

**Comment by kbrandwijk** [comment]
Good points, there's also this discussion: https://github.com/facebook/graphql/issues/283 that lead to the change in the RFC to allow any data to be returned from a subscription. But I agree that it's not always clear what initial data set belongs to a subscription...
I put it here to give the discussion a place to live, it's by no means a final solution.

**Comment by marktani** [comment]
> I put it here to give the discussion a place to live, it's by no means a final solution.
Absolutely, and I appreciate your input! Would love for everyone in the community to chime in if they have an idea.

**Comment by kbrandwijk** [comment]
IMAP / ActiveSync style patterns come to mind, that would involve keeping track of the last requested record (so you have a 'starting point' for the subscription), which is also impossible to do with the free query structure...

**Comment by kbrandwijk** [comment]
Additional thoughts on this one. Maybe for the IMAP/ActiveSync style, whenever a subscription is created from a client, it could get a unique id. And the server could keep generating responses for it, even though there is no active wss connection anymore. Then, when you restart your app later on, you would get the subscription results the server has 'cached' as initial response?

**Comment by eliezedeck** [comment]
+1 for this
