### ISSUE TITLE
Support SQL views

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma1#2412]
Most SQL databases support views and materialized views.

It should be possible to have a type in a Prisma service that is backed by a view or materialized view. These types would not generate mutations.

The underlying view or materialized view can either be managed by Prisma or already exist in the database.

**Comment by ToJen** [comment]
Hey @sorenbs is there an update for this?

**Comment by nicosuave** [comment]
As far as api goes, any thoughts on a schema directive `@pgView` with 2 params: view name & optional select statement? Come migrations, generate the `create or replace view` statement. `@materializedView` directive could add an argument for a cron frequency.

**Comment by chinnumv** [comment]
Any Updates ?

**Comment by HaiderShahid** [comment]
Any update on this ?
