### ISSUE TITLE
Google BigQuery connector

### ISSUE THREAD

**Issue by constant-wip** [prisma/prisma1#2442]
# Feature Request

Are there any plans to support Google BigQuery?
It would be really nice to add this one when dealing with huge datasets.
What do you think?

**Comment by lloydrichards** [comment]
This is also something i'm looking into at the moment as I'm building a new IoT data pipeline in GCP and would love to be able to build out some internal dashboarding using Prisma in Next.JS.  Any update on if this is in the works?  or not possible at all?
