### ISSUE TITLE
Support for Vitess

### ISSUE THREAD

**Issue by tslater** [prisma/prisma1#2451]
# Feature Request

**What feature are you missing?**
Support for Vitess (https://vitess.io/)

**How could this feature look like in detail? Tradeoffs?**
Luckily, this would be very similar to MySQL support, with some extra work on top. Vitess is the MySQL based sharding framework used by google.

**Comment by meodemsao** [comment]
And also support Citus (https://www.citusdata.com/)

**Comment by marcus-sa** [comment]
Seems like nobody cares about making Prisma extensible by adding more connectors...
How can that be?

**Comment by netspencer** [comment]
In order for my team to continue using Prisma, we need support for at least one Cloud Native (Kubernetes) DB. Either this or CockroachDB. I strongly believe there needs to be an emphasis put on this.

Or, at the very least, an article describing best practices using Prisma with Kubernetes, including the database aspect. Prisma itself works great on Kubernetes. But I want to know how to best host the database on Kubernetes as well

**Comment by derekperkins** [comment]
Vitess supports the MySQL protocol, so it should just work. I think there might be an issue with the old MariaDB driver causing issues (https://github.com/vitessio/vitess/issues/4603). I'm hopeful that the switch to the MySQL driver in this PR https://github.com/prisma/prisma/pull/3759 will solve the connection problem.

**Comment by meodemsao** [comment]
@netspencer can you sharing you solution deploy prisma in kubernetes ?
