### ISSUE TITLE
SQLite connector

### ISSUE THREAD

**Issue by benoror** [prisma/prisma1#2460]
# Feature Request

**What feature are you missing?**

Support for local databases such as SQLite

**How could this feature look like in detail? Tradeoffs?**

Should be straightforward since it's kinda standard.

My main use-case would be to create decentralized/portable/client-side-only (d)apps.

**Comment by Oroneki** [comment]
I agree. It would be interesting to use a prisma server hosted on a rapberry pi using just sqlite and served over an intranet.
There's another use case possible: enable sqlite in memory connection to speed up tests.

**Comment by nharlow89** [comment]
Would be great to add sqlite to the list of connectors #1751. In-memory and file-based db's are a big use case, especially when server-based db's are not an option and/or overkill. A couple specific use cases might be bundling sqlite into an Electron app or using sqlite on Android.

**Comment by marktani** [comment]
Thanks for your input, that's very interesting!

I added the new "File based" category to #1751. We are considering to directly bake a memory-based or file-based DB into Prisma, which would be nice for embedded use cases and local development.

**Comment by mnlbox** [comment]
+1
