### ISSUE TITLE
Other postgres column types

### ISSUE THREAD

**Issue by timwis** [prisma/prisma1#2466]
# Feature Request

**What feature are you missing?**
The ability to use postgres column types other than the basic string, integer, date, etc. Personally, I need to use [ltree](https://www.postgresql.org/docs/current/static/ltree.html) to represent a hierarchy, but others may want to use a geometry type, etc.

**How could this feature look like in detail? Tradeoffs?**
Probably something like a [custom scalar](https://www.apollographql.com/docs/graphql-tools/scalars.html) where we describe how to serialise and deserialise into PostgreSQL or something. Many of these types will require specific operators or functions to query them propery (e.g. `SELECT path FROM test WHERE path ~ '*.Astronomy.*'` or `ST_AsGeoJSON(geometry)`), so there would need to be a way to run raw SQL like most ORMs have.

Any chance this is already possible? I'm interested in how I'd accomplish this in the meantime because I need to use an ltree for my project, so otherwise I'd need to use something else to access my database :/

**Comment by BenoitRanque** [comment]
This would be very useful for my project as well. In my case I need to support Date, Time, DateTime, Timestamp, Interval, Duration PostgreSQL types. I have failed to find a way to add my own custom scalar types

**Comment by arnabkd** [comment]
Here's a extract of the unsupported types I got when I introspected one of my client's postgres DBs:
-  Type 'daterange' is not yet supported.
-  Type 'time without time zone' is not yet supported.
-  Type 'ARRAY' is not yet supported.
-  Type 'tstzrange' is not yet supported.
-  Type 'interval' is not yet supported.
-  Type 'ARRAY' is not yet supported.
-  Type 'jsonb' is not yet supported.
-  Type 'bytea' is not yet supported.

Note: this project isn't something that will use prisma (most probably not), so feel free to prioritise as much or as less as you see fit. This is just to add some documentation on what is missing right now I suppose :)

**Comment by gijo-varghese** [comment]
Any updates on this?

**Comment by HariSeldon23** [comment]
We'd also love `jsonb` support. Happy to help out if we can get some kind of consensus on how to implement

**Comment by plmercereau** [comment]
Hello,
Can we know if this issue is part of the roadmap? If not, how can we do to make it available faster? In my case, this is a must, and I wish it could be available so we could adopt prisma!
Thanks

**Comment by stephen-bunn** [comment]
Also wondering on support for these field types. At the very least `ARRAY` and `JSONB` are musts for many of my use cases.

**Comment by tutturen** [comment]
Support for ` jsonb` would be very nice.

**Comment by speix** [comment]
Any news on jsonb type support?

**Comment by randolphpark** [comment]
ARRAY

**Comment by brafdlog** [comment]
+1 jsonb and array

**Comment by secabhi** [comment]
Hi Any update on the support of following columns types
JSONB
TSVECTOR
CITEXT

**Comment by mikicho** [comment]
+1 jsonb

**Comment by beez-dev** [comment]
any updates on this?
