### ISSUE TITLE
DB2 Connector

### ISSUE THREAD

**Issue by rschultzgraycor** [prisma/prisma1#2467]
# Feature Request

**What feature are you missing?**
IBM DB2 Connector

**How could this feature look like in detail? Tradeoffs?**
Passive Connector for IBM DB2. Several enterprise databases such as JDE etc use DB2 and this would be a great addition to the Prisma Supported Databases.

**Comment by aamarin** [comment]
I'm interested in contributing to this item to speed it up if I can since I would like my team to eventually use this product.  I'm not sure where to inquire.
