### ISSUE TITLE
CouchDB Connector

### ISSUE THREAD

**Issue by rschultzgraycor** [prisma/prisma1#2468]
# Feature Request

**What feature are you missing?**
CouchDB/Couchbase Connector

**How could this feature look like in detail? Tradeoffs?**
Active/Passive connector for CouchDB/Couchbase

**Comment by sdgandhi** [comment]
Definitely interested in this as well.

**Comment by nyteshade** [comment]
Are there any solutions to this to date? Where are the docs to build one? I.e. where do I find reference for building a connector.

**Comment by kylemclaren** [comment]
@nyteshade I guess you'd start by looking at how existing connectors are implemented: https://github.com/prisma/prisma/tree/master/server/connectors

I don't think there are any docs describing how to build one.

**Comment by levarberry** [comment]
interested
