### ISSUE TITLE
Specify types and arguments on databases that support it

### ISSUE THREAD

**Issue by davidbarratt** [prisma/prisma1#2509]
# Feature Request

**What feature are you missing?**
There isn't a way to specify the string length (or type) on a string field for databases that support it.
https://www.prisma.io/forum/t/is-there-a-way-to-add-a-length-to-string-varchar/3546/2
Also, it might be beneficial to allow the type (`CHAR` or `VARCHAR`) to be specified or the arguments used for any of the other data types like `INT`
https://dev.mysql.com/doc/refman/5.7/en/create-table.html

**How could this feature look like in detail? Tradeoffs?**
Either we should add these arguments to the GraphQL type (i.e. `String` should allow the `length` argument) if that is even possible, if not, perhaps there should be some "easy" way to specify new primitive types? Like perhaps I could define a new `String` type that is of database type `CHAR(20)`?

The tradeoff would be that it cannot be assumed that a `String` is of the same length for the same field, but I think being able to extend the primitives would aliviate that (and would allow a place to document the restrictions).

**Comment by affanshahid** [comment]
Any update on this? Is it possible to specify string field length

**Comment by mikepuglisi** [comment]
I'm interested in this too. 

Also wondering...aren't there performance implications to storing all strings as a "mediumtext" column in mysql? (as opposed to designing tables as varchars to match the expected data lengths)

**Comment by carstenbaumhoegger** [comment]
I'd also need this feature. Currently, we always have to check for a specific maximum length inside of our resolvers, this would make all of this logic obsolete, which would be very nice!

**Comment by kokokenada** [comment]
+1

**Comment by Lohann** [comment]
+1

**Comment by hoffnung8493** [comment]
+1

**Comment by MohamedElmdary** [comment]
+1

**Comment by VulgarnyKarlson** [comment]
+1

**Comment by lucasferreiralsf** [comment]
+1

**Comment by mukhlim** [comment]
+1

**Comment by jhaemin** [comment]
+1

**Comment by cmdshepard** [comment]
+1
