### ISSUE TITLE
Ability to choose pluralized name for a field

### ISSUE THREAD

**Issue by cameronk** [prisma/prisma1#253]
I have a `Person` field that becomes `Persons` when pluralized for things like `allPersons`, etc.

I'd like the ability to change this to `People`.

**Comment by CameronK** [comment]
I'd also be interested in the ability to configure how some attributes are named. 

For example, let's use the nested mutations example from [the docs](https://www.graph.cool/docs/reference/simple-api/nested-connect-mutations-tu9ohwa1ui/). An `Author` has a *1:N* relation with `Post`.

`Author` | `Post`
----------|--------
id: ID! | id: ID!
name: String! | title: String!
posts: [Post!]! | author: Author!

Let's say I want to create an Author and connect them to two post IDs. The auto-generated name for this is `postsIds`, using the pluralized name from the `Author` type. Would be nice if I could change this / enable a setting that converts it to the `postIds` form.
