### ISSUE TITLE
Chromeos / Crouton / Crosh support

### ISSUE THREAD

**Issue by lucasavila00** [prisma/prisma1#2592]
# Feature Request

**What feature are you missing?**
I'd like to be able to use Prisma services on my Chromebook using crouton via crosh.

**How could this feature look like in detail? Tradeoffs?**
The problem is that when you launch a new browser window and that window can't be opened prisma will exit with code 3.
Crosh won't open links but you could do what Create React App does and **ignore the fact that the browser hasn't opened and print the url which I can type on the browser.**
I have run into issues with this using `prisma login` and `prisma playground`.

Right now I have to log onto XFCE so that the browser opens when I run playground for instance, then I close XFCE and open the url on chromeos and all is fine.

**Comment by degroote22** [comment]
They use this implementation to open the browser window: https://github.com/facebook/create-react-app/blob/next/packages/react-dev-utils/openBrowser.js

I haven't found Prisma's yet but I'm trying to stitch a PR myself.

**Comment by degroote22** [comment]
I have submitted PRs for those issues.
I guess this can be closed.

Thanks for your awesome work!

**Comment by marktani** [comment]
Thanks a lot for your contributions @degroote22! We'll review them soon. In the meanwhile, I'll reopen this issue and will close it once those PRs land 💯
