### ISSUE TITLE
Collection of Postgres flavors

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#2700]
This is a collection of various Postgres flavors. Over time, we will identify what is needed to support connectors for the different flavors, and what specific features can be exposed.

* Timescale
* [CockroachDB](https://github.com/prismagraphql/prisma/issues/1705)
* [CrateDB](https://github.com/prismagraphql/prisma/issues/2689)
* [PostGIS](https://github.com/prismagraphql/prisma/issues/1760)

**Comment by orefalo** [comment]
Let me add a few

https://www.pipelinedb.com/
https://github.com/timescale/timescaledb

**Comment by tsaiDavid** [comment]
PostGIS support would be amazing, would allow us to evaluate Prisma usage in production

**Comment by chrisbull** [comment]
Does anyone have a work around in the meantime for Geometry/Geolocation column returns? Hasura offers this out of the box, but i'd prefer to stay with Prisma. Thanks in advance

**Comment by thakkaryash94** [comment]
[yugabyteDB](https://www.yugabyte.com/) is also Postgres compatible with distributed SQL support.
