### ISSUE TITLE
JSON values have storage limit of 256kb, will throw error 'Value for field <field name> is too long' if value size limit exceeds.

### ISSUE THREAD

**Issue by 5hanth** [prisma/prisma1#2705]
`Json` type fields have [storage limitation of 256kb](https://github.com/prismagraphql/prisma/blob/1dee235f82f7481828d1ae0b3a1ab0c8e95ebe3a/server/servers/api/src/main/scala/com/prisma/api/mutactions/validation/InputValueValidation.scala#L28). There might be applications that require `LONGTEXT` length support to store `JSON` values.

it would be great if we could remove this limitation at application level and let db handle limits (not sure if this can be desired for all scalar types, but for this case Json value can go longer than 16MB)

**Comment by nolandg** [comment]
Has anyone found a workaround for this? This is a show stopper for my app that stores JSON objects of about 350kb. It seems this isn't a postgres limit but something hard coded by Prisma. Is the only way to fork Prisma and hack that line linked to above? Or is it more complicated and Prisma is also limiting the db field size when creating the db schema?

**Comment by gmickel** [comment]
I would also be interested in having the limits String and JSON fields made configurable. Our app has to save large documents and we're having to use ugly workarounds at the moment.

**Comment by gmickel** [comment]
Any update regarding this? We're planning on launching later this month and are blocked by this. Thanks!

**Comment by nolandg** [comment]
Can you just gzip the value into a string? JSON often compresses pretty
well.

You could also make your field an array of strings and chunk your data.

**Comment by gmickel** [comment]
I used gzipping as the workaround I mentioned earlier in this thread. Naturally, that only delays the inevitable, our system deals with documents that can be up to around 1MB in size and due to their complexity (programmable documents) and the real-time nature of our platform, I can't easily split them into smaller pieces.
I'm wondering if the current limits on the String and JSON fields are arbitrary or due to a specific constraint?

**Comment by nolandg** [comment]
My assumption is that it was a lowest common denominator issue to harmonize
the various DBs.

**Comment by gmickel** [comment]
That's definitely possible, yes. In that case, simple configuration flags (as mentioned [here in the docs](https://www.prisma.io/docs/datamodel-and-migrations/datamodel-MYSQL-knul/#fields), but don't seem to exist) might be a viable solution.

**Comment by WaNgeL-SaTaR** [comment]
Any suggestion on Json type field length?

**Comment by entrptaher** [comment]
This is a high priority problem for us. We have a production app that depends on some 300-500kb data. We have a very small 500KB-5MB data, and now our server is throwing errors when we work on that table/data.

It's not specified anywhere why *Json values are currently limited to 256KB in size.*

The docs links to which seems to be closed/stalled for many months/years. The following issues are related yet no solution/workaround provided:
- https://github.com/prisma-labs/http-link-dataloader/issues/8 throws a real error on the client
- https://github.com/prisma/prisma/issues/748#issuecomment-349063876 was requested 
- https://github.com/prisma/prisma/issues/353 means it was on prisma version 1 roadmap but wasn't added

**Comment by entrptaher** [comment]
They put a 256KB limit so I created a 50MB  
workaround (only), because that's not configurable yet, without building the prisma code myself. 😅

**Comment by kunovsky** [comment]
I just ran into this issue myself trying to store ~300KB JSON Objects and thought I'd share my quick fix here incase folks found it helpful. As recommended above I ended up changing the data type for the attribute I was storing from `JSON` to `String` and then compressed and decompressed the data on storage and retrieval from the DB. To be safe I tested this with 15MB of `JSON` and it works fine, so no need to split the data up. FYI before you run `deflateData` on the Object make sure you `JSON.stringify` it so `Brotli` can accept it.

```js 
// compressionUtils.js

import * as zlib from 'zlib'

const base64 = 'base64'

export const deflateData = data =>
  zlib.brotliCompressSync(data).toString(base64)

export const inflateData = data =>
  zlib.brotliDecompressSync(Buffer.from(data, base64)).toString()
```

We're using `graphql-yoga` so in my mutation and query I'm just running `deflateData` and `inflateData` respectively before I store/retrieve it.

Obviously you will lose the ability to query `JSON` the data in the database if you do this, but if you need to store large documents at massive compression this seems like an acceptable workaround.

**Comment by entrptaher** [comment]
@kunovsky I did test with zlib before splitting it, zlib was working fine as well, but it would not allow me to store binary or serious data (non-compressible string). So I had to forcefully split and join it.

I will suggest others to try zlib just like your example if the data is compressable. :)
