### ISSUE TITLE
Default value directive for list of scalars

### ISSUE THREAD

**Issue by codepunkt** [prisma/prisma1#2723]
**Is your feature request related to a problem? Please describe.**
I want to provide a list of static default values for a list of scalars.

**Describe the solution you'd like**
```graphql
type User {
  roles: [UserRole!]! @default(value: ["User"])
}

enum UserRole {
  User
  Admin
}
```

**Describe alternatives you've considered**
Since we're talking about static values, enforcing this in userland code seems like a bad fit.

**Comment by marktani** [comment]
I can confirm that this does not work as of now.

Deploying this datamodel:

```graphql
type User {
  id: ID! @unique
  name: String!
  ints: [Int!]! @default(value: "[1, 2, 3]")
  strings: [String!]! @default(value: "[\"1\", \"2\", \"3\"]")
  enums: [MyEnum!]! @default(value: "[A, B, C]")
}

enum MyEnum {
  A,
  B,
  C
}
```

results in this deploy output:

```sh
Creating stage dev for service r-2723 ✔
Deploying service `r-2723` to stage `dev` to server `prisma-eu1` 164ms

Errors:

  User
    ✖ List fields cannot have defaultValues.
    ✖ List fields cannot have defaultValues.
    ✖ List fields cannot have defaultValues.
    ✖ The defaultValue contains an invalid enumValue.

Deployment canceled. Please fix the above errors to continue deploying.
Read more about deployment errors here: https://bit.ly/prisma-force-flag
```

**Comment by vihuvac** [comment]
This is a very useful feature and I would like to see it soon!

**Comment by guigaoliveira** [comment]
Any progress? =)

**Comment by ConnerNovicki** [comment]
Would love to see this :)

**Comment by codingfunwoody** [comment]
will fix it on prisma 2?

**Comment by ahrbil** [comment]
Will this be supported on Prisma 2?
on Prisma 1 this is not possible

**Comment by BrenoMazieiro** [comment]
Any news about it! It would be really nice to have it!
