### ISSUE TITLE
"prisma list" does not show locally deployed services

### ISSUE THREAD

**Issue by kimobrian** [prisma/prisma1#2764]
**Is your feature request related to a problem? Please describe.**
`prisma list` command only lists services deployed remotely. So far I've only used Prisma cloud and only services on prisma cloud are shown. The ones deployed on docker locally are not.

**Describe the solution you'd like**
Also show locally deployed services when the command `prisma list` is run.

**Comment by kevinmarrec** [comment]
@marktani I can't understand why this feature is still not implemented 🤔, it must be a pain for entreprises using prisma locally with Docker and can't know what are the different stages of their differents local services !

**Comment by kevinmarrec** [comment]
`prisma list` should result in
```
Service Name  Stage  Server
────────────  ─────  ──────────
test          dev    prisma-eu1
test-local    dev    local
test-local    beta   local
```

Only services from Prisma Cloud Demo Servers are displayed, as described in the issue

**Comment by kevinmarrec** [comment]
`prisma list` should use Management API `listProjects` Query when using Docker setup :

![screenshot_6](https://user-images.githubusercontent.com/25272043/48476376-28ae7a00-e7ff-11e8-8f1e-22721c9396c4.png)
