### ISSUE TITLE
Prisma delete - service name

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma1#2788]
**Is your feature request related to a problem? Please describe.**
`prisma delete` relies on the service definition (`prisma.yml`) to delete a service.

**Describe the solution you'd like**
It should be possible to delete a service by its name. 
`prisma delete <service-name>`

**Describe alternatives you've considered**
I use Prisma cloud to delete services.

**Comment by marktani** [comment]
This way of using `delete` can provide a better experience. We need to consider how to handle these edge cases:

* multiple stages for the same service name
* multiple workspaces with the same service name

**Comment by JensMadsen** [comment]
suggestion if `prisma delete <service-name>` is not supported then: 
- do not silently NOT use argument passed to `prisma delete`, e.g. `prisma delete <my-service-name> should yield an error in the line with "please specify the endpoint of the service you would like to delete in prisma.yml"
-  add same informatino to `prisma help delete`
