### ISSUE TITLE
Database migrations output to a file

### ISSUE THREAD

**Issue by WebDevMichael** [prisma/prisma1#2792]
**Is your feature request related to a problem? Please describe.**
Imagine you have 2 environments, a development and a production environment. When you are developing and changing the datamodel, the database gets updated in your development environment when you do "prisma deploy". But then you need to update your production database. The production database structure should be updated in a controlled manner.

**Describe the solution you'd like**
Prisma should provide a SQL file containing the queries it executed when it updated the database structure in the development environment. In the prisma YAML file the developer should be able to define if they want such a file by adding an additional property containing the destination path of the SQL file. When this path is defined, Prisma will export the SQL to that path, if it is undefined, it won't do this.

**Describe alternatives you've considered**
A more complex feature would be that it would incorporate the [Umzug](https://github.com/sequelize/umzug) library, and generate the migration files to javascript files in the Umzug format.

**Comment by divyenduz** [comment]
This is covered with the [migrations RFC](https://github.com/prisma/rfcs/blob/migrations/text/0000-migrations.md). Please share your feedback.
