### ISSUE TITLE
Support for RavenDB as a No SQL Database 

### ISSUE THREAD

**Issue by rwatts3** [prisma/prisma1#2816]
**Is your feature request related to a problem? Please describe.**
No this feature request is not related to a problem more a request or proposal. 

**Describe the solution you'd like**
I'd like to propose adding RavenDB as a No SQL Database option to the list of databases.

**Describe alternatives you've considered**
I have not considered any alternatives. RavenDB would greatly complement the efforts that are in place to support MongoDB.

**Additional context**
https://ravendb.net

If core support for a RavenDB database cannot be implemented by the Prisma staff or will be marked as declined, would it be possible to provide documentation or guidance on how one could create a community plugin or module that would hook into prisma and allow for the support of RavenDB.

**Comment by rwatts3** [comment]
Thank you for accepting this feature request. 
Is there documentation for contributors specifically contributors to connects that I can follow and possibly get this started as a Pull Request ? 

On that note is there documentation in general that would guide a contributor in the right direction for contributing to connectors in general. 

I believe having this guide or documentation may help streamline the connector process and also allow for more collaboration from the community to roll out connectors faster.

**Comment by sorenbs** [comment]
Thank you very much for offering to contribute a RavenDB connector!

We are currently working on the MongoDB connector. When this is available it should be much easier to build the Raven connector, and I would love to help you start that PR. I would estimate 1-2 weeks of full time work for our internal engineers to build a solid Raven connector, so it is important that you keep the scope in mind before diving in.

**Comment by githubfanster** [comment]
i'm interested in RavenDB support. I was wondering if work has started on this now that the MongoDB support is in preview?  thanks for new info!
