### ISSUE TITLE
Support for views with spaces in introspection

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma1#2834]
**Describe the bug**
If the `prisma introspect` command is run against a schema with a view that has a space in its name, the generated `datamodel.graphql` has a type with a space in it. That datamodel is incorrect. 

**To Reproduce**
1. It is reproduced in the [snapshot](https://github.com/prisma/prisma/blob/master/cli/packages/prisma-db-introspection/src/tests/postgres/__snapshots__/largeSchema.test.ts.snap#L81) of the tests for introspection. 

**Expected behavior**
The `prisma introspect` command should generate a valid `datamodel.graphql` that can be deployed. 

**Screenshots**

**Versions (please complete the following information):**
 - `prisma` CLI: `prisma/1.12.0 (darwin-x64) node-v10.4.0`
 - Prisma Server: [e.g. `1.12.0`]

**Comment by divyenduz** [comment]
This is still a bug.

**Comment by mavilein** [comment]
Still a bug.
