### ISSUE TITLE
@unique with a specified context

### ISSUE THREAD

**Issue by panbanda** [prisma/prisma1#2853]
**Is your feature request related to a problem? Please describe.**

I have a situation where a user can only belong to one organization.  This means that in a multi-organization situation a user can use their email to log into two different organizations with a specified context.  However, this doesn't work with the `@unique` specifier now.

**Describe the solution you'd like**

Can we create a way to specify `@unique(column_name)` or something to that it creates a unique index on multiple columns?

**Describe alternatives you've considered**

I could just take off the unique indexing and manually check in the resolvers.

**Comment by mavilein** [comment]
I have just published [spec](https://github.com/prisma/prisma/issues/3408) that touches on this topic. We would love to hear your feedback on this one.
