### ISSUE TITLE
Resources on deploying Prisma to production

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#2859]
**Describe the content you'd like to see**
A central place in the documentation that I can follow to deploy Prisma to production. It should cover a broad range of topics, such as authentication, CI/CD, and touch on different methods to actually deploy Prisma (whether it's on Digital Ocean, AWS, GCP, ...).

**Additional context**
There are some scattered discussions in the Forum and on GitHub, only collecting and summarizing those would already be a big win.

**Comment by AAlvarez90** [comment]
Adding a bit to the description of this issue. It would be great if such documentation does not tie Prisma to a specific technology. For example, I would like to know how I can deploy prisma to an absolute newly-created ubuntu server and not through Prisma Cloud, Heroku, or through Kubernetes.
