### ISSUE TITLE
Unify docker images `prisma` and `prisma-prod`

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma1#2869]
**Is your feature request related to a problem? Please describe.**
We have 2 different images for local prisma and actual production deployments. The difference between those are:
- the prod image can disable the Management API by setting `managementApiEnabled: false` in the server config
- the prod image always tries to connect to a RabbitMQ specified by the `rabbitUri` property.

**Describe the solution you'd like**
We should only have one Prisma image that:
- respects the `managementApiEnabled` setting
- decides whether to use RabbitMQ or not depending on the presence of the `rabbitUri` property.

**Describe alternatives you've considered**
None

**Additional context**
I stumbled upon this issue while i advised people on a production setup for Prisma in this [issue](https://github.com/prismagraphql/prisma/issues/2850). They were trying to disable the Management API for the local image which was not possible.

**Comment by jhalborg** [comment]
@mavilein - This would indeed be easier to understand. 

I have two followup questions:
1. Are there any other differences between the two?
2. Do you not recommend using `prisma` in production (when protected by a management API secret)? If not, how come?

**Comment by frandiox** [comment]
@mavilein Do we still need to use `prisma-prod`?

> decides whether to use RabbitMQ or not depending on the presence of the rabbitUri property

If we have 1 "primary service" for deployments (`managementApiEnabled: true`) and 1 "secondary service" for actual requests (`managementApiEnabled: false`), do we need RabbitMQ? Will the secondary server notice schema changes without it?

**Comment by mavilein** [comment]
@frandiox : Yes you need it. The RabbitMQ is used to propagate datamodel changes from the management server to secondary ones.

**Comment by hitech95** [comment]
@mavilein I'm creating an Helm chart for Prisma-Prod.
I was looking for the Dockefile that generates the `-heroku` suffix.

Due to secrets handlinkg in kubernets I would need a pruduction like docker image with the `-heroku` suffix:
https://github.com/helm/charts/issues/13530#issuecomment-570154690

Unfortunatly I didn't find anything on this repo, I would create my own production like image with the heroku env handling.
