### ISSUE TITLE
Multi Connector Endpoint

### ISSUE THREAD

**Issue by rwatts3** [prisma/prisma1#2873]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to a problem.

**Describe the solution you'd like**
Ability to hit a single prisma endpoint and query , mutate, subscribe to data coming from multiple prisma servers.

**Describe alternatives you've considered**
No alternatives considered, although an alternative in theory would be to write connections to each of the instances by hand within Prisma GraphQL server but this is not ideal for the use case.

**Additional context**
Per the question posted on slack and suggestion from @schickling here is the context of my request.

----

Is it possible to have multiple database endpoints in the same Prisma Application.
For example multiple connections accessible via a single Prisma Endpoint.
I'd like to hit my prisma endpoint and get data from any connection associated with it. 

**Use case**, if i'm working on a Data Science project, and I'm using mysql that has existing data , but also want to get data from my MongoDB endpoint. 
The workflow would be a lot simpler to hit my standalone prisma instance and grab data arbitrary of where it's stored, by knowing what mutation or query I need to pull the data

**Comment by sorenbs** [comment]
Multi-database prisma services doesn't yet exist in Prisma, but we have big plans for this feature. I'm really excited for this feature and believe it will allow a lot of companies to significantly simplify their code base when working with multiple databases.

**Comment by jferrettiboke** [comment]
@sorenbs Any update on this?

**Comment by newtmex** [comment]
I would love this feature. Being able to use prisma to connect to different database of the same DMS. Example having two database on MySql and using Prisma to connect to and manipulate them.

So a workaround for this will be to create different Prisma Servers as needed for each database?

**Comment by mcarpenterjr** [comment]
Currently interested in this as well, has there been any progress on this? Or has some other solution been created that is better? Or is there a new design pattern that makes this obsolete?
