### ISSUE TITLE
[Discussion] the schema setting should be per service when using existing databases

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma1#2890]
**Is your feature request related to a problem? Please describe.**
I see two problems with our current approach to setting the schema name for a connector that is connects to an existing database (`migrations: false`):
1. You have to specify the schema in 2 locations. Once when triggering the introspection and once in the server configuration. I think a lot of people are not aware of this subtlety as we take care of this for local setups in `prisma init` by generating the docker compose file correctly. Another hint for this observation is the fact that bug reports for the passive connector rarely add the server config they used.
2. Normally Prisma is inherently multi tenant. Each service resides in its own schema/database. However the `schema` setting in the server config locks a server to one schema. You can still deploy multiple services but they will always interact with the same schema.

**Describe the solution you'd like**
I think it would be more intuitive if the `schema` setting would be part of the configuration of a service that gets deployed with `prisma deploy`. This would also enable Prisma to connect to multiple schemas in a database. It would reduce the surface for errors as well.

**Describe alternatives you've considered**
None

**Additional context**
We could even widen this discussion to other settings in the server config, e.g. the `migrations: true|false` setting. It might be beneficial to make this a per service config to enable the simultaneous operation of active and passive services.

**Comment by marktani** [comment]
A related suggestion is to denote the according schema on a per type level: https://github.com/prismagraphql/prisma/issues/2477
