### ISSUE TITLE
"Clone service" feature

### ISSUE THREAD

**Issue by jerryjappinen** [prisma/prisma1#2894]
**Is your feature request related to a problem? Please describe.**
When refactoring my backend or developing new features, I need to often test out several different schema changes before committing to any final structure. Currently I'm also happy developing against hosted services and not having any local Prisma servers.

In these cases, I usually create a new branch in my backend codebase and start normal development work. Ideally I'd like to have a Prisma service to match that I can freely play around with and perhaps leave behind when my feature completes. I can actually do that right now using the following steps:

1. `prisma export` existing data to a local file
2. `prisma init` a new service
3. Copy endpoint over from newly generated `prisma.yml` to my existing one (or some local override file, or something to that effect)
4. Clean up all files left over by `prisma init`
5. `prisma deploy` my existing schema to new endpoint
6. `prisma import` the backup from step 1

The end result is pretty much what I want, but it's pretty labor intensive and you have to have a detailed understanding of how each command works while doing it. Also this has to be done in your local environment with the CLI even though duplicating services doesn't really require any local changes. Temporary backups and files left over by `prisma init` also easily makes their way into version control by accident.

**Describe the solution you'd like**
I would love to be able to simply clone any of my services (including both schema and data), so I could easily branch off any of the development services I'm using and connect to it in my development environment. The first thought that came to mind was that I want to easily spin up a new branch-specific development service that I can freely play around with.

I could write a custom script to do some or all of the steps above, but I think the natural solution would be to have that script as part of the CLI (it already has all the relevant parts I listed earlier, but no combined command for the whole flow).

Then again, I don't see any reason why I shouldn't just be able to do this on Prisma Cloud. For me it's more natural to understand what environments I have available using the Cloud UI, edit them there, and then choose which one I want to hook up to development environments.

TBH I've never played around with stages for the services, and it would seem counter-intuitive to use them for this purpose but perhaps using different stages as opposed to cloned services could also be an option. I'm not sure if this would work well with more than one developer or when working on several features in parallel. Perhaps as part of #2732 this will be explained better.

**Describe alternatives you've considered**
I don't really know if there's something else regarding my development flow that I should do differently, but definitely for rapid testing and prototyping I can see the clone feature being extremely useful. Perhaps I'm looking at this the wrong way altogether and just don't have the right workflow overall.

**Comment by schickling** [comment]
This is a fantastic feature proposal and definitely something we're interested in. Before implementing this from our end, we'd love to hear more similar use cases and opinions on this. What are the workarounds people are currently using to accomplish this?

**Comment by Eiskis** [comment]
One small thing to perhaps mention is that currently the schema definition is part of my backend codebase (single repo). So in this scenario schema changes will be in the same version control and any changes will make their way into branches/PRs etc.
