### ISSUE TITLE
Server Config should allow to specify separate reader and writer endpoints

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma1#2895]
**Is your feature request related to a problem? Please describe.**
AWS Aurora allows to multiple read replicas to a cluster. A cluster exposes two separate endpoints for writing and reading. It should be possible to add the reader endpoint to the server config.

**Describe the solution you'd like**
The server config should have an additional key, e.g. `readerHost` that is optional. If that key is present this url will be used for reads. The normal `host` key will be used for writes.

**Describe alternatives you've considered**
None

**Additional context**
I encountered this issue while talking with a customer.

**Comment by bdeo** [comment]
Has anyone found any workarounds for this or able to achieve reader prisma services, and a writer service?
