### ISSUE TITLE
Provide ARM Compatible Docker Image

### ISSUE THREAD

**Issue by Oroneki** [prisma/prisma1#2909]
I want to be able to deploy a Prisma Service to my Raspberry Pi, but there is no ARM compatible docker image. It would be nice to test my Yoga Server at home. There are still postgres and redis compatible images, just the Prisma is missing.

**Comment by marktani** [comment]
This might be helpful: https://www.prisma.io/forum/t/build-prismagraphql-prisma-1-8-docker-image-manually-for-arm-device-deployment/3552/2?u=nilan
