### ISSUE TITLE
Customize Management Api Endpoint

### ISSUE THREAD

**Issue by bergold** [prisma/prisma1#2949]
**Is your feature request related to a problem? Please describe.**
I have multiple prisma containers deployed to a docker swarm network with a single domain. Requests are routed using a reversed proxy (Traefik). Now I want to deploy my prisma services to specific prisma instances. They are reachable at, for example `example.com/`**`prisma_1`**`/rocket_service/staging` and `example.com/`**`prisma_2`**`/service_abc/staging` and the management apis are reachable at `example.com/`**`prisma_1`**`/management` and `example.com/`**`prisma_2`**`/management`. 

Deploying via the CLI is now impossible, because it derives the management api endpoint from the prisma endpoint. So it assumes `example.com/management` as the management api endpoint.

**Describe the solution you'd like**
My preferred solution would be to have a setting in the prisma.yml file to override the management api endpoint that is then used by the cli, like so:
```
endpoint: https://example.com/prisma_1/rocket_servive/staging
managementApiEndpoint: https://example.com/prisma_1/management
```

**Additional context**
There is also a feature request to allow listening for the management api on a different port: #2331 
In order to make that possible, a feature like what I described above would be neccessary.

**Comment by danielmahon** [comment]
Not sure if this is related but `prisma deploy` fails with `ERROR: Authentication token is invalid: Token can't be decoded: Invalid signature for this token or wrong algorithm.` when trying to redeploy to existing service. It also only seems to happen when logged in to prisma cloud via the cli and `config.yml` contains the cloud key. If I `prisma logout` and make sure `config.yml` is reset to `clusters: {}` I don't get the error anymore...
