### ISSUE TITLE
Allow Database Entries to have a TTL

### ISSUE THREAD

**Issue by Plinpod** [prisma/prisma1#295]
Would like to see entries have the option of setting a TTL, so they would delete themselves after X amount of seconds. 

Would be very useful for timed assets such as temporary download and password reset tokens, post image or videos assets that should only be accessible for a temporary period of time. 

This feature would allow for a much more elegant solution on the database side, then having to generate cron jobs to check timestamps for each entry. 

Thanks!

**Comment by sedubois** [comment]
Related to #182 for files.

**Comment by pantharshit00** [comment]
related to #4012
