### ISSUE TITLE
Prisma as a standalone library

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#2992]
**Is your feature request related to a problem? Please describe.**
Deploying a minimal Prisma setup might be more involved than desired, due to the current (effective) requirement of running it inside Docker.

**Describe the solution you'd like**
Run Prisma in the same machine or even same process as the application server. For example, when I run a Node GraphQL Server, there could be a npm library that runs in the same Node process. Similarly for Go servers, Python, ... .

Another option is to expose Prisma as a daemon. Running Prisma would be as simple as `prismad --config path/to/prisma/config`.

**Describe alternatives you've considered**
Make running Prisma inside Docker significantly easier, provide direct cloud integrations for a Prisma setup, and/or provide more/better documentation for Prisma deployment.

**Additional context**
We are soon sharing more details on this topic 🙂

**Comment by cktang88** [comment]
Is there an update on this?

**Comment by jonleopard** [comment]
Would also love to see how to get prisma set up without docker on a server :)

**Comment by GERJohnson** [comment]
+1 get rid of docker:-)

**Comment by meodemsao** [comment]
Have any update on this ?
How to deploy as Prisma as jar packages?

**Comment by Lotuashvili** [comment]
+1 Without a Docker 👍

**Comment by CaptainChemist** [comment]
I would love this! Any idea if it would work in a lambda express server or would the focus be on an express server that is continuously running?

**Comment by jleed** [comment]
docker is nice BUT WE'LL LOVE TO GET RID IT!

**Comment by benseitz** [comment]
Would this also mean getting rid of RabbitMQ?
So adding prisma client as a library to a serverless function would be an ideal use case.
Similar to [Postgraphiles schema-only usage](https://www.graphile.org/postgraphile/usage-schema/).

**Comment by Thebigbignooby** [comment]
I was looking forward to playing around with prisma until I realised it requires Docker.
Ok, I accept the tradeoff and start installing Docker only to realise it doesn't work in WSL ... So, I need to install it under windows. Does that mean I need to install node & databases under windows too ?

Documentation on the respective websites of docker/mysql/mongodb for installation on windows aren't very clear and I'm wasting a lot of time trying to install these things under windows. for example they require packages which must be installed with visual studio, but it's not 100% evident which boxes I need to tick so as to install the required packages only and not useless ones.

I can live with Docker, if someone from the Prisma team or the community can write a comprehensive step by step guide for 4 year olds to get up and running with prisma development on windows, please!

I'll end up writing it if no one else does by the time I figure things out by myself, I've already wasted a few days on this (I even tried installing linux in dual boot, but being on a microsoft device, there are plenty of bugs with kernel drivers etc, the pain is real)

... Or just get rid of Docker 🙃

**Comment by brafdlog** [comment]
If prisma runs in the same process its seems like supporting hooks into the query building process would be possible. This could be a very powerful feature. (postgraphile supports it as well)

**Comment by oreillyross** [comment]
Remove dependency on Docker, Its an issue for me (and others I imagine) that work mostly in cloud based IDEs - it is difficult to get Docker running in a virtual environment, mostly because docker itself hosts the virtual environment.

**Comment by Zireael** [comment]
I've had more luck using postgraphile

```
const express = require("express");
const { postgraphile } = require("postgraphile");

const app = express();

const postgresConn = "postgres://username:password@localhost:5432/postgres";

const options = {
	classicIds: true,
	graphqlRoute: "/graphql",
	graphiqlRoute: "/graphiql",
	graphiql: true, //!IS_PRODUCTION,
	enhanceGraphiql: true, //!IS_PRODUCTION
	exportJsonSchemaPath: "./schema.json",
	enableCors: true
	// jwtSecret: "123",
	// jwtPgTypeIdentifier: "discipuli.jwt_token",
	// pgDefaultRole: "anonymous"
};

app.use(postgraphile(process.env.DATABASE_URL || postgresConn, options));

app.listen(process.env.PORT || 3000);

console.log(
	`GraphQL listening on http://localhost:${process.env.PORT || 3000}`,
	"\n",
	`GUI: http://localhost:${process.env.PORT || 3000}${options.graphiqlRoute}`
);
```

**Comment by agniswarm** [comment]
+1 The things is cool. would be way cooler without Docker.

**Comment by kateile** [comment]
+1 get rid of docker

**Comment by pantharshit00** [comment]
This is basically implemented in Prisma 2.

Please read more about it here: https://www.prisma.io/blog/announcing-prisma-2-zq1s745db8i5/
