### ISSUE TITLE
Generated schema of collection is missing `required` annotation for items.

### ISSUE THREAD

**Issue by brikou** [prisma/prisma1#2999]
**Describe the bug**

Generated schema of collection is missing `required` annotation for items.

**To Reproduce**

1. Create a datamodel.graphql like this

```graphql
type Book {
    id: ID! @unique
    title: String!
    author: String!
}
```

2. Deploy to prisma server with `prisma deploy`
3. Run schema intropspection and search for book, with graphql-cli `graphql get-schema --endpoint http://localhost:4466 --console|grep books`

Then, we can read:

```graphql
type Query {
    books(
        where: BookWhereInput
        orderBy: BookOrderByInput
        skip: Int
        after: String
        before: String
        first: Int
        last: Int
    ): [Book]!
    
    # ...
}
```

**Expected behavior**

The return type should be `[Book!]!` and not `[Book]!`, otherwise this mean we can have this kind of response `[null]`... :disappointed: 

```diff
@@ -7,7 +7,7 @@
         before: String
         first: Int
         last: Int
-    ): [Book]!
+    ): [Book!]!
 
     # ...
 }
```

**Versions (please complete the following information):**
 - OS: `Ubuntu 16.04`
 - `prisma` CLI: prisma/1.15.1 (linux-x64) node-v8.11.4
 - Prisma Server: `1.15.1`

**Additional context**

This problem leads to wrong typing when using TS codegen.

**Comment by brikou** [comment]
it comes from scala, not printer

**Comment by marktani** [comment]
This is not necessarily a bug, but a request to change the current behaviour. We need to review the exact consequences of potentially applying this change, and what that means for code generation, client usage and more.

**Comment by brikou** [comment]
@marktani agreed, but it is sometimes difficult to understand why an entry in an array may be null.
