### ISSUE TITLE
Return default values in __schema query

### ISSUE THREAD

**Issue by chasm** [prisma/prisma1#3016]
**Is your feature request related to a problem? Please describe.**

I use a __schema query to provide metadata for my CRUD forms, rather than hard-coding that data and having to worry about values getting out of synch. Currently, I have to hard code default values for fields, which makes auto-generating forms difficult.

**Describe the solution you'd like**

I'd like to be able to run a __schema query and have fields return the actual default values associated with them, if any. There appears to be a `defaultValue` field, but it does not report the default value. For example, I have an `isPublished` boolean field that defaults to `true`, but this is not reported by the __schema query.

In general, my goal is to be able to run a __schema query (or, better, include __schema information in any query) and retrieve enough information to be able to automatically generate a form.

**Describe alternatives you've considered**

There doesn't seem to be one, which is frustrating. I considered using the `description` field, but that doesn't seem to work (yet), and it would still pose the risk of a conflict.

**Comment by divyenduz** [comment]
The `defaultValue` directive makes the default value available for a field at DB level of none is provided. Then querying that data should yield the default value. Is that not the case for you?
