### ISSUE TITLE
Add validation to fields in the schema

### ISSUE THREAD

**Issue by chasm** [prisma/prisma1#3017]
**Is your feature request related to a problem? Please describe.**

I want to make sure that the schema does not allow values that don't meet a set of criteria. And if I could query the __schema and get back something workable that I could use on both the API server and the front-end client to perform validation, that would provide a single source of truth. It seems to me that the schema _should be_ the single source of truth.

**Describe the solution you'd like**

On any field, I'd like to be able to inject a function that would determine whether an update to that field could take place. For example, I might want to validate an Email or Url field against a regular expression, or check that an Int is between upper and lower bounds.

Not sure exactly how one could inject a function into the schema. Might have to be done at the resolver level, though that's much less ideal. For me the most important part (besides ensuring good data) is being able to query for the validation function and use it to validate on both the server and client sides -- so there is _one_ source of truth for the field. Essentially, I want to be able to be very specific with my types, way beyond simply Int or String.

**Describe alternatives you've considered**

Currently doing this in the resolvers and trying to work out how to create queries to permit the front end to utilize the same functions. I may put all the validation into a library in the monorepo and import it on the server and client, but what a lot of extra work that is.

**Comment by vadistic** [comment]
Hello, Firstly - imho I would implement this functionality on my graphql server, and not expect prisma to make validation. 

I can give you few quick pointers, but you may want to wait for more complete answer. I'm assuming, that you are using `graphql-yoga` or `apollo-server`.

1) >On any field, I'd like to be able to inject a function that would determine whether an update to that field could take place.

You can use `graphql-shield` or implement your own `graphql-middleware`. Middlewarea are the way to wrap your resolvers with function and determine whether an update to that field can take place. You could specify rules to validate `args` for mutations or implement this as field-level permissions.
https://github.com/maticzav/graphql-shield
https://github.com/prisma/graphql-middleware

2) >It seems to me that the schema should be the single source of truth.

If you prefer to annotate schema - you could write your own directives - similar to how you would implement authorization directives that will determine if value is valid and update can take place.
https://www.prisma.io/blog/graphql-directive-permissions-authorization-made-easy-54c076b5368e/

3) >I want to be able to be very specific with my types, way beyond simply Int or String.

You can also implement your custom scalar types with regex validation and use them in your server-side SDL schema. Here's some example: https://github.com/prisma/graphql-yoga/issues/229

I hope it helps you some :smile:
