### ISSUE TITLE
Unify active & passive connectors

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma1#3022]
The active and passive database connectors should be unified. This means the `migrations` property will be removed from `PRISMA_CONFIG` and no matter if you're using a new or an existing database, you will be able to perform migrations either manually or through Prisma.

**Comment by schickling** [comment]
Related: https://github.com/prisma/prisma/issues/2890

**Comment by mavilein** [comment]
I have just published a [spec](https://github.com/prisma/prisma/issues/3408) that touches on this topic. We would love to hear your feedback on this one.
