### ISSUE TITLE
Where are the samples, codes and documentation that supports mongodb? Or this is just the typical false marketing click-bait thing?

### ISSUE THREAD

**Issue by iamrommel** [prisma/prisma1#3052]
![image](https://user-images.githubusercontent.com/177265/45274272-43a3fb80-b4e9-11e8-8ce6-296e17134cae.png)

I highly suggest that remove that checkbox on mongodb if is really not there, it is really misleading!

Or if it really exists, please update the docs, samples and code as i cannot find it efficiently

**Comment by divyenduz** [comment]
Hey! thanks for reaching out. The mongodb connector is available in an early preview now - https://github.com/prisma/Mongo-Connector-Preview

Feedback super appreciated. Thanks!

**Comment by marktani** [comment]
Thanks for your feedback @iamrommel! Feel free to hit me up in Slack (@nilan) if you're interested to use the MongoDB connector today.
