### ISSUE TITLE
Can I change 'createdAt' field and 'updatedAt' field's timezone, other than UTC?

### ISSUE THREAD

**Issue by nob** [prisma/prisma1#3075]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I visually confirm data 'createdAt' or 'updatedAt' field directly in our MySQL database (I think that's not uncommon for developers and operators),  I just want to see them in our local time, not in UTC time.

I may able to convert them to our local time when our API returns them to API clients, but not when our mutation API creates/updates them in our database via Prisma API since 'createdAt' and 'updatedAt' fields are readonly to us.

**Describe the solution you'd like**
Preferably, let us to set the timezone using prisma.yml file.

**Comment by vjsingh** [comment]
+1!

**Comment by cr101** [comment]
Has anyone figured out how to change the UTC time to local time? I tried adding TZ environment variable to the docker-compose file but it didn't make any difference.

**Comment by LyhengTep** [comment]
+1
