### ISSUE TITLE
Suggestions for default timeout on SubscriptionServer

### ISSUE THREAD

**Issue by mistic** [prisma/prisma1#309]
Hi guys (and also @Urigo @DxCx @dotansimha),

I've doing updates to `subscriptions-transport-ws` and I realize that 30000ms for the timeout is too much time in order to get a production ready reconnect transaction. What do u think guys in proceed with this two changes also on graphcool:

- change default timeout to 10000ms (used to send keep_alive messages but also to set the max connect timeout before retry to connect or fail) which is the timeout also used for example by slack
- In order to improve a faster connect/reconnect/disconnect flow what do u think of proceed with a change that I've already made in our server's implementation: right after sending the `connection_ack` also sending the first `ka` message if the server has the config to use keep alive mechanism.

**Comment by sorenbs** [comment]
Hi @mistic I'm aware that you have been following this in Apollo issues including https://github.com/apollographql/subscriptions-transport-ws/issues/167

The current behaviour of the Graphcool subscriptions service is that we send a `connection_ack` message immediately after receiving `connection_init` from the client.

We then proceed to send a `ka` message every 10 seconds.

Here is a sample trace:

![image](https://user-images.githubusercontent.com/281337/28118507-98d4ec08-6711-11e7-84f8-171c9ce0df04.png)

From the Graphcool side we have two intervals:

 - Every 10 seconds we send a `ka` message
 - If we don't receive any incoming messages for _a very long time_ we drop the connection.

On the client side you need to decide how much delay you will tolerate in the `ka` messages before attempting to reconnect. Our current recommendation is 30 seconds, but in most cases you can reduce this to 15 seconds and maybe even 12 seconds if you can tolerate occasional superfluous reconnects.


Please help me understand 

 - exactly what you want to change 
 - how these changes will improve the user experience

Thanks! :-)

**Comment by mistic** [comment]
Hey @sorenbs thank you for your answer :)

After reading everything u wrote I realize that you already sent a `ka` message in `10000ms` intervals (before your answer I have the idea in my mind that u are using `30000ms` according your answer here https://github.com/apollographql/subscriptions-transport-ws/issues/167). However even with all u have explained there are one thing missing that you can upgrade in your server implementation in order to improve the user experience. Your correct connect/reconnect messages flow is:

`--> connection_init` - 0s
`<-- connection_ack` - 0s
`<-- ka` .                     - 10s

Instead you can implement this flow:

`--> connection_init` - 0s
`<-- connection_ack` - 0s
`<-- ka` .                     - 0s
`<-- ka` .                     - 10s

Doing that will allow  to immediately activate the timeout control in the client side. With the current implementation the timeout control will fail if the  connection goes down before we have received the first `ka` message and we the user will have to wait for your connection close that will happens later. I have implemented this logic in the `SubscriptionsServer` shipped with `subscriptions-transport-ws` and the final results, with a `10s timeout` are very good in order to reflect in the UI the moment when we loose the connection.

**Comment by sorenbs** [comment]
Thank you @mistic!

We will implement this change in the Graphcool subscription service and update this issue when rolled out.

These considerations should really be reflected in the Apollo ws specification as many backends will be implementing this. Would you be the right person to write this up?

**Comment by mistic** [comment]
@sorenbs I just opened a pull request apollographql/subscriptions-transport-ws#279 to updated the protocol documentation as you have requested :)

**Comment by minghiu** [comment]
@sorenbs You mentioned 

> Every 10 seconds we send a ka message

but it is not true if subscription event is fired. Event will delay ka message. And, if there is a stream of event coming through. you won't see any ka message.
![screen shot 2017-10-21 at 11 17 59 pm](https://user-images.githubusercontent.com/32978828/31853079-a1861586-b6b5-11e7-9f21-25b09f9826bd.png)


This behaviour will confuse `apollographql/subscriptions-transport-ws` SubscriptionClient. It will make SubscriptionClient keep on reconnecting at a interval. See the below discussion about this issue:
https://www.graph.cool/forum/t/invoking-a-subscription-event-frequently-in-a-short-amount-of-time/1298/8?u=mxming

**Comment by kbrandwijk** [comment]
Well, to be honest, that seems to be an error on the side of subscription-transport-ws. As a ka message only makes sense to keep the connection alive _if no other messages come in_. Sending ka messages when there's already a stream of event messages being sent, makes no sense to me whatsoever.

**Comment by minghiu** [comment]
@kbrandwijk I agree with you. However, what does the graph ql subscription spec says about the ka ? the bottle line is `graphcool` and `apollographql/subscriptions-transport-ws` need to be one the same page.

**Comment by kbrandwijk** [comment]
@minghiu Nothing, because it has to do with the websockets protocol, not with GraphQL.
