### ISSUE TITLE
Improve code comments for auto-generated Prisma client files

### ISSUE THREAD

**Issue by schickling** [prisma/prisma1#3110]
Every generated Prisma client file should contain the following code comments:

### JS-based (JS, TS, Flow, Reason)

```js
// Code generated by Prisma (prisma@1.17.0-beta.10, prisma-client-lib@0.2.58). DO NOT EDIT.
// Please don't change this file manually but run `prisma generate` to update it.
// For more information, please read the docs: https://www.prisma.io/docs/prisma-client/
```

In the case of Flow, this code comment should be after the required `@flow` comment.

### Go

```go
// Code generated by Prisma (prisma@1.17.0-beta.10). DO NOT EDIT.
// Please don't change this file manually but run `prisma generate` to update it.
// For more information, please read the docs: https://www.prisma.io/docs/prisma-client/
```

## File-specific comments

Typically a generated Prisma client is split up in various files. Every generated file should also contain some helpful comments about its purpose/function.

**Comment by pantharshit00** [comment]
Added feature label to avoid stalebot
