### ISSUE TITLE
ReasonML Support for Prisma Client

### ISSUE THREAD

**Issue by kgoggin** [prisma/prisma1#3119]
# Feature Request: [ReasonML](https://reasonml.github.io/) for Prisma Client

Let's make ReasonML support for Prisma Client happen! This feature request is for an option to specify `reason` as an option when running the client generator, which would in turn generate Prisma client code specific to your schema definition, written as .re ReasonML files. These Reason modules could then be compiled to JS files which would interop with the existing Prisma JS code. 

I've been working with Reason full-time for about nine months now so I'm fairly familiar with the ecosystem and language conventions, and I'll put some thoughts below about what we'd need to consider to build a good API for this. That said, I'm definitely still learning more every day about Reason and the larger OCaml ecosystem, so welcome others' thoughts and opinions on everything here!

# API Considerations

## Typing Query/Mutation Responses

The response from any GQL query/mutation is difficult to type in Reason due to its dynamic nature. Any given field on the response type may or may not be included in the response depending on whether or not it was specified in the query. Prisma's client defaults to only querying the scalar fields, but also allows for querying relations, as well as specifying a GQL fragment. I see a couple of ways to handle this:

### Option 1: Avoid typing query responses until runtime, make each response its own unique type depending on what was fetched.

This is the approach currently favored by libraries like [reason-apollo](https://github.com/apollographql/reason-apollo), which relies heavily on [graphql_ppx](https://github.com/mhallin/graphql_ppx) to determine the type of the query response at build-time based on the actual fields queried. 

*Pros*
 * The returned types are easier to work with

*Cons*
 * You can't reuse the types across different queries
 * More configuration needed from the user (setting up graphql_ppx) vs. having the codegen do it for you.
 * Dependency on another library

### Option 2: Define response types allowing for the fact that each field may/may not be included

This approach would have the codegen tool define response types corresponding to each query/mutation, but which differed slightly from the GraphQL types themselves in that each field would need to be an `option` depending on whether or not the field was actually fetched in the response.

For instance, the type defined for a user response might look like this:

```
# GraphQL type definition
type User {
  id: ID!
  name: String!
  nickname: String
}
```

```re
type userResponse {
  /* id may or may not have been requested in the query */
  id: option(string),
  /* same with name... */
  name: option(string),
  /* nickname is nullable, so not only do we need to define if it was requested, we also need
  to check if it exists! */
  nickname: option(option(string))
}
```

*Pros*
 * Can reuse the type definitions for all similar queries/mutations
 * Type definitions are generated by the tool - no extra work for the user to use them

*Cons*
 * Result type is more difficult to work with, as accessing values requires "unwrapping" the `option` around each field. Nullable fields require a double unwrap.

### Option 3: A hybrid approach

We could also theoretically break the use case for querying with a fragment off into its own specific function call (`userWithFragment` or something) and use the build-time typing there, but then handle the default case where all scalar fields are fetched with a generated type that assumes all the scalar fields are present.

*Pros*
 * Easy to use type when you need just the scalars, while still allowing for a more complicated query

*Cons*
 * Larger API footprint + divergence from the JS API
 * More complex code to implement
 * Still requires usage of external tooling to work

## Querying Relations

Prisma boasts about it's [Fluid API for querying the relations on an object](https://www.prisma.io/docs/prisma-client/api-reference/reading-data-JAVASCRIPT-rsc2/#relations). I'd love to make sure doing the same thing in Reason is just as straightforward. 

## Typing arguments

Prisma's convention for arguments like `where` and `data` is to pass them as objects to the query/mutation function. The analogous type for Reason would be a record, but again we run into issues with optional fields. We ought to lean on Bucklescript's [object creation tooling](https://bucklescript.github.io/docs/en/object#creationhttps://bucklescript.github.io/docs/en/object#creation) that was recently released to help with this. For example, a JS query that looked like this:

```js
prisma.user({ email: "bob@prisma.io" })
```

would look something like this in Reason 

```re
prisma.user(userWhereInput(~email="bob@prisma.io, ()), ());
```

## Working with Async

Async support in Reason is still evolving. Most code these days leans heavily on [Js.Promise](https://reasonml.github.io/docs/en/promise) which works fine but is not nearly as nice to work with as async/await in JS. I'm aware of a couple of projects to get a better API working. One is a separate library called [Respromise](https://aantron.github.io/repromise/). I'm using this in my own project and really like it, but I'd be hesitant to make Prisma's code dependent on it. I've also seen talk about adding async/await-like syntax into BuckleScript itself in the last few weeks, so we might want to check with some of the folks heavily involved with that project to see what they'd suggest.

**Comment by kgoggin** [comment]
Something else that could be worth looking into [Dre](https://rrdelaney.github.io/reason-dre/), which let you define interfaces similar to Flow that get compiled into Reason code. I'm not that familiar with Flow or this project, but I wonder if it could potentially allow for reuse of a lot of the existing code that already allow for Flow Prisma client?

**Comment by thislogancall** [comment]
Hey @samuela  @kgoggin , I see that there was some work (at least thoughts) started on this. Checking to see if there's been any kind of progress or ideas for next steps?

**Comment by kgoggin** [comment]
@thislogancall not on my end. If I were going to work on this today I'd probably be looking to write something to support [Photon](https://github.com/prisma/photonjs) vs. the original prisma client, as it seems like that's the direction they're headed in.

**Comment by thislogancall** [comment]
Thank you. That makes sense. 

For anyone who finds this and is looking to use Prisma to handle all their backend needs but want ReasonReact on the frontend with apollo client and typesafe graphql query generation - https://github.com/SeaMonster-Studios/prisma-graphql-reason-react-apollo-starter

No need to use the repo, but just a good example of using the Prisma and ReasonML together. The graphql_ppx is amazing tech and generates a typesafe schema that reason-apollo-hooks will use to make queries typesafe.
