### ISSUE TITLE
Prisma client - chaining API after array

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma1#3126]
**Is your feature request related to a problem? Please describe.**
Prisma client does not emit the chaining API when we run into an array. The reason for that is we can have multiple solutions and we want the community to choose the API. 
 
**Describe the solution you'd like**
Currently, the client just stops when the chaining API reaches an array. 

In the new API, `client.users().friends()` can return an array of friends or an array of users with friends.

Similarly, `client.users().book()` can return an array of books or an array of users with book. 

We can add to this API in an additive fashion. 

**Describe alternatives you've considered**
Current alternative is to use the direct GraphQL, SQL feature of client.

**Comment by kratam** [comment]
What if we pass an argument which controls which should be the "root" type?
E.g. `client.users().book()` returns an array of books and `client.users().friends({root: true}).book()` returns an array of friends with book.

**Comment by HyveMynd** [comment]
Im a fan of the [Objection.js](http://vincit.github.io/objection.js/) style of [eager loading](http://vincit.github.io/objection.js/#eager-loading). That framework uses a simple  relation expression string to describe how to eagerly load relationships and which ones should/should not be loaded.

For example: 
```
// Returns an array of users with the friends (user model) array populated
client.users().eager('friends')

// Returns an array of users with the books array populated 
client.users().eager('books') 

// Each person has the `.books` property populated with Books objects. 
// The `.friends` property contains the User's friends. 
// Each friend also has the `books` and `friends` relations eagerly fetched.
client.users().eager('[books, friends.[books, friends]')
```

I believe its simple yet powerful enough to easily define very complex relationships with ease.
