### ISSUE TITLE
The example in documentation not working

### ISSUE THREAD

**Issue by condef5** [prisma/prisma1#3132]
**Describe the content you'd like to see**
The method createDraft in the schema of [this tutorial](https://www.prisma.io/docs/get-started/03-build-graphql-servers-with-prisma-e001/) not work.

The mutation not working:
![error](https://i.imgur.com/PussjlB.png)

This is my logs: 
![logs](https://i.imgur.com/Aoys1IF.png)

**Additional context**
I followed all the steps of the documentation examples.

**Comment by jamesmbowler** [comment]
Looks like the docs need to be updated.
```
title:"some title",
userId: "25254"
```

Should be 
```
data:{
title:"some title",
userId: "25254"
}
```

**Comment by condef5** [comment]
This solves the problem:

```js
// mutation
createDraft(root, args, context) {
      return context.prisma.createPost(
        {
          title: args.title,
          author: {
            connect: { id: args.userId }
          }
        },

      )
    },
```
