### ISSUE TITLE
Make Prisma Client available in the Browser

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma1#3142]
As @timoweave already rightfully asked on our recent [Blogpost about the new Client](https://www.prisma.io/blog/prisma-client-beta-ahph4o1umail/), it can be a valid use-case to use the Prisma Client directly from the Browser.
Steps needed to make this happen:
1. replace node-fetch with isomorphic-fetch
2. Only load `ws` when in a Node.JS context

**Comment by PsidomPC** [comment]
I want to add that this could be really a cool feature to have. Think about how firestore database works in the browser. And prisma could be a layer that makes a general database available in the browser. I am not sure what security issue this may imply but it would be amazing if this can happen.

**Comment by gregwebs** [comment]
The use case I had for this was having TypeScript types for sending queries from the browser. For some applications, giving read access directly to the client is acceptable (but not necessarily write access).

Another good refactoring of the TypeScript would be to separate out query sending from graphql query string generation. That is, there are other clients that can send graphql queries, and they just need a graphql query string.

Note that a browser client could already send graphql queries to the prisma server, its just that they need to be typed out as strings. However, it is possible to add safety on top of these graphql string with some codegen tools (apollo and graphql-code-generator), but the workflow is quite different.

**Comment by ecwyne** [comment]
https://www.npmjs.com/package/isomorphic-ws may be an option as well

**Comment by Nishchit14** [comment]
@timsuchanek
Can you say about any future for the browser support?  Can we wait for it or start with server-side now?
