### ISSUE TITLE
Expose an object / map of the type definitions

### ISSUE THREAD

**Issue by jgoux** [prisma/prisma1#3193]
Hello,

**Is your feature request related to a problem? Please describe.**
Today, we can import Prisma's generated types using `graphql-import`. My issue with it is that it hides the dependencies I have over Prisma's types because of the comment syntax.

My typical model definition looks like this : 
```js
const { forwardTo } = require('prisma-binding')

const typeDefs = /* GraphQL */ `
  # Too magic, these dependencies are burried :D
  # import Query.site from "${__dirname}/../generated/prisma.graphql"
  # import Query.sites from "${__dirname}/../generated/prisma.graphql"
  # import Mutation.createSite from "${__dirname}/../generated/prisma.graphql"

  # Define my own Query and Mutation based on above imported types...
`

const resolvers = {
  Query: {
    site: forwardTo('prisma'),
    sites: forwardTo('prisma')
  },
  Mutation: {
    createSite(_, args, { prisma}, info) {
      // custom business logic here...
      return prisma.mutation.createSite(args, info)
    }
  }
}

module.exports = {
  typeDefs,
  resolvers
}
```

**Describe the solution you'd like**
Ideally, I'd like Prisma to exposes these type definitions in the form of a JS object.
By exposing the types in a JS object structured after Prisma's schema, it would open the door for "normal" JS import + composition, making the dependency over them explicit!

Also, I'm not a typescript expert, but I assume that if you control this object generation, you could also generate corresponding TS types for autocompletion? Double bonus? 😄

Example : 
```js
const { forwardTo } = require('prisma-binding')
const gql = require('graphql-tag')
const{ Query, Mutation } = require('./generated/typeDefs')

const typeDefs = gql `
  ${Query.site}
  ${Query.sites}
  ${Mutation.createSite}
  # Define my own Query and Mutation based on above imported types...
`

const resolvers = {
  Query: {
    site: forwardTo('prisma'),
    sites: forwardTo('prisma')
  },
  Mutation: {
    createSite(_, args, { prisma }, info) {
      // custom business logic here...
      return prisma.mutation.createSite(args, info)
    }
  }
}

module.exports = {
  typeDefs,
  resolvers
}
```

**Comment by jasonkuhrt** [comment]
Anyone have opinions on how well tooling is for schema definitions in TS/JS files versus in their own `.graphql` files?
