### ISSUE TITLE
prisma generate schould respect .env file

### ISSUE THREAD

**Issue by Awem** [prisma/prisma1#3211]
`prisma generate -e .env` should interpolate the variables of that `.env` file in to the generated client.

Currently an entry in `prisma.yml` like:
```
endpoint: ${env:PRISMA_ENDPOINT}
```
will output
```
exports.Prisma = prisma_lib_1.makePrismaClientClass({
  typeDefs,
  endpoint: `${process.env["PRISMA_ENDPOINT"]}`
});
```

This is fine as a default behavior. However, specifying an `.env` file should trigger interpolation.

**Comment by schickling** [comment]
Hi @Awem! Thanks a lot for this feature suggestion. I'm not 100% sure whether this is a good idea, so I'd love to open up a discussion on this topic before making a decision. I'm especially concerned that this might make it more likely to leak credentials in repositories.

**Comment by Awem** [comment]
You are absolutely right about the risk of leaking credentials to repositories. I am mainly thinking about using this feature for the endpoint configuration. Not for the secret.
What I have in mind is a setup with different stages configured via endpoints (e.g. dev, test, prod). On your local machine you'd have an `.env` file containing your secret and on production a different `.env` file. However, the endpoint wouldn't be defined via the `.env` file because on your local machine it would need to be changed when running tests.
Thus you configure the endpoints three times:

- in `dev.env`, `test.env` and `prod.env` used via `-e` option on `prisma deploy`
- in your `.graphqlconfig.yml`
- in the environments dev, test and prod individually

With an `-e` option for `prisma generate` we could at least reuse `dev.env`, `test.env` etc. and the CLI would be more consitent with `prisma deploy`.

However, I would consider another option to be the best approach: use `.graphqlconfig.yml` as single source of truth. For this to be possible we need another option for `prisma deploy` that reads values from a specific project config of `.graphqlconfig.yml`.

For now, I don't generate the client via `prisma generate` but only the graphql-schema. I then use `prisma-client-lib` directly:

```
import { getGraphQLConfig } from 'graphql-config'
import { makePrismaClientClass } from 'prisma-client-lib'

export const bindPrisma = config => {
  const graphQLConfig = getGraphQLConfig()
  const projectConfig = graphQLConfig.getProjectConfig(config)
  const Prisma = makePrismaClientClass({
    typeDefs: projectConfig.getSchemaSDL(),
    endpoint: projectConfig.endpointsExtension.getEndpoint('default').url
  })
  return new Prisma()
}
```

What do you thing of this?

**Comment by iilei** [comment]
> You are absolutely right about the risk of leaking credentials to repositories. I am mainly thinking about using this feature for the endpoint configuration. Not for the secret.

I wouldn't recommend treating variables inconsistently. Just add [dortenv-load](https://github.com/formatlos/dotenv-load) to your npm command and you are covered.

**Comment by Awem** [comment]
@iilei sure. Also [env-cmd](https://github.com/toddbluhm/env-cmd) will do the trick. I am trying to avoid multiple `.env` files though.
As I said above, I now only use `generate` for the schema. I think, generating the client produces unnecessary boilerplate code that duplicates the schema definitions. I don't want to check this in. Writing the client by yourself with `prisma-client-lib ` and `graphql-config` is much more straight forward for advanced use cases.
@schickling I wouldn't mind closing this, because I don't need the feature any longer for the given reasons.

**Comment by gustawdaniel** [comment]
My workaround: 
+ in Makefile that build project override result of prisma generation replacing address by variable. 

```
        prisma generate
	perl -p -i -e 's/^  endpoint: .*/  endpoint: process.env["PRISMA_ENDPOINT"],/' ../src/generated/prisma-client/index.js
	sed -i '1iinitialSetupCheck();' ../src/generated/prisma-client/index.js
	sed -i '1iconst {initialSetupCheck} = require("./../../../src/services/initialSetupCheck");' ../src/generated/prisma-client/index.js
```

where file`initialSetupCheck` allow to load configuration from `.env` to `process`. 

---

I am aware that this is dirty hack and would like to see implementation of this feature. I added this solution because it can be useful for someone now.
