### ISSUE TITLE
Namespace fields like ID with "Eq" or a suffix to avoid collisions

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma1#3212]
**Is your feature request related to a problem? Please describe.**
Go client generates fields on generated structs based on datamodel fields. For example, 
for the datamodel field `id` on any type `` the generated struct can be like

```
type TodoWhereInput struct {
	ID                *string          `json:"id,omitempty"`
	IDNot             *string          `json:"id_not,omitempty"`
	IDIn              []string         `json:"id_in,omitempty"`
	IDNotIn           []string         `json:"id_not_in,omitempty"`
	IDLt              *string          `json:"id_lt,omitempty"`
}
```

There `Not`, `In` etc are generated to map Prisma API. This might lead to a collision if A user create two field `Id`  and `IdNot` in the datamodel. 

**Describe the solution you'd like**
We might want to suffix the generated fields with something like `IdEq` to avoid the naming collisions.

**Additional context**
Once this is implemented we add it here as well https://github.com/prisma/prisma/issues/3185

**Comment by gregwebs** [comment]
A way to solve this and reduce code generation from models would be something like:

``` go
// This could be imported as `_` to avoid the `prisma.` qualifier. Or import as `db`.
TodoWhereInput{ ID: prisma.eq("foo") }

type EQ struct { string }
func eq(s string) EQ {
  return EQ{s}
}
type StringQuery interface {
  Op() string
  GetString() string
}
func (e EQ) Op() { return "eq" }
func (e EQ) GetString() { return string(e) }
type TodoWhereInput struct {
	ID                StringQuery
}
```

**Comment by timsuchanek** [comment]
The proposal by @divyenduz is how the initial implementation was intended. This is the way to go for now. @gregwebs your proposal is very interesting and we want to take it into consideration once we work on a v2 of the Go Client.

**Comment by timsuchanek** [comment]
It turns out, that the solution @divyenduz proposed is just "delaying" the Problem.
It is also a fairly rare edge case, that we're talking about.
This problem can even be achieved with the GraphQL API itself:
```graphql
type User {
  id: ID!
  id_gt: String!
}
```
We wait with tackling this until more people have reported this.
