### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by sergeysova** [prisma/prisma1#3217]
What about to add support for rust language?

For example [juniper](https://github.com/graphql-rust/juniper)

**Comment by marktani** [comment]
Are you talking about Prisma Client?

**Comment by schickling** [comment]
If so, I've open a feature request here: https://github.com/prisma/prisma/issues/3220

**Comment by sergeysova** [comment]
I talk about Prisma server on rust

**Comment by alaarihan** [comment]
Is that mean rebuilding Prisma on Rust instead of Scala ?
