### ISSUE TITLE
Java support for Prisma client

### ISSUE THREAD

**Issue by schickling** [prisma/prisma1#3221]
We should add [Java](https://www.java.com) support for Prisma client. 🙌

**Comment by bishwenduk029** [comment]
@schickling , I have a Java background, in case this feature is still open, can you please guide me on how set out building the client, like if I could refer some specs or documentations...

**Comment by agolomoodysaada** [comment]
Which graphql libraries would you recommend to use while we wait for official prisma java client support?

**Comment by unknowedNp** [comment]
+1

**Comment by ajorlando** [comment]
Bump
