### ISSUE TITLE
PHP support for Prisma client

### ISSUE THREAD

**Issue by schickling** [prisma/prisma1#3225]
We should add [PHP](http://php.net/) support for Prisma client. 🙌

**Comment by lpj145** [comment]
so twelve month's passed and not have any update ?
:)

**Comment by szepeviktor** [comment]
@nikolasburk Could you share us your thoughts with us? Pros/cons?

**Comment by lpj145** [comment]
all things about php cannot help with realtime hype ? 

> @nikolasburk Could you share us your thoughts with us? Pros/cons?
