### ISSUE TITLE
Add `latest` Docker tag 

### ISSUE THREAD

**Issue by schickling** [prisma/prisma1#3244]
It's a best practice for most tools distributed via Docker to have a `latest` tag that points to the latest stable release. We should adopt the same best practice to allow `docker pull prismagraphql/prisma` without specifying a certain version.

This will avoid confusion like [this Slack conversation](https://prisma.slack.com/archives/CA491RJH0/p1538570166000100):
![image](https://user-images.githubusercontent.com/1567498/46411090-2bf01980-c71b-11e8-945f-d28e4ac0aaab.png)

**Comment by lookapanda** [comment]
Anything new here? How do I find out the latest version?

**Comment by zuohuadong** [comment]
+1
