### ISSUE TITLE
Improve the Prisma Helm Chart to ensure the best possible experience running Prisma on Kubernetes

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma1#3266]
A community member graciously provided a [Helm chart for Prisma](https://github.com/helm/charts/pull/6483). This is a good first step to making it easy to run Prisma on Kubernetes.

The current version of the Helm Chart does not support scaling to multiple instances. It is possible to run Prisma on Kubernetes in a way that supports horizontal scaling as evidenced by this example: https://github.com/prisma/prisma/issues/2850#issuecomment-427311958.

We should either help improving the existing Helm chart or provide an official way to run Prisma on Kubernetes.

**Comment by serendipity1004** [comment]
@sorenbs I do feel this is quite necessary and while providing docs it would be great if we could consider https://github.com/prisma/prisma/issues/3789#issuecomment-501113350 as well.
