### ISSUE TITLE
updateMany and deleteMany Mutations Do Not Fire Subscriptions

### ISSUE THREAD

**Issue by goulderb** [prisma/prisma1#3304]
**Describe the bug**
updateMany and deleteMany mutations do not fire subscriptions.

**To Reproduce**
1. Create a new project with prisma init
2. Paste the following into the datamodel.prisma file:
```graphql
type A {
  id: ID! @unique
  name: String!
  bs: [B!]! @relation(name: "AtoB", onDelete: CASCADE)
}

type B {
  id: ID! @unique
  name: String!
}
```
3. Deploy this schema via prisma deploy
4. Open the playground at localhost:4466
5. Create a subscription on type B:
```graphql
subscription {
  b {
    mutation
    node {
      id
      name
    }
    previousValues {
      id
      name
    }
    updatedFields
  }
}
```
6. In a separate tab, create a record of type A and use nested mutations to create some records of type B:
```graphql
mutation {
  createA(data: {
    name: "Test A",
    bs: {
      create: [
        {
          name: "Test B 1"
        },
        {
          name: "Test B 2"
        }
      ]
    }
  }) {
    id
  }
}
```
7. Observe that the subscription shows both B's being created
8. Issue an updateMany against type B:
```graphql
mutation {
  updateManyBs(data: { name: "Test B Update Many" }) {
    count
  }
}
```
9. Observe that the subscription is not fired for each of the updates that took place.
10. Issue a deleteMany against type B:
```graphql
mutation {
  deleteManyBs(where: { name_contains: "Test " }) {
    count
  }
}
```
11. Observe that the subscription is not fired for each of the deletes that took place.

**Expected behavior**
The subscription to type B should have been fired for each update and deletion that took place.

**Versions (please complete the following information):**
OS: Arch Linux
prisma CLI: prisma/1.18.0 (linux-x64) node-v10.11.0
Prisma Server: 1.18.0

**Comment by FluorescentHallucinogen** [comment]
Any progress?

**Comment by ashitikov** [comment]
+1

**Comment by gabrieltong** [comment]
+1

**Comment by ashitikov** [comment]
#3303

**Comment by RoMay** [comment]
+1
