### ISSUE TITLE
Blog RSS feed

### ISSUE THREAD

**Issue by fvieira** [prisma/prisma1#331]
It would be great if there was an RSS feed for blog entries.

**Comment by marktani** [comment]
Thanks, we're already working on a subscription for our blog 🙂

**Comment by fvieira** [comment]
Well, that was fast! :laughing:

**Comment by marktani** [comment]
The blog moved to https://medium.com/@graphcool/, so you can subscribe to new posts there 🙂

**Comment by fvieira** [comment]
Hi Nilan. 
The blog on Medium is no longer receiving updates, and the blog on https://www.prisma.io/blog has no support for RSS... Are you planning on adding support eventually?

**Comment by adamfeldman** [comment]
+1
