### ISSUE TITLE
Prisma Client swallows errors returned for initial subscription requests

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#3317]
**Describe the bug**
Prisma Client swallows errors returned for initial subscription requests.

**To Reproduce**

0. Setup a new project using `prisma deploy` and **generate Typescript client**
1. Deploy this `datamodel.graphql`:

```graphql
type User {
    id: ID! @unique
    name: String!
}
```

2. Run `prisma playground`:

```graphql
subscription {
  user(where: {where: {
    mutation_in: CREATED
  }}) {
    node {
      id
    }
  }
}
```

The Playground (the Prisma API) returns this error:

```
{
  "error": {
    "message": "Argument 'where' expected type 'UserSubscriptionWhereInput' but got: {where: {mutation_in: CREATED}}. Reason: 'where' Field 'where' is not defined in the input type 'UserSubscriptionWhereInput'. (line 2, column 15):\n  user(where: {where: {mutation_in: CREATED}}) {\n              ^\n (line 2, column 16):\n  user(where: {where: {mutation_in: CREATED}}) {\n               ^"
  }
}
```

**This is expected**.

3. Run `prisma generate` again
4. In a `graphql-yoga` server, define this subscription resolver:

```typescript
    resolvers: {
        Subscription: {
            newUser: {
                subscribe: (parent, args, ctx) => {
                    return ctx.db.$subscribe.user({ where: { mutation_in: 'CREATED' } }).node()
                }
            }
        },
```
5. Now, against your Typescript GraphQL server run the subscription `newUser`.
6. Observe that no error is returned.

**Expected behavior**
In step 5, Prisma Client should return the same error that Prisma API returns in step 2.

**Versions (please complete the following information):**
- `prisma` CLI: `prisma/1.19.0-beta.2 (darwin-x64) node-v10.8.0)`
 - Prisma Server: `1.18.x`

**Additional context**
You can find a reproduction repo here: https://github.com/prisma/prisma/issues/3299.

**Comment by schickling** [comment]
@timsuchanek @divyenduz can you confirm whether this is still an issue or was this fixed in a recent release?

**Comment by pantharshit00** [comment]
I can confirm that this still an issue and no error is returned and the subscription just returns null as data when a new mutation is made.

I also noticed that the typescript typing doesn't allow this if the user uses proper type annotation.

![screenshot 2018-12-01 at 7 29 25 pm](https://user-images.githubusercontent.com/22195362/49329026-723cea00-f59f-11e8-925b-9176cb41f63d.png)


I am adding a reproduction repo: https://github.com/pantharshit00/prisma-issue-3317

**Comment by pantharshit00** [comment]
I can still reproduce this with 1.30
