### ISSUE TITLE
Flutter support for Prisma golang

### ISSUE THREAD

**Issue by ghost** [prisma/prisma1#3393]
It would be great to be able to use Flutter for your GUI and golang prisma for your backend.
Flutter architecture works very well with real time data from GraphQL subscriptions.

Flutter ( https://flutter.io/) is able to run on mobiles and desktops.

Mobile versions: https://github.com/flutter/flutter

Desktop version: https://github.com/Drakirus/go-flutter-desktop-embedder

There is a Flutter graphql implementation also btw:
https://github.com/zino-app/graphql-flutter

---

Now what are the interesting opportunities ?

1. You can embed golang inside flutter as a Flutter plugin, and so it could call the DB directly, obviously going through a Reverse proxy to protect the DB.

2. You can use the current Golang Rest example, and just expose Rest to Flutter. Thats really missing the opportunities of subscriptions i feel.

3. You can use a new Golang GRPC wrapper for prisma, and talk over GRPC to Flutter.
https://github.com/grpc/grpc-dart
I have done GRPC between a Golang server and Flutter Client and it works nicely.
This has the advantage of speed and ease of data binding on both side.

Happy to answer any questions if i can...

**Comment by Tata1993** [comment]
Would really love to see this being implemented for prisma!

**Comment by Matthewjarredondo** [comment]
+1

**Comment by johanguse** [comment]
Yes!

**Comment by dennis-szymanski** [comment]
+1
