### ISSUE TITLE
[RFC] Datamodel v1.1

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma1#3408]
This spec acts as the central place for all discussions around data model syntax. It contains new syntax for existing features as well as missing features.

**timeline**: Currently we do not have a timeline yet for those features. First we want to settle on a spec together with the community. Then we will start to plan the actual implementation of those features.

**handling of breaking changes**: The spec contains some breaking changes. We are aware that this would be a huge burden for existing projects. Therefore we plan to offer an easy way to migrate existing projects to the new syntax, e.g. by rewriting the data model on version upgrade.

The goals for this spec are:

* It should advance our data model syntax in order to support more databases. Concretely it contains the syntax for supporting relational and document databases.
* It should precisely define valid and invalid syntax in order to facilitate comprehensive data model validations.
* It should propose syntax for features we have not been able to build yet. This will be the foundation to actually implement those features.
* It aims at unifying the behaviour of active and passive connectors (based on the `migrations` setting in the server config). This means that Prisma will provide defaults for many things but is still configurable through the use of directives. This will enable seamless switching between the active and passive modes.

## Parts
For better readability the spec has been split into multiple parts: 

- [**Field Behaviour** #3403](https://github.com/prisma/prisma/issues/3403)
- [**Database names and types** #3404](https://github.com/prisma/prisma/issues/3404)
- [**Indexes and Constraints** #3405](https://github.com/prisma/prisma/issues/3405)
- [**Relations** #3406](https://github.com/prisma/prisma/issues/3406)
- [**Polymorphic Relations** #3407](https://github.com/prisma/prisma/issues/3407)

#### Type Level

1. `@db`
1. `@linkTable`
1. `@embedded`
1. `@indexes`
1. `@discriminator`

#### Field Level

1. `@id`
1. `@createdAt`
1. `@updatedAt`
1. `@default`
1. `@db`
1. `@scalarList`
1. `@sequence`
1. `@relation`
1. `@unique`

#### Interface Level

1. `@inheritance`

## Glossary of terms used in the spec

* *Relation Link*: a relation link is the concrete instance where two nodes gets linked. In SQL this could be a row in a relation table or foreign key column in a table for a type. In Mongo these are fields that contain ids to other documents.

**Comment by divyenduz** [comment]
Will datamodel v2 allow for us to add custom scalars to Prisma datamodel? Like,

```
scalar IP

type MyType {
  ip: IP!
}
```

**Comment by nikolasburk** [comment]
*The datamodel v1.1 is ready to be tested* 🎉  You can find all instructions how to get started in [this](https://github.com/prisma/datamodel-v1.1-feedback) GitHub repo.

**Comment by abdullah-almesbahi** [comment]
@nikolasburk I have installed the latest beta 1.31.0-beta.1 just to test introspect 

I followed your instructions in [this](https://github.com/prisma/datamodel-v1.1-feedback)

After running this

```
prisma introspect --prototype -e .env
prisma deploy -e .env

```
I got the following errors

AmAdmin
    ✖ The value 0 is not a valid default for fields of type Boolean.

  AmAgreement
    ✖ The value 0 is not a valid default for fields of type Boolean.

  AmBillingPlan
    ✖ The value 0 is not a valid default for fields of type Boolean.
    ✖ The value 0 is not a valid default for fields of type Boolean.

  AmButton
    ✖ The value 0 is not a valid default for fields of type Boolean.
    ✖ The value 0 is not a valid default for fields of type Boolean.

  AmCouponBatch
    ✖ The value 0 is not a valid default for fields of type Boolean.
    ✖ The value 0 is not a valid default for fields of type Boolean.

  AmEmailTemplate
    ✖ The value 0 is not a valid default for fields of type Boolean.
    ✖ The value 0 is not a valid default for fields of type Boolean.
    ✖ The value 1 is not a valid default for fields of type Boolean.

  AmInvoice
    ✖ The value 0 is not a valid default for fields of type Boolean.

  AmInvoiceItem
    ✖ The value 0 is not a valid default for fields of type Boolean.
    ✖ The value 0 is not a valid default for fields of type Boolean.

  AmInvoiceLog
    ✖ The value 0 is not a valid default for fields of type Boolean.

  AmProduct
    ✖ The value 0 is not a valid default for fields of type Boolean.
    ✖ The value 0 is not a valid default for fields of type Boolean.
    ✖ The value 0 is not a valid default for fields of type Boolean.

  AmProductOption
    ✖ The value 0 is not a valid default for fields of type Boolean.

  AmProductUpgrade
    ✖ The value 0 is not a valid default for fields of type Boolean.

  AmResourceAccess
    ✖ The value 0 is not a valid default for fields of type Boolean.

  AmUser
    ✖ The value 0 is not a valid default for fields of type Boolean.
    ✖ The value 1 is not a valid default for fields of type Boolean.
    ✖ The value 0 is not a valid default for fields of type Boolean.
    ✖ The value 0 is not a valid default for fields of type Boolean.

  AmUserStatus
    ✖ The value 0 is not a valid default for fields of type Boolean.

  AmAccessCachefnEnum
    ✖ The enum type `AmAccessCachefnEnum` contains invalid enum values. The first character of each value must be an uppercase letter.

  AmAccessCachestatusEnum
    ✖ The enum type `AmAccessCachestatusEnum` contains invalid enum values. The first character of each value must be an uppercase letter.

  AmCountrystatusEnum
    ✖ The enum type `AmCountrystatusEnum` contains invalid enum values. The first character of each value must be an uppercase letter.

  AmCouponBatchdiscountTypeEnum
    ✖ The enum type `AmCouponBatchdiscountTypeEnum` contains invalid enum values. The first character of each value must be an uppercase letter.

  AmEmailTemplateformatEnum
    ✖ The enum type `AmEmailTemplateformatEnum` contains invalid enum values. The first character of each value must be an uppercase letter.

  AmResourceAccessfnEnum
    ✖ The enum type `AmResourceAccessfnEnum` contains invalid enum values. The first character of each value must be an uppercase letter.

  AmStatestatusEnum
    ✖ The enum type `AmStatestatusEnum` contains invalid enum values. The first character of each value must be an uppercase letter.
