### ISSUE TITLE
Only fire 'updated' subscriptions when a field is actually updated

### ISSUE THREAD

**Issue by kbrandwijk** [prisma/prisma1#341]
Currently, subscriptions for `UPDATE` always trigger on an update mutation, even if nothing actually changes. It would be nice to only fire subscriptions when something actually changes. So if I update a field with the same value, I wouldn't get a subscription trigger.

The `updatedAt` field is actually not updated when the field value doesn't actually change, so that check is already in place for the `updatedAt` field, but not used for subscriptions.

**Comment by danmkent** [comment]
I agree with this - I would only expect the subscription to trigger when the updatedAt value is changed
