### ISSUE TITLE
@unique on to-one relation

### ISSUE THREAD

**Issue by antimagnes** [prisma/prisma1#3414]
**Is your feature request related to a problem? Please describe.**
I have following schema
```graphql
type User {
  id: ID! @unique
  email: String! @unique
  username: String! @unique
  name: String!
}

\# Keep is separate so it is not available in the public graphql api as if kept in the User
type Password {
  id: ID! @unique
  user: User! @unique
  password: String!
}
```

When I wanted to select the password for a given user I was expecting to find in `PasswordWhereUniqueInput!` of the `password` query a `UserWhereInput!` field, but the only option is `id`.

**Describe the solution you'd like**
I would like to be able to query using the single result query by the relation also if it is marked `@unique`

**Describe alternatives you've considered**
I am using `passwords` now and expect an array with one element.

**Comment by hinsxd** [comment]
+1
I have a similar situation where a user can only comment once in a post. Perhaps you need a field called `userId: ID! @unique` because non-scalar cannot be used in relations.
I am looking forward to non-scalar relations tho.

**Comment by antimagnes** [comment]
> +1
> I have a similar situation where a user can only comment once in a post. Perhaps you need a field called `userId: ID! @unique` because non-scalar cannot be used in relations.
> I am looking forward to non-scalar relations tho.

@hinsxd  what do you mean by  '... non-scalar cannot be used in relations.'? From where I am standing it seems, that they can and I do. What am I missing?

From [Prisma docs](https://www.prisma.io/docs/data-model-and-migrations/data-model-knul/)
```type User {
  id: ID! @unique
  comments: [Comment!]! @relation(name: "CommentAuthor", onDelete: CASCADE)
  blog: Blog @relation(name: "BlogOwner", onDelete: CASCADE)
}

type Blog {
  id: ID! @unique
  comments: [Comment!]! @relation(name: "Comments", onDelete: CASCADE)
  owner: User! @relation(name: "BlogOwner", onDelete: SET_NULL)
}

type Comment {
  id: ID! @unique
  blog: Blog! @relation(name: "Comments", onDelete: SET_NULL)
  author: User @relation(name: "CommentAuthor", onDelete: SET_NULL)
}```

**Comment by antimagnes** [comment]
@hinsxd Why don't you simply select the comment for that user for that post? If it is already there then you know the user cannot comment.
