### ISSUE TITLE
Seed from mutliple .graphql files

### ISSUE THREAD

**Issue by lewebsimple** [prisma/prisma1#3422]
The prisma.yml.seed.import property can only accept one file.

I'd like to be able to modularize the seed import into multiple files by having the following in prisma.yml:
```
seed:
  import:
  - ./seed/a.graphql
  - ./seed/b.graphql
```
I tried using `# import` statement with `graphql-import` without success.

Are there any ways around this?

Thanks for maintaining such an amazing project!

**Comment by b33son** [comment]
bump!

**Comment by pdeak** [comment]
This would be a big help, it would allow us to separate static data from test data and put them into separate files.

**Comment by jameshood118** [comment]
Has there been any headway on this? We would love to split our seed files into the specific actions/apps they relate, instead of having one long file

**Comment by Markus357** [comment]
Definitely bump
