### ISSUE TITLE
Enforce version of Prisma CLI

### ISSUE THREAD

**Issue by mxstbr** [prisma/prisma1#3506]
**Is your feature request related to a problem? Please describe.**
I want to enforce consistent usage of a Prisma CLI version across my team.

**Describe the solution you'd like**
The `prisma.yml` file should have a `version` field that allows me to pin a specific version, and if the CLI detects that it has a different version it throws an error requesting that specific version.

**Describe alternatives you've considered**
N/A

**Additional context**
Flowtype does this and it's great, see https://flow.org/en/docs/config/version/

**Comment by samuela** [comment]
I just use prisma as a local devDependency and it works great. You just write `yarn prisma ...` instead of `prisma ...` but it keeps everything consistent across developer machines and CI/CD.

**Comment by mxstbr** [comment]
Yes, if people remember to write `yarn prisma` instead of `prisma` :wink: That's why I'd like to enforce a consistent version!

**Comment by samuela** [comment]
@mxstbr yeah, that's a problem I can't solve...

**Comment by mxstbr** [comment]
Not stale
