### ISSUE TITLE
Expose custom scalars

### ISSUE THREAD

**Issue by mxstbr** [prisma/prisma1#3512]
**Is your feature request related to a problem? Please describe.**
I want to expose the `createdAt` and `modifiedAt` fields from my GraphQL API. Unfortunately, the `DateTime` type by Prisma is a custom scalar, so I can't just add `createdAt: DateTime!` to my custom GraphQL API schema.

**Describe the solution you'd like**
I'd love to be able to `import { DateTimeScalar } from 'some-prisma-package'` and then add that custom scalar to my GraphQL API to be able to expose it to end-users.

**Describe alternatives you've considered**
- Using the `graphql-iso-date` package, but I'm not clear on whether that will clash with Prisma's built-in scalar

**Comment by mxstbr** [comment]
It seems that the `grapqhl-iso-date` package does work, so maybe it's just a matter of adding it to the documentation—that being said, as more custom scalars are added it would be nice if one didn't have to resort to third-party packages that might be slightly different, so I'll leave this open anyway!

**Comment by timsuchanek** [comment]
Thanks for raising the issues @mxstbr! As Prisma is returning a string for the DateTime, there is no need for a custom resolver.
It's sufficient to add
```graphql
scalar DateTime
```
to the application schema.
We have 2 custom scalar types for now:
`DateTime` and `Json`.
If you don't want to bother about them, you can also use `graphql-import`.
It's builtin with `graphql-yoga` and can be used like this:
https://github.com/prisma/graphql-prisma-typescript/blob/master/src/schema.graphql#L1
That then would automatically import the directive as defined here https://github.com/prisma/graphql-prisma-typescript/blob/master/src/generated/prisma.graphql#L1840

**Comment by mxstbr** [comment]
Oh I see, even better! Then it'd be great if this was documented somewhere :+1:

**Comment by mxstbr** [comment]
Not stale.
