### ISSUE TITLE
Cannot expose connections

### ISSUE THREAD

**Issue by mxstbr** [prisma/prisma1#3513]
**Describe the bug**
Apart from not being able to use inner connections (ref #1780), I can't seem to expose connections to my API users at all.

**To Reproduce**
1. Create an API with a many-many or one-many relationship, e.g. `User.posts`
2. Try to expose and query a connection for the field from your custom API
3. This fails with obscure error messages like `"postsConnection.edges cannot be null"`:

```JS
// api/queries/user/postsConnection.js

export default (user, args, { prisma }) => {
  // args is something like { first: 10, after: 'asdf-123' }
  return prisma.postsConnection({
    where: {
      user: {
        id: user.id
      }
    },
    ..args,
  })
}
```

**Expected behavior**
I should be able to expose connections to my users.

**Versions (please complete the following information):**
 - OS: MacOS Mojave
 - `prisma` CLI: 1.20.0

**Comment by timsuchanek** [comment]
Thanks for reporting @mxstbr !
We're aware that this a limitation with the current approach using the Prisma Client.

A workaround that you can use for now is using the `$fragment` syntax.
With that, you can provide a custom GraphQL fragment which can go arbitrarily deep with your query.

```js

export default (user, args, { prisma }) => {
  // args is something like { first: 10, after: 'asdf-123' }
  return prisma.postsConnection({
    where: {
      user: {
        id: user.id
      }
    },
    ..args,
  }).$fragment(`fragment F on PostConnection {
    pageInfo {
      startCursor
    }
    edges {
      node {
        id
        name
        email
      }
    }
  }`)
}
```

**Comment by mxstbr** [comment]
Not stale.

**Comment by pantharshit00** [comment]
This will get fixed in the new prisma client v2: https://github.com/prisma/rfcs/blob/new-ts-client-rfc/text/0000-new-ts-client.md#withpageinfo

See `withPageInfo()`
