### ISSUE TITLE
Optional field encryption

### ISSUE THREAD

**Issue by mxstbr** [prisma/prisma1#3519]
**Describe the feature you'd like**

It would be awesome if one could encrypt certain fields (or columns) at the db level automatically. For example:

```GraphQL
type User {
  id: ID! @unique
  email: String! @encrypt
}
```

All emails would now be encrypted with a globally configured key in the database, making it harder for a potential hacker to get the list of emails of our users.

Postgres has a db-level feature that allows this (https://www.postgresql.org/docs/8.1/encryption-options.html), but I don't know about other databases.

**Describe alternatives you've considered**
- One could handle this in the application layer, but that's tedious and error-prone. It'd be much nicer if Prisma handled this out of the box

**Comment by codeincontext** [comment]
Ping. We also want this (not for storing passwords in the database though!)

**Comment by johhansantana** [comment]
This would work great for handling PII and other compliance stuff.

**Comment by Fabiomad85** [comment]
i thik its useful
