### ISSUE TITLE
CLI performance

### ISSUE THREAD

**Issue by mxstbr** [prisma/prisma1#3547]
**Describe the bug**
The CLI is notably slow to do anything, taking > 1s to start logging the first output.

**To Reproduce**

Run a simple `--version` call and note how long it takes:

```
$ time prisma --version
...
0.85s user 0.13s system 2.064 total
```

In comparison:

```sh
$ time grep --version
...
0.00s user 0.00s system 0.008 total

# and a little bit more fairly
$ time npm --version
...
0.18s user 0.05s system 0.272 total
```

Grep is logs almost instantly, but even npm (which is also written in JS) is 10x faster. 

**Expected behavior**
The CLI logs the first output quickly

**Comment by schickling** [comment]
Thanks a lot for reporting this. We expect this to massively improve via #1480. 🙏

**Comment by mxstbr** [comment]
Are you sure that's the bottleneck when running commands? I can't imagine Node taking > 1s just to resolve the CLIs dependencies, there must be something else happening that's taking so long.

**Comment by timsuchanek** [comment]
@mxstbr we have the architecture (don't use it yet) for an fs-based plugin system. These plugins are scanned in the cli on bootup time. Right now I assume this is the biggest bottleneck.
