### ISSUE TITLE
Prisma requires an ID field every type

### ISSUE THREAD

**Issue by ejoebstl** [prisma/prisma1#3575]
Currently, Prisma requires an ID field on every type. 

However, ID fields might not exist on existing databases, which can break introspection. 

Examples are: 
* Embedded types in MongoDB, where an `_id` is not required
* Tables without ID or PrimaryKey in Postgres or MySql

**Comment by mrchirub** [comment]
Issue still exists on prisma:1.31

**Comment by pantharshit00** [comment]
Fixed with datamodel v1.1
