### ISSUE TITLE
Migration support for Int to Float conversion

### ISSUE THREAD

**Issue by terion-name** [prisma/prisma1#3600]
**Describe the bug**
Changing field type from int to float triggers error "You are changing the type of a required field and there are nodes for that type. Consider making the field optional, then set values for all nodes and then making it required." 

**To Reproduce**
Deploy a schema with required int field, then change it to float

**Expected behavior**
Type changes seamlessly, without loosing data and breaking required status

**Versions (please complete the following information):**
 - Prisma Server: `1.9.0`

**Comment by noobling** [comment]
Does anyone have any work around to this for now?

**Comment by antimagnes** [comment]
> Does anyone have any work around to this for now?

Nope, but facing the exact same issue :/. Would be really nice if this was working!
