### ISSUE TITLE
Cannot rename "named" relation

### ISSUE THREAD

**Issue by JensMadsen** [prisma/prisma1#3607]
**Describe the bug**
When renaming a named relation (using `@relation`directive) `prisma deploy` throws the error: 
```
Errors:

  Post
    ✖ You are creating a required relation, but there are already nodes that would violate that constraint.
```

**To Reproduce**
1. deploy the schema: 
```
type User {
  id: ID! @unique
  name: String!
  posts: [Post!]! @relation(name: "UserOnPost")
}

type Post {
  id: ID! @unique
  title: String!
  user: User! @relation(name: "UserOnPost")
}
```  
2. change datamodel: 
```
type User {
  id: ID! @unique
  name: String!
  posts: [Post!]! @relation(name: "PostUser")
}

type Post {
  id: ID! @unique
  title: String!
  user: User! @relation(name: "PostUser")
}
``` 
3. `prisma deploy` 
4. error thrown:
```
Errors:

  Post
    ✖ You are creating a required relation, but there are already nodes that would violate that constraint.
```

**Expected behavior**
relation is renamed

**Versions (please complete the following information):**
 - OS: ubuntu 18.04
 - prisma 1.18.1 and 1.20.6

 - `graphql-cli`, `prisma-binding`, etc. if applicable

**Additional context**

**Comment by schickling** [comment]
Thanks a lot for opening this issue. We should consider this as another requirement for the discussion here #1263.
