### ISSUE TITLE
Well-defined API errors

### ISSUE THREAD

**Issue by ejoebstl** [prisma/prisma1#361]
It would be great to have a schema for API errors, or at least some pre-defined codes that are easily machine-readable. 

Detecting which error happened can ease robust programming a lot. 

For example, I might want to explicitly handle accessing a node that does not exist, retry on a connection error, and fail hard on a syntax error in the query.

**Comment by kbrandwijk** [comment]
Have you seen this list of error codes?
https://www.graph.cool/docs/reference/simple-api/error-management-aecou7haj9/

**Comment by schickling** [comment]
Thanks a lot for bringing this up @ejoebstl. Typed errors is definitely something we'd love to support at some point in the future as soon as this becomes officially part of the GraphQL spec. Check the following issue to track the progress in the GraphQL spec: https://github.com/facebook/graphql/issues/135

Until then working with the [API error codes](https://www.graph.cool/docs/reference/simple-api/error-management-aecou7haj9/#api-errors) as @kbrandwijk pointed out is the way to go.

Any other suggestions are more than welcome!
