### ISSUE TITLE
Enable installation through `curl`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma1#3620]
Currently, it's possible to [install](https://github.com/prisma/prisma/issues/3619#issuecomment-442758506) Prisma using Homebrew, NPM and Yarn. It should be also be possible to install it using a `curl` command that downloads and installs the binary on a local machine.

**Comment by schickling** [comment]
I really like the way how Rust presents this option:

![image](https://user-images.githubusercontent.com/1567498/50055924-7fd4a100-0155-11e9-92a3-105fd91cc419.png)
