### ISSUE TITLE
Add support for using docker-secrets

### ISSUE THREAD

**Issue by seberik** [prisma/prisma1#3626]
**Is your feature request related to a problem? Please describe.**
I don't want to specify database password in docker-compose since I don't want the secrets to be visible in our repos / part of our codebase. 

**Describe the solution you'd like**
I would like the option to use docker-secrets instead of environment variables.

https://docs.docker.com/engine/swarm/secrets/

**Comment by pantharshit00** [comment]
I guess you are using docker compose not docker swarm, so docker secrets wont help in there.

But you can use an env file with docker compose.
https://docs.docker.com/compose/env-file/

**Comment by seberik** [comment]
Not sure what you mean, We are using docker-swarm. I have access to docker secrets but I don't think that there is a way to provide that secret to the prisma service through the docker-compose file?

**Comment by seberik** [comment]
Yes, I understand that it can be done if the secret is available as an environment variable somehow but I don't think that you can map a secret which is basically a file in /run/secrets to env-variable right? I'm thinking that it would be nice if prisma could read the secret from `/run/secrets/some-secret-name` where the `some-secret-name` is specified as an env-variable in the compose file.

**Comment by thehappycoder** [comment]
I need this too.

**Comment by soqt** [comment]
Agree on this. Docker compose reads file from `/run/secrets/SECRET_NAME`, It's good to have DB connectors to have the ability to read files rather than just environment variables.

**Comment by soqt** [comment]
Here is a good setup for Mongo docker compose using[file as secret](https://github.com/docker-library/mongo/blob/b1c209cdd9b890cd62e85a2c7055fb8f00c7d248/4.0/docker-entrypoint.sh#L34-L54)
