### ISSUE TITLE
Retry failed webhook deliveries

### ISSUE THREAD

**Issue by dpetrick** [prisma/prisma1#363]
Currently, if a webhook delivery in a server side subscription fails, the system is not attempting a redelivery.

The upside would be that transient errors (network, hitting a dying server, ...) would be handled gracefully. The downside is that delivering a webhook multiple times is something that might have unintentional side effects if the webhook fails but side effects were already triggered anyways before the remote blew up.

Personally, I'd consider the latter to be bad design on the webhook receiver side and would always assume the implementation to be idempotent or robust enough to handle these cases.

Thoughts?

**Comment by giautm** [comment]
I think webhook should have an options to try failured on http codes: `retryHttpCodes: [0, 500, 503, 504]`. And another options for connection timeout.
