### ISSUE TITLE
Prisma Client enum list not accepted as array

### ISSUE THREAD

**Issue by heymartinadams** [prisma/prisma1#3638]
**Describe the bug**
Unable to update an `enum` list in Prisma Client without manually changing it into a `set` object.

**To Reproduce**
For this datamodel:
```graphql
type Participant @model {
  User: User!
  dietaryRestrictions: [EnumDietaryRestriction!]!
}

enum EnumDietaryRestriction {
  Diabetic
  GlutenFree
  HighProtein
}
```

This doesn’t work (with `data.dietaryRestrictions = ['GlutenFree']`):
```javascript
  let data = { ...args }
  const updateUser = await ctx.prisma.updateUser({
    where: {
      id: User.id
    },
    data: {
      Participant: {
        update: {
          ...data
        }
      }
    }
  })
```

...but it works if you change `data.dietaryRestrictions = ['GlutenFree']` from an array into an object `dietaryRestrictions: { set: ['GlutenFree'] }`:
```javascript
  let data = { ...args }
  // Make enum list palatable to Prisma Client
  data = { ...data, dietaryRestrictions: { set: [...data.dietaryRestrictions] } }
  const updateUser = await ctx.prisma.updateUser({
    where: {
      id: User.id
    },
    data: {
      Participant: {
        update: {
          ...data
        }
      }
    }
  })
```

**Expected behavior**
I don’t think we should be needing to manually modify the incoming arguments specifically for `enum` lists.

**Versions (please complete the following information):**
 - OS: `OS X Mojave`
 - `prisma` CLI: `prisma/1.21.0 (darwin-x64) node-v11.3.0`
 - Prisma Server: `1.22-beta-1`
 - `prisma-client-lib`: `1.20.7`
- `graphql-yoga`: `1.16.2`

**Comment by pantharshit00** [comment]
Hi @heymartinadams,
I was able to reproduce this have added a reproduction [here](https://github.com/pantharshit00/issue-3638). Even the typescript typings don't allow this. I don't exactly know yet why this is done in this way but maybe we should use `set` as default behaviour when nothing is provided.

That being said I have noticed this exact same behaviour in other places as well and in my personal findings, this is not specific to enums. Another day I was getting this kind of behaviour when I was inserting data for [this](https://www.prisma.io/forum/t/delete-a-record-with-array-column-fails-with-postgres/5281) reproduction.
