### ISSUE TITLE
Unable to view schema on deployed Heroku endpoint

### ISSUE THREAD

**Issue by AmoDinho** [prisma/prisma1#3649]
**Describe the bug**
I've deployed my server to Heroku and when visiting the [endpoint ](https://fan-boost-new-eb982e7d8c.herokuapp.com )the schema does not load. I typed `prisma playground` into the playground and received the following error: 

```
{
  "errors": [
    {
      "message": "Project not found: 'default$default'",
      "code": 3016,
      "requestId": "local:cjpb3ru3f000b0866zwbasaom"
    }
  ]
}
```

I am able to access the Prisma service endpoint and perform queries etc. Also there are no errors popping up in the logs on Heroku.

**To Reproduce**
1. Clone this [repo](https://github.com/AmoDinho/formulaone-graphql)
2. Create a Prisma server and service
3. Deploy to Heroku.
4. Visit the Heroku endpoint to see if the error is present.

**Expected behavior**
I expect my schema to be loaded and be able to execute operations on the API.

**Screenshots**
![screenshot-fan-boost-new-eb982e7d8c herokuapp com-2018 12 05-13-53-40](https://user-images.githubusercontent.com/19347140/49511985-4ff3e680-f895-11e8-8f44-5ea0faa99171.png)

**Versions (please complete the following information):**
 - OS:Windows 10
 - `prisma` CLI: ` "prisma": "1.21.1",`
 - `prisma-binding: "2.1.5"`

**Additional context**
None

**Comment by pantharshit00** [comment]
Hi, 

I am able to access your deployment at https://fan-boost-new-eb982e7d8c.herokuapp.com/boost/dev

This is because you have deploying it to the boost service and the dev stage as provided in the endpoint field of your prisma.yml file https://github.com/AmoDinho/formulaone-graphql/blob/e56886d0683cb127b28ecbae0259ca90c8351794/database/prisma.yml#L31

Since without those two routes at the end prisma defaults to the `default` service and `default` stage which are non existent in your case. So always remember to put the correct service and stage your have deployed your app.

**Comment by AmoDinho** [comment]
Hi @pantharshit00 
> I am able to access the Prisma service endpoint and perform queries etc.

Not sure if this did not come across clearly enough, but this is what I meant by I am able to access my deployment on Prisma database layer of my app. However, I am unable to access the application layer of of my app.  

Below is a screenshot of the application layer from an endpoint that would not allow me to deploy my Prisma service: 

![screenshot-fan-boost-two-48a9866683 herokuapp com-2018 12 05-17-35-21](https://user-images.githubusercontent.com/19347140/49524471-79703a80-f8b4-11e8-9642-497fcea6e51f.png)

In that case I can see my schema which I cannot at `https://fan-boost-new-eb982e7d8c.herokuapp.com/`

**Comment by pantharshit00** [comment]
You need to separately deploy your graphql server to a different heroku instance and use the endpoint of your prisma instance in your connection url. They are separate entities. You need a separate deployment for the graphql-yoga server.
