### ISSUE TITLE
Field 'id' is not defined in the input type when using in where

### ISSUE THREAD

**Issue by b33son** [prisma/prisma1#3670]
I'm trying to write a resolver that returns a list of organizations for a user id, but only organizations of which the current user is also a member. The Org entity has a list of members I'm trying to filter on. 

Maybe I'm going about it the wrong way, but this is how I'm trying to do it. Could also be a bug related to UUIDs?

```ts
orgs: (parent, args, ctx) => {
    // current user
    const userId = getUserId(ctx);

    console.log(`userId   `, userId);   
    console.log(`parent.id`, parent.id);
    return ctx.prisma
      .user({ id: parent.id })    // the requested user
      .orgs({ where: { orgMembers_some: { id: userId } } });
  }
```

```graphql
type User { 
  id: UUID!
  name: String
  orgs: [Org!]!  
}

type Org { 
  id: UUID!
  name: String 
  orgMembers: [User!]! 
}
```

I'm getting this: 
```
"message": "Variable '$where' expected value of type 'OrgWhereInput' but got: {\"orgMembers_every\":{\"id\":\"a3f7bcd1-3ae7-4706-913a-9cfe5ed7e7b6\"}}. Reason: 'orgMembers_every.id' Field 'id' is not defined in the input type 'UserWhereInput'. (line 1, column 8):\nquery ($where: OrgWhereInput, $where_1: UserWhereUniqueInput!) {\n       ^",
```

I can successfully use `{ where: { orgMembers_some: { name: "test" } } }` and not get an error. 

Do I need to explicitly cast from string (userId) to UUID? Or am I missing something else? 
 

**:**
 - OSX
    "graphql-shield": "^4.1.0",
    "graphql-yoga": "^1.16.7",
    "jsonwebtoken": "^8.4.0",
    "prisma-client-lib": "^1.22.0"
    "graphqlgen": "0.4.0",

**Comment by pantharshit00** [comment]
Hi, 

The id field you are using should be in the format of `id: ID! @unique` or `id: UUID! @unique`. As I can see in your datamodel you haven't added the `@unique` directive so that's prisma is generating wrong where input and causing this error.

Prisma do not allow to deploy this model in the latest version and it errors out like so:
![image](https://user-images.githubusercontent.com/22195362/49645416-d77e5880-fa41-11e8-9d15-ccd6fce0e367.png)

Maybe you are using an old version of cli. Can you provide me with the prisma version you are using?

Amending you datamodel to this will solve your problem:
```graphql
type User {
  id: UUID! @unique
  name: String
  orgs: [Org!]!
}

type Org {
  id: UUID! @unique
  name: String
  orgMembers: [User!]!
}

```

**Comment by b33son** [comment]
Thanks for taking a look. I'm using 
    "prisma-client-lib": "^1.22.0"

So, it turns out I copied from my schema.graphql. I actually do have UUID! @unique in my datamodel.prisma: 
```

type User @model { 
  id: UUID! @unique
  name: String 
  orgs: [Org!]! @relation(name: "UserOrgMember") 
}

type Org @model { 
  id: UUID! @unique
  name: String 
  orgMembers: [User!]! @relation(name: "UserOrgMember")  
}
```

The interface UserWhereInput has the ID field variations so it's passing type safe checks at compile time: 


```
export interface UserWhereInput {
  createdAt?: DateTimeInput;
  createdAt_not?: DateTimeInput;
  createdAt_in?: DateTimeInput[] | DateTimeInput;
  createdAt_not_in?: DateTimeInput[] | DateTimeInput;
  createdAt_lt?: DateTimeInput;
  createdAt_lte?: DateTimeInput;
  createdAt_gt?: DateTimeInput;
  createdAt_gte?: DateTimeInput;
  updatedAt?: DateTimeInput;
  updatedAt_not?: DateTimeInput;
  updatedAt_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_lt?: DateTimeInput;
  updatedAt_lte?: DateTimeInput;
  updatedAt_gt?: DateTimeInput;
  updatedAt_gte?: DateTimeInput;
  id?: UUID;
  id_not?: UUID;
  id_in?: UUID[] | UUID;
  id_not_in?: UUID[] | UUID;
  id_lt?: UUID;
  id_lte?: UUID;
  id_gt?: UUID;
  id_gte?: UUID;
  id_contains?: UUID;
  id_not_contains?: UUID;
  id_starts_with?: UUID;
  id_not_starts_with?: UUID;
  id_ends_with?: UUID;
  id_not_ends_with?: UUID;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
...
```

**Comment by pantharshit00** [comment]
I guess your code is technically wrong,

I have achieved to find the user's organisation by using:

```js
 const data = await prisma
    .user({ id: 'dcd4f996-af63-452c-ad8a-a1eb08451dbc' }) // the requested user
    .orgs()
```
You get the related field that are connected using id by simply calling the field. No need of doing the above stuff. The above stuff is required for other field like name.

**Comment by b33son** [comment]
Okay, I might be doing it wrong. What I'm trying to do, is only return the organizations the Authenticated user has in common with the requested User. In other words, if the Authenticated user isn't a member of the Organization himself, that Organization will not be returned. Example: 

Current Authenticated User's orgs: 
   Org A
   Org B
   Org C

Requests UserID with orgs: 
   Org A
   Org C
   Org E
   Org F

Returned orgs should be: Org A, Org C


Is there another way to do this you know of?

**Comment by haruska** [comment]
Has this been resolved? I think it's still a bug. For my issue, I cannot query it a different way as @pantharshit00 suggests because I'm trying to use a Relay Connection instead of just a list. 

The query that is supported (according to the generated prisma-client) is:
```
prisma.savedSearchesConnection({
  where: {
    portfolio: {
      id: "9768dff2-7d1f-4044-b650-6476da21da52"
    }
  }
)
```

The error is:
```
    Variable '$where' expected value of type 'SavedSearchWhereInput' but got: {"portfolio":{"id":"9768dff2-7d1f-4044-b650-6476da21da52"}}. Reason: 'portfolio.id' Field 'id' is not defined in the input type 'PortfolioWhereInput'. (line 1, column 43):
    query ($orderBy: SavedSearchOrderByInput, $where: SavedSearchWhereInput)
```

For reference, in prisma-schema.ts the definition starts with:
```
input PortfolioWhereInput {
  id: UUID
  id_not: UUID
  id_in: [UUID!]
  id_not_in: [UUID!]
  ...
}

input SavedSearchWhereInput {
  ...
  portfolio: PortfolioWhereInput
  ...
}
```

I guess I could roll my own Connection response but it seems like the client should handle this case according to the generated schema and types.
