### ISSUE TITLE
Automated test cases for binaries (brew, curl)

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma1#3672]
**Is your feature request related to a problem? Please describe.**
Currently, when we generate the binary using `pkg`, it bundles the current state of `node_modules` folder into the binary. This might lead to bugs (https://github.com/prisma/prisma/issues/3671).

There are also subtle differences between node APIs when accessed through the binary (https://github.com/prisma/prisma/issues/3458).

This requires manual testing of the binary on each generation. 

**Describe the solution you'd like**
We need to have automated tests around binaries for `brew`, `curl`. This can happen at the time of generation (maybe on upload to S3 event or push to brew repository event). We should check the following workflows (at least):

1. `prisma init`
2. `prisma deploy`
3. `prisma generate`

And test the deployed server (also client) with some basic operations.

**Comment by pantharshit00** [comment]
Using ncc many of these problems can be solved. An issue has already been about use of ncc https://github.com/prisma/prisma/issues/3666

We can have some integration tests at the time of generation. That will make us more confident to ship the binaries.
