### ISSUE TITLE
prisma-client connection retries 

### ISSUE THREAD

**Issue by runar-indico** [prisma/prisma1#3675]
**Describe the bug**
we are now attempting to move from subscriptions to `$subscribe` in the `prisma-client`. This seems to work great, except that if the prisma-backend is not reachable at the time when we set up the subscription, it will not give us any feedback, and no reconnect if the connection drops. Is there a way to access `onDisconnected`, `onError` etc to attempt to reconnect? 

**To Reproduce**

Subscribe to any event like `prismaClient.$subscribe.user`. Check that it is able to recieve the events, and then disconnect the server. 

**Expected behavior**
Expecting an error, with a possibility of reconnecting.

**Versions (please complete the following information):**
prisma: 1.22.1

**Comment by prilutskiy** [comment]
Also, after some timeout prisma client stops emitting events. However, everything starts to work again after restart, but that's not really a solution.

**Comment by divyenduz** [comment]
@prilutskiy : That sounds like a bug, can you please create a separate issue for it (possibly with a reproduction), in case that is not already covered by this not already covered via https://github.com/prisma/prisma/issues/3950
