### ISSUE TITLE
SDL declare order with relation.

### ISSUE THREAD

**Issue by yckao** [prisma/prisma1#3698]
**Describe the bug**
SDL in different order will cause different behavior.

I have a model like
```graphql
type Posts @pgTable(name: "posts") {
  id: Int! @unique
  ...
  member: Members @pgRelation(column: "member_id")
  ...
}

type Members @pgTable(name: "members") {
  id: Int! @unique
  ...
  posts: [Posts!]!
  ...
}
```

It is a bidirectional direct 1-N relation.

When Members is above
```graphql
{
    members(where: {id: xxx}) {
        posts {
            id
        }
    }
}
```
will use another table post_comments as relation table
and give wrong result.
even specify @relation(name: xxx)
SQL:
```sql
select
    "Alias"."id",
    "RelationTable"."post_id" as "__RelatedModel__",
    "RelationTable"."member_id" as "__ParentModel__"
from "public"."posts" as "Alias"
join "public"."post_comments" as "RelationTable"
    on "Alias"."id" = "RelationTable"."post_id"
where "RelationTable"."member_id" in ($1)
order by "RelationTable"."post_id" asc;
```

But if posts is above it work fine.
```sql
select
    "Alias"."id",
    "RelationTable"."id" as "__RelatedModel__",
    "RelationTable"."member_id" as "__ParentModel__"
from "public"."posts" as "Alias"
join "public"."posts" as "RelationTable"
    on "Alias"."id" = "RelationTable"."id"
where "RelationTable"."member_id" in ($1)
order by "RelationTable"."id" asc
```

**To Reproduce**
1. Using a exist database with a 1-N direct relation. (Maybe also need a table contain both foreign key)
2. Specify N above and query.
3. Change the order and query again.

**Expected behavior**
Same query result.

**Screenshots**
posts above:
<img width="485" alt="2018-12-13 6 45 20" src="https://user-images.githubusercontent.com/9109250/49933756-81108e80-ff07-11e8-9526-04b4705c15c4.png">

members above:
<img width="482" alt="2018-12-13 6 50 20" src="https://user-images.githubusercontent.com/9109250/49933922-f67c5f00-ff07-11e8-890d-8f3329e7552b.png">

**Versions (please complete the following information):**pri
 - OS: OS X Mojave
 - `prisma` CLI: prisma/1.22.2 (darwin-x64) node-v8.12.0
 - Prisma Server: prismagraphql/prisma:1.22
 - postgres

**Additional context**

**Comment by do4gr** [comment]
This should be fixed by 
You might have heard that we are transitioning to a new datamodel, see #3408.

For this we will soon start a closed beta. I tested the functionality using that datamodel and there it works. I'll invite you once the beta starts and then it should work for you. Since we are so close to switching over we'll not fix this bug for the old datamodel though.
