### ISSUE TITLE
Naming of generated types from MongoDB introspection 

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma1#3702]
The convention to name Prisma models is:
- use singular version 
- start with uppercase letters

MongoDB conventions to name collections are:
- use plural version
- start with lowercase letter

To account for this mismatch, `prisma introspect` for MongoDB should generate a name that accords to the Prisma convention and use the `@db` directive to map to the underlying collection. Or the naming convention to use singular, uppercase versions for models should be lifted in Prisma.

**Comment by timsuchanek** [comment]
Applying `camelize(singularize(collectionName))` for example from the `inflector` library should be sufficient.
