### ISSUE TITLE
Support for Scala Client

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [prisma/prisma1#3708]
I have an Akka/Scala, Spark, Kafka, PostgreSQL based application stack, I use Slick FRM for DB communication. Since Prisma support DAL as GraphQL service, I could not find any reference to Scala Client SDK. I like the support for TypeScript, useful for Angular/Node.js, without JVM client, the application stack seems incompatible. 

Can Prisma REST APIs can be accesses easily via simple POST/GET/PUT/DELETE method from JVM languages? Anyone point out what is the best way to communicate to Prisma through JVM client (Scala if possible)?

**Comment by pantharshit00** [comment]
Hi @gopalakrishnan-subramani,

I can understand your situation. We are working hard to make clients for all of the languages. Currently, only these clients are available:
1. JS client
2. TS client
3. Flow client
4. golang client

We will definitely add the Scala client in the future.

**Comment by pantharshit00** [comment]
You can consume the prisma API like any other graphql API. The client makes it easy to consume prisma. But it is possible to use it as a graphql endpoint.

You can use something like https://github.com/Jarlakxen/drunk in scala to consume it.
