### ISSUE TITLE
Query ReactNative SQLite

### ISSUE THREAD

**Issue by mxstbr** [prisma/prisma1#3719]
**Is your feature request related to a problem? Please describe.**
I hate manually having to query and manage my local SQLite database in ReactNative, even with Expo.

**Describe the solution you'd like**
It'd be awesome if I could use the Prisma query engine (?) to query the local SQLite database in ReactNative and Expo.

**Describe alternatives you've considered**
N/A

**Comment by mxstbr** [comment]
A SQLite connector wouldn't be enough I'm pretty sure as one can't run the Prisma server on a mobile device. I'm solely talking about turning a Prisma query into Sqlite-compatible SQL string and running it against WebSQL basically.

**Comment by timsuchanek** [comment]
@mxstbr my apologies 🙌  that indeed is a separate issue.

**Comment by flybayer** [comment]
Yes, this would be an amazing feature to have!

**Comment by dantman** [comment]
If this were supported, Prisma could potentially be the best react-native app data storage API I've seen.

**Comment by 5hee75** [comment]
Over 2 years since the last activity on this issue - not a great sign - but is there any hope this could happen?  This would also be a great feature to have against the local SQLite database when exposed through Cordova, Capacitor, or Ionic Secure Storage.
