### ISSUE TITLE
go-client generator errors

### ISSUE THREAD

**Issue by speix** [prisma/prisma1#3720]
For the last week I've been testing the go-client generator with an existing database, and it seems that its not ready for production.  The prisma playground works fine by the way.

If my Postgres schema is as simple as possible (say a User and Posts), the generator works fine. 
When I am integrating a little more complicated relationship I get a ton of errors on go compilation like the ones below:

```
prisma\prisma-client\prisma.go:124:69: undefined: AssetTypeExec
prisma\prisma-client\prisma.go:145:61: undefined: AssetTypeExecArray
prisma\prisma-client\prisma.go:179:80: undefined: AssetTypeConnectionExec
prisma\prisma-client\prisma.go:440:70: undefined: AssetTypeExec
prisma\prisma-client\prisma.go:455:71: undefined: AssetTypeExec
prisma\prisma-client\prisma.go:490:71: undefined: AssetTypeExec
prisma\prisma-client\prisma.go:505:75: undefined: AssetTypeExec
prisma\prisma-client\prisma.go:2481:45: undefined: AssetTypeExec
prisma\prisma-client\prisma.go:2537:52: undefined: AssetTypeEdgeExec
prisma\prisma-client\prisma.go:3494:60: undefined: AssetTypeExec
prisma\prisma-client\prisma.go:3494:60: too many errors
```

For some reason the generator does not create the above structs (and many others).

Below you'll find my test datamodel.prisma (which was generated by prisma introspect). 
Can you please check it out and tell me if you find something wrong with it? Do I have to follow some specific naming convention for my database? Thanks.

```
type Asset @pgTable(name: "asset") {
  id: Int! @unique @pgColumn(name: "asset_id")
  active: Boolean! @default(value: false)
  address: String
  asset_type: Asset_type @pgRelation(column: "asset_type_id")
  bedrooms: Int
  coordinates: String
  createdAt: DateTime!
  description: String
  expenses_hoa: Float
  expenses_monthly_tax: Float
  floors: Int
  full_bath: Int
  garage_sf: Int
  half_bath: Int
  house_sf: Int
  kitchens: Int
  lot_sf: Int
  one_quarter_bath: Int
  price: Int
  published: Boolean! @default(value: false)
  slug: String! @unique
  three_quarters_bath: Int
  updatedAt: DateTime!
  url: String
  user: User @pgRelation(column: "user_id")
  year_built: Int
  year_remodeled: Int
  zip: String
}

type Asset_type @pgTable(name: "asset_type") {
  id: Int! @unique @pgColumn(name: "asset_type_id")
  assets: [Asset!]!
  createdAt: DateTime!
  icon: String!
  sorting: Int! @default(value: 0)
  # title: null! # Type 'jsonb' is not yet supported.
  updatedAt: DateTime!
}

type Role @pgTable(name: "role") {
  id: Int! @unique @pgColumn(name: "role_id")
  createdAt: DateTime!
  system: String!
  title: String!
  updatedAt: DateTime!
  users: [User!]!
}

type User @pgTable(name: "user") {
  id: Int! @unique @pgColumn(name: "user_id")
  active: Boolean! @default(value: false)
  assets: [Asset!]!
  createdAt: DateTime!
  email: String! @unique
  firstname: String
  gender: String
  hash: String
  lastname: String
  pass: String
  remember_token: String
  role: Role @pgRelation(column: "role_id")
  updatedAt: DateTime!
}
```

One last things is that the generated prisma.go client has the below datatype definition, using pointers for the User struct. Why is that?
```
type User struct {
	ID            int32   `json:"id"`
	Active        bool    `json:"active"`
	CreatedAt     string  `json:"createdAt"`
	Email         string  `json:"email"`
	Firstname     *string `json:"firstname,omitempty"`
	Gender        *string `json:"gender,omitempty"`
	Hash          *string `json:"hash,omitempty"`
	Lastname      *string `json:"lastname,omitempty"`
	Pass          *string `json:"pass,omitempty"`
	RememberToken *string `json:"remember_token,omitempty"`
	UpdatedAt     string  `json:"updatedAt"`
}
```

**Comment by divyenduz** [comment]
@speix : Can you please share a small reproduction repository where we can observe this behavior? Specifically, what datamodel are you using? 

Thanks.

**Comment by speix** [comment]
@divyenduz the first problem occurs when I have tables with **created_at** and **updated_at** fields instead of **createdAt** and **updatedAt**. For some reason the generator expects the name convention to be CamelCase when introspecting an existing database.

The second problem comes from the fact that some fields into the database are nullable by default. Which means they accept NULL values and the introspect extracts those fields without ! mark like below:

```
type User @pgTable(name: "user") {
  ...
  firstname: String
  ...
}
and this translates to:
firstname *string
```

For the second problem (*string) I suppose that's because a pointer to a string can be nil? But do we need to distinguish an empty string from no string?

**Comment by pantharshit00** [comment]
I can confirm this behavior but I don't know this is expected or not.

cc @dominikh
