### ISSUE TITLE
sync-exec; 1 sync-exec vulnerability found in package-lock.json

### ISSUE THREAD

**Issue by steida** [prisma/prisma1#3723]
```
npm list sync-exec
este@ /Users/steida/dev/este-typescript
└─┬ prisma@1.22.2
  └─┬ prisma-cli-core@1.22.2
    └─┬ npm-run@4.1.2
      └── sync-exec@0.6.2
```

Should not be used imho.

**Comment by divyenduz** [comment]
There is a regression in windows for `npm-run` (https://github.com/prisma/prisma/pull/3517). We can upgrade this after this one is merged https://github.com/timoxley/npm-run/pull/21

Or break the build for windows temporarily. Can you please confirm what the vulnerability is exactly and does it also affect CLI tools?

**Comment by steida** [comment]
I think it's not severe, because it's for local web development, but I am not an expert. I would wait, this issue can help the others meanwhile.

**Comment by tianhuil** [comment]
The regression is still around.  Any ETA on fixing this?
```
$ npm list sync-exec
project@0.0.3
└─┬ prisma@1.34.1
  └─┬ prisma-cli-core@1.34.1
    └─┬ npm-run@4.1.2
      └── sync-exec@0.6.2
```
