### ISSUE TITLE
Reuse the internal datamodel representation in the introspection

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma1#3725]
In order to support directives like `@db`, `@id` `@createdAt` and `@updatedAt` in introspection, we need to take the current mappings that are defined in the datamodel into account, as not all of the information can be inferred by the pure data and data structure.

The desired way of handling this is the following: When performing the introspection, we will look into the local datamodel file to look for directives that are defined on types or fields that we just introspected. If anything relevant is being found in that local datamodel, we apply that to the introspection result. This way, users can control the introspection result in the future, when they, for example, add a field through a rails migration.

Using the local datamodel as the basis to perform the introspection can have one disadvantage, though: It could get out of sync with the real database. To circumvent this issue, we want to introduce a `prisma introspect --overwrite` command, which would overwrite the local datamodel and is specified in https://github.com/prisma/prisma/issues/3729.

Directives that affect renaming:
- `@db` - this can either rename a field or a type
- `@id` - the MongoDB connector always maps this to `_id`, even if the field which has the `@id` directive applied may be called `foo`

An example schema we want to support:
```graphql
type User @db(name: "users") {
  foo: ID! @id
  createdAt: DateTime! @createdAt
}
```

The handling of the `id` directive is specified in detail in https://github.com/prisma/prisma/issues/3733

**Comment by ejoebstl** [comment]
I've been thinking a lot about the workflow for this feature lately.

Would it make sense to reuse all directives, comments etc in the existing model?
Or in a more extreme case, just add new fields or types to the model, when re-introspecting?
