### ISSUE TITLE
The MongoDB connector should support transactions for nested mutations

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma1#3738]
Currently, nested mutations with the MongoDB connector are not executed transactionally and therefore might bring your project into an inconsistent state and break the API. See [this](https://github.com/prisma/prisma/issues/3718) issue as an example.

**Comment by do4gr** [comment]
MongoDB itself started supporting multi-document transactions starting with 4.0. 

The Prisma Mongo connector is not officially tested against 4.0 yet but we would expect it to just work. Making use of the transactional capabilities that 4.0 offers is something we would need to explicitly add though.

We currently do not think that the implementation is the main hurdle, the biggest task is to get an understanding of the performance implications and potential deadlock issues this brings with it. 

The SQL connectors also always run with transactionality enabled by default. It is not yet clear to us whether this should be the case for Mongo as well or whether users would like to configure this (to avoid performance penalties for example.)

If any one has a strong opinion on this or has specific use cases where they want / do not want it we would like to hear from you!

**Comment by nikolasburk** [comment]
Thanks a lot for the explanation! 

I think this is a very important product decision because not supporting transactions would mean that we're accepting projects to be inconsistent which will lead to errors further down the road in the same project. 

Consider the example from [this](https://github.com/prisma/prisma/issues/3718) issue where the following datamodel was used:

```
type User {
  id: ID! @id
  name: String
  companies: [Company!]! @relation(link: INLINE)
}

type Company {
  id: ID! @id
  name: String
  user: User!
}
```

Note that the `user` field is required on the `Company` model.

But because the transaction failed, there was a `Company` node created that had no `User` associated with it! This will lead to a GraphQL error when that `Company` node with the `user` relation is being retrieved.

**Comment by johnsonjo4531** [comment]
Hey @allanplima,  here's how to [format multi-line code on Github](https://help.github.com/articles/creating-and-highlighting-code-blocks/). Might I also suggest using `json` or `js` as the language like so.

    ```js
    <code goes here>
    ```

Also if your new to markdown in general I recommend reading [Github's markdown guide](https://help.github.com/articles/basic-writing-and-formatting-syntax/) or the [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) they are both pretty similar so only reading one is fine.

**Comment by monojack** [comment]
Doesn't work for me with MongoDB 4.0.6.

Im trying this ([from the docs](https://www.prisma.io/docs/prisma-client/basic-data-access/writing-data-JAVASCRIPT-rsc6/))

```js
const newUserWithLinks = await prisma
  .createUser({
    name: "Alice",
    email: "alice@prisma.io",
    password: "IlikeTurtles",
    links: {
      create: [{
        description: "My first link",
        url: "https://www.prisma.io"
      }, {
        description: "My second link",
        url: "https://www.howtographql.com"
      }]
    }, 
  })
```

the model is:
```graphql
type Link {
  id: ID! @id
  createdAt: DateTime!
  description: String!
  url: String!
  postedBy: User
  votes: [Vote!]! @relation(link: INLINE)
}

type User {
  id: ID! @id
  name: String!
  email: String! @unique
  password: String!
  links: [Link!]! @relation(link: INLINE)
  votes: [Vote!]! @relation(link: INLINE)
}

type Vote {
  id: ID! @id
  link: Link!
  user: User!
}
```

and I get the following error:
```bash
{
  "result": {
    "data": null,
    "errors": [
      {
        "message": "Variable '$data' expected value of type 'UserCreateInput!' but got: {\"name\":\"Alice\",\"email\":\"alice@prisma.io\",\"password\":\"IlikeTurtles\",\"links\":{\"create\":[{\"description\":\"My first link\",\"url\":\"https://www.prisma.io\"},{\"description\":\"My second link\",\"url\":\"https://www.howtographql.com\"}]}}. Reason: 'links.create[0].createdAt' Expected non-null value, found null. (line 1, column 11):\nmutation ($data: UserCreateInput!) {\n          ^",
        "locations": [
          {
            "line": 1,
            "column": 11
          }
        ]
      },
      {
        "message": "Variable '$data' expected value of type 'UserCreateInput!' but got: {\"name\":\"Alice\",\"email\":\"alice@prisma.io\",\"password\":\"IlikeTurtles\",\"links\":{\"create\":[{\"description\":\"My first link\",\"url\":\"https://www.prisma.io\"},{\"description\":\"My second link\",\"url\":\"https://www.howtographql.com\"}]}}. Reason: 'links.create[0].createdAt' Expected non-null value, found null. (line 1, column 11):\nmutation ($data: UserCreateInput!) {\n          ^",
        "locations": [
          {
            "line": 1,
            "column": 11
          }
        ]
      }
    ],
    "status": 200
  }
}
```

**Comment by EhsanSarshar** [comment]
so Prisma is not safe and I should implement my own API with mongoose

**Comment by akhilshastri** [comment]
is there any plan for it ...?
