### ISSUE TITLE
Self-relation challenge

### ISSUE THREAD

**Issue by jferrettiboke** [prisma/prisma1#3744]
Hi guys,

I do not know if it is a bug or not but I struggling with this... Maybe I missed something...

Consider, San Francisco (city), California (state) and United States (country). All of them are locations.

```graphql
type Location {
  id: ID! @unique
  name: String!
  parent: Location @relation(name: "ParentLocationRelation")
  children: [Location!]! @relation(name: "ChildLocationRelation")
  # More fields...
}
```

The question is simple. How to relate all these locations? I want to add California as a location, San Francisco as a child location of California and United States as a parent location of California. It works! But... When I query all locations, I get...

```json
{
  "data": {
    "locations": [
      {
        "name": "California",
        "parent": {
          "name": "United States"
        },
        "children": [
          {
            "name": "San Francisco"
          }
        ]
      },
      {
        "name": "United States",
        "parent": null,
        "children": []
      },
      {
        "name": "San Francisco",
        "parent": null,
        "children": []
      }
    ]
  }
}
```

United States has no children (California) and San Francisco has no parent (California)! Is this a bug or is this intentional? Am I missing something?

For more context, this is the mutation and response.

```graphql
mutation {
  createLocation(
    data: {
      name: "California"
      parent: { create: { name: "United States" } }
      children: { create: { name: "San Francisco" } }
    }
  ) {
    name
    parent {
      name
    }
    children {
      name
    }
  }
}
```

```json
{
  "data": {
    "createLocation": {
      "name": "California",
      "parent": {
        "name": "United States"
      },
      "children": [
        {
          "name": "San Francisco"
        }
      ]
    }
  }
}
```

**Comment by pantharshit00** [comment]
Hi @jferrettiboke,

I implemented this kind of datamodel a while ago. I went with the following approach:

```graphql
type Location {
  id: ID! @unique
  name: String! @unique
  parent: [Category!]! @relation(name: "LocationsParents")
}
```

I am only tracking the parent of the node. In this pattern, the root node will have no parent. That will be the identification of the root node. This allows us to have a nice tree-like recursive data structure pattern. You will also be able to query down the tree.

```graphql
mutation {
  createLocation(
    data: {
      name: "California"
      parent: { create: { name: "United States" } }
      children: { create: { name: "San Francisco" } }
    }
  ) {
    name
    parent {
      name
    }
    children {
      name
    }
  }
}
```

**Comment by pantharshit00** [comment]
Hi @jferrettiboke, Sorry for the accidental closing of the issue.


Your approach is not working as when you are using create it will not interlink the children and the parent. You will need to retrieve their `ids` and connect them in the code using `connect` argument in the input of the updateLocation mutation.

I will recommend you should not make two separate fields and should consider using only one field like. United State -> California -> San Francisco . US will have no parent. California will have the US as the parent. Lastly, San Francisco will have California as the parent. That will allow you to make nice recursive queries to this tree and retrieve data easily.

This is the query for three levels deep field like you have:

```graphql
{
  locations {
    name
    parent {
      name
      parent {
        name
      }
    }
  }
}
```

Datamodel for this approach:

```graphql

type Location {
  id: ID! @unique
  name: String! @unique
  parent: [Location!]! @relation(name: "LocationsParents")
}

```


Then you will be able to connect them in one mutation like so: 


```graphql
mutation {
  createLocation(
    data: {
      parent: {
        create: {
          name: "SF"
          parent: { create: { name: "CA", parent: { create: { name: "US" } } } }
        }
      }
    }
  ) {
    id
  }
}
```

**Comment by do4gr** [comment]
I just answered a similar question here with an approach that lets you keep both the parent and child fields: https://stackoverflow.com/questions/54019995/how-to-create-categories-and-its-subcategory-in-prisma-orm-using-mongodb/54020530#54020530

Your  misunderstanding seems to be that you created two separate relations which both only have one side explicit in the datamodel (You did this by giving two different names). What it sounds like what you wanted to do is to create one relation that has both fields present(for this the relation name needs to be the same for both).

**Comment by sohebm** [comment]
I have the same problem, I am building the market place where I have Categories and Sub-Categories. Unfortunately, I do not have the level of Sub-Categories defined. Below is my datamodel:

```
type Category {
 id: ID! @id
 name: String!
 description: String
 parentId: Category @relation(link: INLINE)
}
```
If the parentId is null then it is my Main Categories, other it is sub-category.

I am unable to query Category where my parentId is null

**Comment by gotexis** [comment]
@sohebm 
Any solution yet?
I think it rather just works, with the current version of Prisma -- I tested it.

Wonder if you could convirm
