### ISSUE TITLE
`prisma.$graphql` could accept not only string, but also `graphql-tag`ed object

### ISSUE THREAD

**Issue by beeplin** [prisma/prisma1#3750]
**Is your feature request related to a problem? Please describe.**
In `prisma.$graphql(query, variables)` now `query` could only be string, not query object generated via `graphql-tag`.

**Describe the solution you'd like**
It would be nice to be able to do this: 
```js
import gql from 'graphql-tag'
const QUERY = gql` 
  query.....
`
prisma.$graphql(query)
```

**Comment by pantharshit00** [comment]
Hi @beeplin,


Can you tell me a use case of supporting the graphql tag here? If you are concerned about syntax highlighting you can do that in regular strings using a simple comment like so: 

```js
const QUERY = /* GraphQL */` 
  query.....
`
prisma.$graphql(query)
```

**Comment by beeplin** [comment]
@pantharshit00 Thank you for the quick response. 

It's not only for syntax highlighting but also for linting. For example, with `eslint-plugin-graphql`  + vscode eslint extension, we could lint errors (graphql syntax errors, non-existing fields, etc.) in graphql-tagged strings: 

![image](https://user-images.githubusercontent.com/13058150/50289520-0fef4f00-04a4-11e9-8c02-8e8a2be02ce6.png)

![image](https://user-images.githubusercontent.com/13058150/50289527-15e53000-04a4-11e9-9966-75e57f07a4ec.png)

But this linting by default cannot detect raw strings even we have `/* GraphQL */` before them. 

And also, sometimes we need to use the same query, or mutation, or especially a fragment, in both an apollo/graphql-request api (which require a graphql-tagged object) and a prisma.$graphql api (which requires a raw string). Currently for this situation I could only define two versions of the same thing, which seems quite ugly and awkward: 

```js
import gql from 'graphql-tag'

export const JOB_FOR_LOCK_CHECK_STRING = /* GraphQL */ `
  id
  requiredJobs {
    id
    title
    userJobRecords(where: { userId: $userId }) {
      id
      userId
      jobId
      score
    }
  }
`

export const JOB_FOR_LOCK_CHECK = gql([`fragment JobForLockCheck on Job { ${JOB_FOR_LOCK_CHECK_STRING} }`])
```

**Comment by joshhopkins** [comment]
Have just come across this too. Support for `graphql-tag` would be great.

**Comment by rostislav-simonik** [comment]
Am I right that  this will also support `*.graphql` files where you can benefit from other things like `#import ...` etc.
