### ISSUE TITLE
Cannot use ID in where clause

### ISSUE THREAD

**Issue by b33son** [prisma/prisma1#3757]
**Describe the bug**
Prisma throws error when using id in the where clause of a query. 

```
const posts = ctx.prisma.posts({
      where: { owner: { id: "47bd123b-4920-4253-8b07-ddd123dee1ad" } },
    });
```

```
Error: Variable '$where' expected value of type 'PostWhereInput' but got: {"owner":{"id":"47bd123b-4920-4253-8b07-ddd123dee1ad"}}. Reason: 'owner.id' Field 'id' is not defined in the input type 'UserWhereInput'. (line 1, column 8):
[0] query ($where: PostWhereInput) {
```

The same exact query works with a different unique field such as 

    const posts = ctx.prisma.posts({
      where: { owner: { username: "Dorothy" } },
    });

```
{
  "data": {
    "userPosts": []
  }
}
```

**To Reproduce**

**datamodel.prisma**
type User @model {
  createdAt: DateTime!
  updatedAt: DateTime!
  id: UUID! @unique
  username: String! @unique
  fullName: String 
  posts: [Post!]! @relation(name: "UserPost")
}

type Post @model {
  createdAt: DateTime!
  updatedAt: DateTime!
  id: UUID! @unique
  name: String! @unique
  caption: String
  owner: User @relation(name: "UserPost") 
}

**Resolver**
  userPosts: (parent, { id }, ctx) => {
    console.log(`userPosts: `, id);
    const posts = ctx.prisma.posts({
      where: { owner: { username: "Dorothy" } },
    });
    return posts;
  },

**Query**
query userPosts($id:UUID!){
  userPosts (id:$id){
    id
    name
  }
}

**Schema.graphql**
type Query { 
  userPosts(id: UUID!): [Post!]! 
}

**Expected behavior**
Should be able to query on either field. 

**Versions (please complete the following information):**
"dependencies": {
    "@types/bcrypt": "^3.0.0",
    "@types/jest": "^23.3.10",
    "@types/jsonwebtoken": "^8.3.0",
    "bcrypt": "^3.0.2",
    "graphql-shield": "^4.1.0",
    "graphql-yoga": "^1.16.7",
    "jsonwebtoken": "^8.4.0",
    "prisma-client-lib": "^1.23.0-test.3"
  },
  "devDependencies": {
    "apollo-boost": "^0.1.22",
    "apollo-cache-inmemory": "^1.3.11",
    "apollo-client": "^2.4.7",
    "apollo-link-http": "^1.5.7",
    "graphql": "^14.0.2",
    "graphql-tag": "^2.10.0",
    "graphqlgen": "0.4.0",
    "jest": "^23.6.0",
    "json-stringify-extended": "^2.0.0",
    "moment": "^2.22.2",
    "nodemon": "1.18.7",
    "ts-jest": "^23.10.5",
    "ts-node": "^7.0.1",
    "typescript": "^3.2.1"
  },

**Comment by pantharshit00** [comment]
Hi @b33son, Thanks for reaching out!

You can achieve the behaviour you want using the following code:
```js
prisma.user({ id: '987d1464-9db0-4b3f-a90d-e398d9834300' }).posts()
```

This will grab the posts where the user is `987d1464-9db0-4b3f-a90d-e398d9834300`

Hope this will solve your issue

**Comment by yckao** [comment]
> Hi @b33son, Thanks for reaching out!
> 
> You can achieve the behaviour you want using the following code:
> 
> ```js
> prisma.user({ id: '987d1464-9db0-4b3f-a90d-e398d9834300' }).posts()
> ```
> 
> This will grab the posts where the user is `987d1464-9db0-4b3f-a90d-e398d9834300`
> 
> Hope this will solve your issue

Also facing same issue
And I am using schema binding with relay support.
`prisma.myTypeConnection(where: {otherType: {id: '19366c44-9e3c-4972-9623-4b495857c3f8'}})`
change query direction may not appropriate in this situation.

**Comment by AnselmMarie** [comment]
I'm using Prisma version 1.28.0 and my code is similar to @b33son and I'm still having this issue. The database I'm using is PostgresSQL.
