### ISSUE TITLE
Does mongodb connector supports GridFS

### ISSUE THREAD

**Issue by soqt** [prisma/prisma1#3764]
GridFS is for resolving 16mb limit for single file. Does prisma currently support this feature?

**Comment by pantharshit00** [comment]
Hi @soqt,

The mongo connector is currently in preview and we currently do not support gridFS out of the box. You will be able to use access the gridFS data using raw database access later on.

**Comment by fuergaosi233** [comment]
How can I use the raw database access in Prisma?
