### ISSUE TITLE
fragmentReplacements and Prisma Client

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma1#3791]
**Is your feature request related to a problem? Please describe.**
Current implementation of Prisma client does not support `fragmentReplacements` as schema delegation is not a feature of Prisma client. 

This makes usage of Prisma Client with libraries like [middleware fragments](https://github.com/prisma/graphql-middleware#middleware-fragments) a bit inconvenient because you have to use the [`$fragment`](https://www.prisma.io/docs/prisma-client/basic-data-access/reading-data-JAVASCRIPT-rsc2/#using-fragments-for-fine-grained-data-access) syntax in each resolver to make it work defeating the purpose of middleware fragments. 

**Describe the solution you'd like**
Prisma Client can support `fragmentReplacements` via a new API that might look like this:

```
const prisma = new Prisma({
  // Other Initialization options like endpoint, secret
  fragmentMap: {
    User: `... on User { profile { name } }`
  }
})
```

**Describe alternatives you've considered**
Currently, I have to use `$fragment` syntax on each resolver or fall back to use binding (missing our on awesome Client features including type safety).

**Comment by timsuchanek** [comment]
This is related to field preselection.
