### ISSUE TITLE
[Mongo] Cascading deletes

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma1#3796]
Cascading deletes is not implemented for the Mongo connector.

A validation should be added to the deploy step to make sure that it is not declared on the data model.

Note: Embedded types by their nature already have a cascading delete effect; deleting a top level type will of course also delete all its embedded types.

**Comment by domekol** [comment]
This should be in the docs, i just wanted to create an issue for.

https://github.com/domekol/prisma-mongodb-cascade-relation-bug

**Comment by tiagocpontesp** [comment]
This should definitely be in the docs

**Comment by ezeikel** [comment]
@do4gr  So will this be eventually implemented or is there a reason why?

**Comment by do4gr** [comment]
Our implementation of Cascading Deletes in the SQL connectors relies on transactional guarantees across tables.

Mongo only started supporting cross-document transactions with 4.0. We are at the moment testing at what performance penalty enabling transactions on Mongo comes since this is a very new concept for them.

**Comment by remorses** [comment]
For what release will this be fixed?

**Comment by do4gr** [comment]
Our prototype that implemented cascading deletes using transactions showed transaction errors (deadlocks etc. ) under heavy concurrency. We therefore cannot implement this feature at the moment. 

Until we can we will therefore add an error during deployment to avoid confusion.

**Comment by nikolasburk** [comment]
Reopening this issue as cascading deletes is not yet implemented for the Mongo connector. However, since we're not tackling this any time soon (see @do4gr's last comment), we're applying the `on-hold` label for now.

**Comment by FinnFrotscher** [comment]
are we talking weeks, months or years?
Do you propose a specific workaround?

**Comment by do4gr** [comment]
I think this will probably take a couple of months until we can focus on this.

**Comment by Divine1** [comment]
> https://github.com/domekol/prisma-mongodb-cascade-relation-bug

@domekol  is this issue fixed?

**Comment by developerk786** [comment]
any updates regarding this issue, since I am making production ready app so any trick or the third party will also be better for me?

**Comment by rip3rs** [comment]
Is there any new news on this?

I believe this to be major. While there is no updates for this.

> Until we can we will therefore add an error during deployment to avoid confusion.
What would be the recommended way to "cascade" deletion on a relation?

cheers

**Comment by omarragi** [comment]
Can someone point me to an alternative for now ?

**Comment by developerk786** [comment]
currently, I am doing cascading deletes manually @omarragi

**Comment by rip3rs** [comment]
@developerk786  could you give us a simple example :)

**Comment by entrptaher** [comment]
So if you have a nested relation like I did, it's gonna be a nightmare.

User => (Posts => Photos) + Comments + Favorites + Friends + ...

It will have to remove all of them when we remove a user. Otherwise they will become null and gather dust in the database for no reason.

Here is the similar code we had to put,

```js
const result = await deleteAction({
    where: {
        id: args.id
    }
}, info);

// TODO: use a queue instead of blocking all connection here
// What if the user has 100k logs on a instance? :/
await Promise.all([
    logs && logs.length && (await deleteManyLogs(logs.map(log => ({
        where: {
            id: log.id
        }
    })))),
    content && (await deleteContent({
        where: {
            id: content.id
        }
    })),
    state && (await deleteState({
        where: {
            id: state.id
        }
    })),
    source && (await deleteSource({
        where: {
            id: source.id
        }
    })),
]);
```

Then we were forced to refactor them a bit because we had to use them many times on many reducer, the code is kind of similar to this,

```js
const deleteSingle = (group, mutation, info) => group && mutation({
  where: {
      id: group.id
  }
}, info);

const groupMapped = group => group.map(single => ({
  where: {
      id: single.id
  }
}));

const deleteMany = (group, mutation) => group && group.length && mutation(groupMapped(group));

// Run them
// we need to use/return this later
const result = await deleteSingle(args, deleteAction, info);
await Promise.all([
  deleteMany(logs, deleteManyLogs),
  deleteSingle(content, deleteContent),
  deleteSingle(state, deleteState),
  deleteSingle(state, deleteSource)
])
```

Maybe there is a better way to deal with this, who knows!

**Comment by developerk786** [comment]
@entrptaher Your solution is better than mine =D, for now, we can do this but we can rely on prisma2 for future apps

**Comment by remorses** [comment]
I just released [mongoke](https://github.com/remorses/mongoke), it is a docker image that instantly serves your mongodb database via graphql and , contrary to prisma, works with existing databases, this means that you can directly insert and update the data in your database without worrying about corrupting prisma data model. It generates only graphql queries but you can easily attach other graphql services (to handle custom mutations) thanks to [apollo federation](https://github.com/remorses/mongoke/blob/master/docs/docker.md#apollo-federation).
It also has built in authorization using your jwt which means you can expose directly the service to the open world.

**Comment by EhsanSarshar** [comment]
You should also remove it from docs
https://www.prisma.io/docs/datamodel-and-migrations/datamodel-MONGO-knun/
