### ISSUE TITLE
Prisma client: mutation ignored when callback not provided

### ISSUE THREAD

**Issue by dodas** [prisma/prisma1#3810]
I am implementing an mutation resolver.
I make and await mutations that are essential to fulfilling this query.
Then, I want to initiate an additional mutation, immediately return and complete this mutation in background, while client already got his response.

Something along lines:
```js
async mutationResolver() {
  const updated = await prisma.updateEntityX({ ... });
  prisma.updateEntityY({ ... }); // < no await or any "then" callback
  return updated;
}
```
Then, I inspect prisma database and it seems like call to `prisma.updateEntityY()` is totally ignored, until I provide some callback, e.g.:
```js
prisma.updateEntityY({ ... }).then(() => {}); // just an empty handler
```

Is this really the case? Seems weird.

Thanks.

**Comment by pantharshit00** [comment]
Hi @dodas,

We internally batch thing up using data loader so this is expected behavior in my opinion. Let me know any solid use case of your setup if there is any.

**Comment by dodas** [comment]
I already described my exact use case :)
I need to perform a mutation that's result is not needed for resolver's return value.
I just want to return value from resolver and finish this additional mutation in background.

**Comment by pantharshit00** [comment]
Related: https://github.com/prisma/prisma/issues/4179

cc @divyenduz

**Comment by divyenduz** [comment]
Thanks for raising this issue @dodas 

Currently, you have to consume the Prisma client promise for it to actually fire, it is designed to be lazy right now. But in your case, you are calling `.then` and the mutation still does not fire, which sounds like a bug. 

This was a related discussion with some workarounds but it is closed by the author, so, I would keep this issue open to track this: https://github.com/prisma/prisma/issues/3827
