### ISSUE TITLE
prisma updateMany execution order issue

### ISSUE THREAD

**Issue by xiaoqf10** [prisma/prisma1#3811]
I have a question regarding prisma client `updateMany`. We use it to wrap deletions from two tables into one transaction, we also want to delete the relation between them. We are soft deleting so what we do is actually `update` TableA, `updateMany` TableB, and `disconnect` TableB. It turns out when we have both `disconnect` and `updateMany` in the same `data` object, the `updateMany` will be ignored.  It seems there is some internal priorities and the disconnect was executed first? Is it a design choice or is it a bug? Thx!

**Comment by pantharshit00** [comment]
cc @mavilein

**Comment by pantharshit00** [comment]
Update I tried to reproduce this myself and was successful:

```graphql
mutation {
  updateUser(
    data: {
      organisations: {
        disconnect: { id: "cjqwhotlv000c0907wkcjp1l7" }
        updateMany: {
          where: { id: "cjqwhotlv000c0907wkcjp1l7" }
          data: { name: "Jsaf" }
        }
      }
    }
    where: { id: "cjqwhotnm000d0907vhvmf0pr" }
  ) {
    id
  }
}
```

Here is the reproduction repo: https://github.com/pantharshit00/prisma-issue-3811

**Comment by xiaoqf10** [comment]
@mavilein Is this bug fixed?

**Comment by divyenduz** [comment]
Turning this into a feature request which would enable controlling the execution order of a single query.

**Comment by m3hari** [comment]
+1, What is the plan? Looks like it's a bug
