### ISSUE TITLE
Prisma client mutations do not get executed without await or callback

### ISSUE THREAD

**Issue by Elfayer** [prisma/prisma1#3827]
**The bug**
Prisma client mutations do not get executed without `await` or callback.

**To Reproduce**
Using Prisma JS client:
`index.js`
```js
const { prisma } = require('./generated/prisma')

const foo = async () => {
  await prisma.updateManyLoans({ data: { isCanceled: true } }) // Gets executed
}
foo()

const bar = () => {
  prisma.updateManyLoans({ data: { isCanceled: true } }) // Doesn't get executed
}
bar()

prisma.updateManyLoans({ data: { isCanceled: true } }).then() // Gets executed
prisma.updateManyLoans({ data: { isCanceled: true } }) // Doesn't get executed
```

**Expected behavior**
Expect `prisma.updateManyPosts({ data: { isCanceled: true } })` to get executed and be reflected in the DB.

**Versions:**
 - OS: `Windows 10`
 - `prisma` CLI: `prisma/1.19.0 (windows-x64) node-v8.11.2`
 - Prisma Server: `1.19.0`
 - `graphql-cli`: `2.16.5`
- `prisma-client-lib`: `1.19.0`

**Additional context**
I need to create a job task to be executed every day, for that I want to run a prisma client mutation.

**Comment by mavilein** [comment]
Hey @Elfayer ,

is it a problem for you that you need to await it? The prisma client is intentionally designed in a lazy way so that queries are executed only when the developer consumes the promise.

**Comment by Elfayer** [comment]
Hi @mavilein , thanks for the quick answer!

I was hopping to be able to run multiple parallel commands at the same time.
Is this meant to avoid consistency issues?

**Comment by mavilein** [comment]
It is mostly used to allow for chaining in queries, e.g. the example from the homepage:
```javascript
await prisma
  .post({ id: "cjl4srkaqqxa30b46pqcyzpyo" })
  .comments()
```
This results in one query being sent to the backend. If the evaluation would be eager we would have two roundtrips to the server.

**Comment by schickling** [comment]
@Elfayer you can execute multiple queries in parallel like this in JS/TS:

```ts
const q1 = prisma.posts() // no await here
const q2 = prisma.users() // no await here
const [posts, users] = await Promise.all([q1, q2])
```

Does that answer your question?
