### ISSUE TITLE
resolving relationships when one entity can be of more than one type?

### ISSUE THREAD

**Issue by udithv** [prisma/prisma1#3850]
Please provide your feedback here instead: https://github.com/prisma/prisma-content-feedback/issues/new?template=documentation-feedback.md.

Provide documentation for querying relationships when one  or  both entities involved can be of more than one type.

Let's say like hackernews , there can be two kinds of posts .One that just has a link and title and another that is more like a blog post. 

Traversing these entities can be included in the documentation.

**Comment by pantharshit00** [comment]
Hi,

I would define a datamodel 

```graphql
type Post{
  id: ID! @unique
  link: String
  title: String
  blog-content: String
  isBlog: Boolean!
}
```

That will allow you to query it like so 

```graphql
{
  posts(where:{ isBlog: true }){
     blog-content
   }
}
```

For more advanced use case you can separate them to their own types and query them separately:

```graphql
type Post{
  id: ID! @unique
  link: String!
  title: String!
}
type Blog {
  id: ID! @unique
  blog-content: String!
}
```

```graphql
{
  posts{
     title
   }
   blogs{
     blog-content
   }
}
```

**Comment by pantharshit00** [comment]
Also, our datamodel v2 will improve this further later when it will get released:
https://github.com/prisma/prisma/issues/3407

**Comment by udithv** [comment]
But this solution is hardly flexible. What if you have more than two types ?. I was thinking more in the line of expressing the relationship between the types.
