### ISSUE TITLE
$WHERE OR / NOT available in mongodb?

### ISSUE THREAD

**Issue by Mercurial** [prisma/prisma1#3897]
I can't seem to use WHERE OR , WHERE NOT in MongoDB

![image](https://user-images.githubusercontent.com/585569/51463617-97c7c200-1d9e-11e9-9d2e-132903d38260.png)
![image](https://user-images.githubusercontent.com/585569/51463728-ef662d80-1d9e-11e9-85ea-526d7638480f.png)

Am I doing something wrong?

**Comment by do4gr** [comment]
No, these were disabled in the Mongo connector in order to enable filters on relations. We might bring them back in the future, but for now we valued a quicker implementation of relational filters higher than `OR`, `NOT`.

I hope you can work around the lack of these for now?

**Comment by Mercurial** [comment]
Thanks for the answer @do4gr

**Comment by otrebu** [comment]
Hi @do4gr in practice how should be filtering ? Or should we wait until more work has been done?

**Comment by btotharye** [comment]
Curious how you accomplish this now with something like this before using Postgres?

```
query SEARCH_SNAKES_QUERY($searchTerm: String!) {
    snakes(
      where: {
        OR: [
          { name_contains: $searchTerm }
          { description_contains: $searchTerm }
        ]
      }
    ) {
      id
      image
      name
    }
  }
```

Is there some other way we are supposed to do this now in the Mongo connector world?

**Comment by do4gr** [comment]
The only option I could think of for the moment is to create two separate subscriptions for this.

**Comment by jhagu** [comment]
> No, these were disabled in the Mongo connector in order to enable filters on relations. We might bring them back in the future, but for now we valued a quicker implementation of relational filters higher than `OR`, `NOT`.
> 
> I hope you can work around the lack of these for now?

Hi @do4gr , any update about this topic?

**Comment by do4gr** [comment]
No, sorry we are currently focusing on the upcoming Prisma 2 release.

**Comment by jhagu** [comment]
> No, sorry we are currently focusing on the upcoming Prisma 2 release.

Thanks for your answer!

**Comment by sohailhaider** [comment]
Please provide any work around for OR in MongoDB, its one of the major query parts. Otherwise we have 4 products in prisma and have to move to `mongod` connector.

**Comment by dimaip** [comment]
It's a shame this is not mentioned in the docs: https://v1.prisma.io/docs/1.34/prisma-client/basic-data-access/reading-data-JAVASCRIPT-rsc2/#basic-filters-for-lists
Just lost half a day debugging this :(
