### ISSUE TITLE
 Mocking Prisma client for unit testing (typescript client)

### ISSUE THREAD

**Issue by durdenx** [prisma/prisma1#3898]
**Is your feature request related to a problem? Please describe.**
Is there a simple way to mock Prisma for unit testing? What are the best practices?

**Describe the solution you'd like**
For instance it would be neat to be able to create an instance of prisma client with dummy data in memory. Something like that:
```js
import { Prisma } from '@generated/prisma-client';
const db = new Prisma({
  mockData: {users: [{name: "myUser", password: "myUserPassword"}] }
  debug: config.isDev!,
});

export default db;
```
And we could inject that mocked Prisma instance in the context for unit test purspose and use it like a real Prisma.

**Describe alternatives you've considered**
At the moment we have to mock every prisma functions like this:
```js
const db = {
  users: args => ({name: "myUser", password: "myUserPassword"}),
  createUser: args => ({...args})
  $exists: {
      users: (args) => true
  }
 ...
}
```

**Comment by pantharshit00** [comment]
Hi @durdenx,

I don't think currently there is a solution baked into prisma for this so we can use this issue as a feature request for this.

That being said I use [this](https://github.com/javascript-af/javascript-af/blob/master/packages/backend/tests/repo.test.ts) approach currently to mock the prisma client and it works fine. Have a look 🙂

**Comment by durdenx** [comment]
Thanks @pantharshit00! It's a very useful link 👍

**Comment by steebchen** [comment]
This would be important for the Go client as well.

**Comment by arielalvarez88** [comment]
+1

**Comment by 13shubham** [comment]
Hi @pantharshit00  I am getting circular dependency error while mocking the prisma client, do you happen to know the solution?
