### ISSUE TITLE
Subscription with OR not working

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma1#3932]
**Describe the bug**
Subscription with OR not working

**To Reproduce**
https://github.com/divyenduz/prisma-3932

**Expected behavior**
Subscription with OR should work. 

**Versions (please complete the following information):**
 - Connector: `MySQL`
 - Prisma Server: `1.25.0`
 - `prisma` CLI: `1.25.3`
 - OS: `OS X Mojave`

**Comment by yodaheis** [comment]
Any updates on this one? prisma-binding does not seem to work with OR filters either in subscription

**Comment by solarsoft0** [comment]
what is the status of the issue, is it going to be treated any time soon
