### ISSUE TITLE
New Introspection feedback

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma1#3933]
# Prisma Introspection Feedback
When introspecting a Postgres database that has been created by Prisma for the following datamodel

```graphql
type User {
  id: ID! @unique
  name355: String! @db(name: "name300")
  car: Car
  houses: [House!]!
  scalarStringList: [String!]!
  scalarIntList: [Int!]!
}

type Car {
  id: ID! @unique
  name: String!
}

type House {
  id: ID! @unique
  windows: Int!
}
```

The output for Datamodel v1 looks like this:
```graphql
type Car {
  createdAt: DateTime!
  id: String!
  name: String!
  updatedAt: DateTime!
  User: [User!]! @relation(name: "_CarToUser")
}

type House {
  createdAt: DateTime!
  id: String!
  updatedAt: DateTime!
  User: [User!]! @relation(name: "_HouseToUser")
  windows: Int!
}

type User {
  Car: [Car!]! @relation(name: "_CarToUser")
  createdAt: DateTime!
  House: [House!]! @relation(name: "_HouseToUser")
  id: String!
  name355: String!
  updatedAt: DateTime!
}

type User_scalarIntList {
  # Multiple ID fields (compound indices) are not supported
  # Multiple ID fields (compound indices) are not supported
  # ID field must be called "id" in relational models.
  # nodeId: User!
  position: Int!
  value: Int!
}

type User_scalarStringList {
  # Multiple ID fields (compound indices) are not supported
  # Multiple ID fields (compound indices) are not supported
  # ID field must be called "id" in relational models.
  # nodeId: User!
  position: Int!
  value: String!
}
```

The output for Datamodel v1.1 looks like this:
```graphql
type Car {
  createdAt: DateTime! @createdAt
  id: String! @id
  name: String!
  updatedAt: DateTime! @updatedAt
  User: [User!]! @relation(name: "_CarToUser")
}

type House {
  createdAt: DateTime! @createdAt
  id: String! @id
  updatedAt: DateTime! @updatedAt
  User: [User!]! @relation(name: "_HouseToUser")
  windows: Int!
}

type User {
  Car: [Car!]! @relation(name: "_CarToUser")
  createdAt: DateTime! @createdAt
  House: [House!]! @relation(name: "_HouseToUser")
  id: String! @id
  name355: String!
  updatedAt: DateTime! @updatedAt
}

type User_scalarIntList {
  # Multiple ID fields (compound indices) are not supported
  # Multiple ID fields (compound indices) are not supported
  # nodeId: User! @id
  position: Int!
  value: Int!
}

type User_scalarStringList {
  # Multiple ID fields (compound indices) are not supported
  # Multiple ID fields (compound indices) are not supported
  # nodeId: User! @id
  position: Int!
  value: String!
}
```

While using `introspection.getNormalizedDatamodel`.

We, however, want to achieve an exact match between the input datamodel (which is in v1) and the output v1 datamodel.
For the v1 output also a few changes are necessary.

## Changes needed for v1 and v1.1
- In case you find an inline relation, the question is, wether you turn it into a 1 to 1 or 1 to n relation by default, if no reference datamodel is available. We would like to go with 1 to n for now. However, you could (stretch goal) find this out by performing a `GROUP BY` on the actual data, to find out, if there are instances with multiple mapping from one node to another. This is not required though, getting the "happy path" working is more important right now.
- Remove the @relation directive if there is only one relation from type A to B
- Turn `id: String!` into `id: ID!`
- Always add back relations, if not excluded from datamodel. We just discussed this default. It’s more conservative for the user as we don’t know which side of the relation the user actually wants to use.
- In Prisma datamodel v1 and probably also v1.1, we’re using Tables to represent scalar lists. This should be taken into account by the introspection. By the following conventions, the introspection should be able to deduce that we’re looking at a scalar list:
	- the name of the scalar list table is `${typeName}_${fieldName}`
	- it includes a compound index over `nodeId` and `position`
	- the type of the value is also the type of the scalar field. For the int list, it’s for example `Int!`

## Changes to be implemented by `getNormalizedDatamodel`

	- Preserve the order of types and fields
	- Remove `createdAt` and `updatedAt` from the types if they’re  not provided in the datamodel
	- If a relation is one sided in the datamodel, remove the other side
	- In v1, even “to 1” relations use a join table, when created by Prisma. This should be taken into account when using the `getNormalizedDatamodel` method, but is not possible to deduce just from the database structure
  

## Changes needed for v1

- Recognize id fields as `ID! @unique ` -> this should be done if a primary key is added

## An important difference  between v1 & v1.1: Defaults for Join Tables
The current behavior with v1 is, that we’re always creating a join table, even for 1 to 1 relations. However, the new default behavior in Datamodel v1.1 will  be, to create an inline relation for a 1 to 1 or 1 to n relation, if no further instructions are provided in the datamodel.
That new default is the equivalent of adding the directive `@relation(link: INLINE)`. In  other words, in the case,  that we should find a v1-style connection between two types, which is using a join table, but is just a to 1 relation, in the v1.1 datamodel we now have to explicitly add the `@relation(link: TABLE)` directive, as otherwise Prisma in datamodel v1.1 mode would delete the join table and turn it into an inline relation. For n to n relations, Prisma would, however, still create a join table as the default behavior.

**Comment by ejoebstl** [comment]
Thanks for the clear instructions, tim!

**Comment by ejoebstl** [comment]
I will update the following comment to reflect my progress on branch https://github.com/prisma/prisma/tree/tmp-3933:

Relational Introspector changes
 [x] Inline relations 1:1 vs 1:n (via unique constraint)
 [ ] Inline relations 1:1 vs 1:n (via data inspection)
 [x] Always add back relations for inline relations
 [x] Correctly handle scalar list tables
 [ ] Add unit test for scalar list table handling 
Postgres introspector changes
 [x] Turn string field with isId into ID field
Renderer changes
 [ ] Remove `@relation` if only one relation from A to B
 [ ] Make sorting in renderer optional by parameter
Normalizer changes
 [ ] db/pgColumn directive not picked up correctly
 [x] preserve order of fields and types in respect to ref datamodel
 [ ] Add unit tests for postgres introspection with existing ref datamodel
 [ ] hide createdAt/updatedAt if also hidden in the reference datamodel
 [ ] hide back relations if also hidden in the reference datamodel
 [ ] in v1: handle join tables for 1:n or 1:1 relations correclty, e.g. do not generate a n:n relation in this case
 [ ] migrating v1 to v2: In the case above, add a @relation(link: TABLE) directive.

**Comment by ejoebstl** [comment]
> In case you find an inline relation, the question is, wether you turn it into a 1 to 1 or 1 to n relation by default

Couldn't we use a unique constraint for detecting 1:1 inline relations?

**Comment by ejoebstl** [comment]
The introspection module should now properly respect existing schemas. Please give it a spin.
