### ISSUE TITLE
Log generated db queries

### ISSUE THREAD

**Issue by joshhopkins** [prisma/prisma1#3936]
**Is your feature request related to a problem? Please describe.**
I often would like to inspect the queries generated by Prisma. This is useful for inspecting efficiency or simply using the generated queries elsewhere.

**Describe the solution you'd like**
Prisma already provides a docker config param, `SLOW_QUERIES_LOGGING: 'true'` for logging incoming GraphQL queries. I propose an additional param, `GENERATED_QUERIES_LOGGING`, which when deployed will log generated queries.

**Describe alternatives you've considered**
Docker provides a way to grab containers logs, `docker logs -f [CONTAINER_ID]` but this log doesn't contain database queries for all images out of the box. It is possible to configure Postgres directly to log queries, though it's more complex than it should be.

**Comment by do4gr** [comment]
This is an interesting feature. I can see that being valuable also to decide when to use rawAccess. 

Until something like this is available you could change the docker image for the Postgres container to get easy access to logs for the generated queries. 

If you change the Postgres image in the docker-compose.yml from 
`image: postgres` to `image: timms/postgres-logging:10.3` the Postgres Docker container will automatically log all executed SQL queries.

**Comment by joshhopkins** [comment]
Good thinking, @do4gr. I'm trying this now, though image `timms/postgres-logging:10.3` doesn't seem to display SQL queries with the default settings. 

Logs from running `docker logs -f [CONTAINER_ID]` and running a query from Prisma.

`
2019-02-05 17:08:45.698 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-02-05 17:08:45.698 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2019-02-05 17:08:45.701 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-02-05 17:08:45.716 UTC [23] LOG:  database system was interrupted; last known up at 2019-02-05 17:00:27 UTC
2019-02-05 17:08:45.875 UTC [23] LOG:  database system was not properly shut down; automatic recovery in progress
2019-02-05 17:08:45.884 UTC [23] LOG:  redo starts at 0/C7D87C0
2019-02-05 17:08:45.884 UTC [23] LOG:  invalid record length at 0/C7D87F8: wanted 24, got 0
2019-02-05 17:08:45.884 UTC [23] LOG:  redo done at 0/C7D87C0
2019-02-05 17:08:45.910 UTC [1] LOG:  database system is ready to accept connections
`

**Comment by do4gr** [comment]
Hmm, that is weird, that is the image we use in dev for easy logging. Have you recreated with `docker-compose pull` followed by `docker-compose up -d` after changing your prisma.yml to make sure that the new image is running?

**Comment by joshhopkins** [comment]
@do4gr Yeah, image is definitely running and no problem querying it. It doesn't require any other config?

```
CONTAINER ID        IMAGE                         COMMAND                  CREATED              STATUS              PORTS                    NAMES
40aa2166d841        timms/postgres-logging:10.3   "docker-entrypoint.s…"   About a minute ago   Up About a minute   0.0.0.0:3001->5432/tcp   renko-bot_postgres_1
5ef9e62e2463        redis:latest                  "docker-entrypoint.s…"   About a minute ago   Up About a minute   0.0.0.0:6379->6379/tcp   renko-bot_redis_1
d00bde06082e        prismagraphql/prisma:1.25.7   "/bin/sh -c /app/sta…"   5 days ago           Up 3 days           0.0.0.0:4466->4466/tcp   renko-bot_prisma_1
```

**Comment by joshhopkins** [comment]
@do4gr Yeah, image is definitely running and no problem querying it. It doesn't require any other config?

```
CONTAINER ID        IMAGE                         COMMAND                  CREATED              STATUS              PORTS                    NAMES
40aa2166d841        timms/postgres-logging:10.3   "docker-entrypoint.s…"   About a minute ago   Up About a minute   0.0.0.0:3001->5432/tcp   app_postgres_1
5ef9e62e2463        redis:latest                  "docker-entrypoint.s…"   About a minute ago   Up About a minute   0.0.0.0:6379->6379/tcp   app_redis_1
d00bde06082e        prismagraphql/prisma:1.25.7   "/bin/sh -c /app/sta…"   5 days ago           Up 3 days           0.0.0.0:4466->4466/tcp   app_prisma_1
```

**Comment by endenwer** [comment]
@joshhopkins I had the same problem with logging. You just need to remove container and volumes. https://github.com/docker-library/postgres/issues/193#issuecomment-313803409

**Comment by joshhopkins** [comment]
That did it – thank you @endenwer!
