### ISSUE TITLE
Support aggregations in subscriptions

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [prisma/prisma1#3937]
**Is your feature request related to a problem? Please describe.**

I'm working on a some kind of dashboard that should display the current number of active ads in real time.

It's possible to use aggregations in queries to get it once:

```graphql
query totalAdvertsCount {
  advertsConnection {
    aggregate {
      count
    }
  }
}
```

But it's not possible to use aggregations in subscriptions to get/update it continuously in real time.

**Describe the solution you'd like**

Please add support of aggregations to subscriptions.

**Comment by Mercurial** [comment]
yes please! Subscription is the most powerful thing, and the more flexible queries the better!

**Comment by lancedouglas1** [comment]
From a real-time application perspective, without aggregations then the Subscription is not really a suitable solution, imho.  To be the right solution satisfying the one-way-app/flux/real-time patterns, it's not events, but changes, that need to be able to subscribed to.

MongoDB and MySQL real-time options are terrible examples of "something changed, here's everything...".

The best approach I've seen so far is OrientDB's LiveQuery.  I want to subscribe to a query, not an event.  The scope of event(s) can be inferred much easier from an incremental query-result-set update, than inferring the scope of a change from the simple events currently exposed in Prisma.

Currently I'm intending on using a completely separate subscriptions engine on the DB to expose a real-time perspective on deep-linked, complex aggregations, so I will have RPC via GraphQL and Prisma, but the actual websocket real-time nature will be served by an app subscribing to every possible change and pushing incremental diffs to subscribers.  At the moment, if I can use GraphQL and OrientDB, then I don't see a value to using Prisma, TBH (haven't tried yet, but no reason it wouldn't work relatively easily).
