### ISSUE TITLE
create, modify, and delete model, field, enum, relation using the management api on the local server?

### ISSUE THREAD

**Issue by LuHugo** [prisma/prisma1#3939]
Is it possible to create, modify, and delete model, field, enum, relation using the management api on the local server?

**Comment by pantharshit00** [comment]
Yes, 

The management API can perform changes to your datamodel and perform migrations on your server. The prisma cli uses this API to perform all of these tasks.

**Comment by LuHugo** [comment]
@pantharshit00 Maybe I didn't describe it more specifically. I know that using prisma cli can be deployed to a local server via datamodel. But I mean to create models, fields, etc. through the management API in http://localhost:4466/management. Is this possible?
