### ISSUE TITLE
some WHERE FILTER like node : { field_some: {} } aren't exposed but works in Typescript Client Lib

### ISSUE THREAD

**Issue by Mercurial** [prisma/prisma1#3942]
as the title says

![image](https://user-images.githubusercontent.com/585569/51844869-4a74c300-2351-11e9-8135-a8c479a949ca.png)

this works because I marked the object passed in node: as any, as if it was not exposed on purpose

![image](https://user-images.githubusercontent.com/585569/51844991-96c00300-2351-11e9-8f34-e84217f745dd.png)

if I remove the <any> keyword it simply rejects it because the type ConnectionSubscriptionWhereInput doesn't expose the user_some property

but does indeed work in the prisma graphql playground

![image](https://user-images.githubusercontent.com/585569/51845131-e1417f80-2351-11e9-8971-8b2e103efc02.png)

**Comment by pantharshit00** [comment]
This is related to mongo and datamodel v2 @divyenduz
