### ISSUE TITLE
Separate prisma-client runtime from code generator in `prisma-client-lib`

### ISSUE THREAD

**Issue by ziegfried** [prisma/prisma1#3949]
I would like to ship my graphql server with a `prisma-client-lib` that only contains the necessary runtime dependencies and not the codegen (which has some particularly heavy dependencies like prettier).

Context:
Code generated by prisma imports `prisma-client-lib` and is therefor a production dependency that needs to be included. Part of `prisma-client-lib` is a code generator, which is only used at build time, not at runtime (as far as I can tell).

**Comment by ahrbil** [comment]
I just started building my app for production and started to realize that this will be very helpful
