### ISSUE TITLE
Logging executed GraphQL Queries.

### ISSUE THREAD

**Issue by Industrial** [prisma/prisma1#4004]
**Is your feature request related to a problem? Please describe.**
Running a Prisma server I can't see logs of executed GraphQL queries. I run in Docker so I would love logs of this.

**Describe the solution you'd like**
An environment variable describing the log level the Prisma server should output at.

**Describe alternatives you've considered**
I don't see any.

**Comment by pantharshit00** [comment]
Hi @Industrial 

You can log all of the queries by using the `SLOW_LOGGING` feature.

Here is how you can do that: https://github.com/prisma/prisma/issues/3210#issuecomment-425485902

**Comment by Industrial** [comment]
Thanks a lot. I checked a lot of documentation but didn't find anything prior to making this ticket. I think it would be a good idea to add this to the documentation :-)

Cheers!

**Comment by Industrial** [comment]
@pantharshit00 Hi! I guess the remaining request for this ticket would be a feature request to document the behaviour of how to get all queries logged (described above) for others.

gr,

Tom
