### ISSUE TITLE
String arrays with MongoDB

### ISSUE THREAD

**Issue by rafakwolf** [prisma/prisma1#4017]
Hey guys... sorry I creating this issue again (related to https://github.com/prisma/prisma/issues/3975)
It was not clear to me :\

When I create a schema like this:

```
type MyTest {
  id: ID! @id
  arrayField: [String]
}
```
To add data to this `arrayField` I need to use like this ?

```
{
arrayField: {set: ['a', 'b', 'c']}
}
```
If i try to use like this:

```
{
arrayField: ['a', 'b', 'c']
}
```
I'm facing the error:

```
Reason: 'arrayField' Expected 'MyTestCreatearrayFieldInput', found not an object
```
Thanks!

**Comment by do4gr** [comment]
You can find the documentation around scalar lists here: 
https://www.prisma.io/docs/prisma-graphql-api/reference/mutations-qwe2/#scalar-list-mutations
