### ISSUE TITLE
Go client: prisma.Client.GraphQL() unmashal result into struct

### ISSUE THREAD

**Issue by andcan** [prisma/prisma1#4023]
When i run a custom query using GraphQL() I always have to use libraries like mitchellh/mapstructure to bind map values to a structure.
Adding a parameter to GraphQL() (resp interface{}) would allow to decode data directly into my struct because machinebox/graphql already supports decoding into struct

The alternative implementation would be
```
func (client *Client) GraphQL(ctx context.Context, query string, variables map[string]interface{}, resp interface{}) error {

	req := graphql.NewRequest(query)

	if client.Secret != "" {
		req.Header.Add("Authorization", "Bearer "+client.Secret)
	}

	for key, value := range variables {
		req.Var(key, value)
	}

	return client.GQLClient.Run(ctx, req, resp)
}
```

This implementation allows to work with both map and structure:
```
var m map[string]interface{}
err := client.GraphQL(ctx, query, vars, m)
```

```
var s MyStruct
err := client.GraphQL(ctx, query, vars, &s)
```

**Comment by dominikh** [comment]
I agree with this. In particular, it is in line with the API I had in mind for raw database queries.

This is a backwards incompatible change, but I suspect we're fine with that. @timsuchanek?

**Comment by chris-rock** [comment]
I use this method to expose the feature as this point:
```
// GraphQL Send a GraphQL operation request
func Run(client *prisma.Client, ctx context.Context, query string, variables map[string]interface{}, resp interface{}) error {
	req := graphql.NewRequest(query)

	if client.Secret != "" {
		req.Header.Add("Authorization", "Bearer "+client.Secret)
	}

	for key, value := range variables {
		req.Var(key, value)
	}

	if err := client.GQLClient.Run(ctx, req, &resp); err != nil {
		return err
	}
	return nil
}
```
we could easily integrate it into the core lib without a breaking change, as shown in https://github.com/prisma/prisma-client-lib-go/pull/5
