### ISSUE TITLE
query field against field

### ISSUE THREAD

**Issue by cesarve77** [prisma/prisma1#4051]
Sorry for my english.
I guess there is an issue open for this already, But I looked for it and I didnt find it. sorry again.
**Is your feature request related to a problem? Please describe.**
I need a query to compare values inside the record

In my sql would be `SELECT * FROM TableName where updatedAt=createdAt`
(it is just an example)

Actually I'm only able to compare against scalar values,

**Describe the solution you'd like**
See the query below, where "$value" is a field of products table
`
{
  query products(where: {cost_gte:"$value"}){
    id
    cost
    value
  }
}
`
**Describe alternatives you've considered**
I know there are a lot of thing more to considere, but that's the main idea

**Comment by pantharshit00** [comment]
Hi @cesarve77 

I don't think something like this is possible right now so we can use this issue as a feature request but you can fall back to `executeRaw` to use this functionality.

https://www.prisma.io/docs/prisma-graphql-api/reference/raw-database-access-qwe4/
