### ISSUE TITLE
Operation pre/post hooks

### ISSUE THREAD

**Issue by israelglar** [prisma/prisma1#4065]
It doesn't seem to be possible to set functions to fire before or after a mutation/query.
Some examples of that are
 - graphcool: https://www.graph.cool/docs/reference/functions/hooks-pa6guruhaf/
 - mongoose: https://mongoosejs.com/docs/middleware.html

What I would want is something close to these 2 libraries. Some use cases would be:
 - Before creating a user, set a property based on sent by the user (I can add this to my createUser resolver, but a User can also be created through a relation)
 - Validate an update mutation sent by the user before saving it to the database (same problem as previous)

It's possible to do a "after operation" hook using subscriptions, but I can't see any way to do the "before operation" logic for Update, Create, Delete

Thanks!

**Comment by meebix** [comment]
This would bring Prisma closer to a full ORM replacement. This is a fantastic project and I hope to continue seeing it evolve. Hooks into the CRUD actions for create, update, etc. are key to an ORM's functionality!
