### ISSUE TITLE
There can be only one variable named 'where'

### ISSUE THREAD

**Issue by RaeesBhatti** [prisma/prisma1#4066]
**Describe the bug**
Duplicate variable name for `$where` when querying an array field that references a type.
```
Error: GraphQL error: graphql: There can be only one variable named 'where'. (line 1, column 12):
query call($where: UserWhereInput, $where: CallWhereUniqueInput!) {
           ^
 (line 1, column 36):
query call($where: UserWhereInput, $where: CallWhereUniqueInput!) {
                                   ^
```

**To Reproduce**
example `datamodel.prisma`:
```
type User {
	id: ID! @unique
	credit: Int! @default(value: 0)
	createdAt: DateTime!
	updatedAt: DateTime!
}

type Call {
	id: ID! @unique
	source: User! @relation(name: "UserCalls")
	guests: [User!]! @relation(name: "UserCallsReceived")
	createdAt: DateTime!
	updatedAt: DateTime!
	endedAt: DateTime
}
```
example `prisma.yml`:
```
endpoint: "http://localhost:4466"
datamodel: datamodel.prisma
generate:
  - generator: go-client
    output: ./generated/prisma-client/
```
1. Create a new GoLang project
2. Run `prisma deploy`
3. Run `prisma generate`
4. Try to run the following with prisma generated packages imported:
```
u := getCurrentUser(ctx)
users, err := prismaClient.Call(prisma.CallWhereUniqueInput{ID: &callId}).Guests(&prisma.GuestsParamsExec{Where: &prisma.UserWhereInput{ID: &u.ID}}).Exec(ctx)
if err != nil {
	log.Fatal(err)
	return
}
```

**Expected behavior**
Run the query without error and return a slice of `User`s.

**Screenshots**

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.25
 - `prisma` CLI: `prisma/1.26.6 (darwin-x64) node-v8.12.0`
 - OS: macOS Mojave 10.14.3
 - other dependencies:

**Additional context**
It seems to me that this is a problem with query generation.

**Comment by helder-moreira** [comment]
@raeesbhatti 

I have created a PR to fix this:
https://github.com/prisma/prisma-client-lib-go/pull/7

While it is not merged, feel free to use my fork:
https://github.com/voluzi/prisma-client-lib-go
