### ISSUE TITLE
multiple interfaces syntax error with comma and ampersand

### ISSUE THREAD

**Issue by ibraheem-ghazi** [prisma/prisma1#4067]
**Describe the bug**
- Command line `prisma deploy` throw an error when using multiple interfaces separated by ampersand but accept syntax with multiple interfaces separated by comma
-  `prisma generate` is vice versa , accepting ampersand but throw syntax error on comma
- I used hooks to call generate after deploy

**To Reproduce**
1. create any type implements two interfaces
2. ensure that interfaces separated by  comma `,`
3. run `prisma deploy` => will success
4. run `prisma generate` => will fail
5. ensure that interfaces separated by  ampersand `&`
6. run `prisma deploy` => will fail
7. run `prisma generate` => will success

**Expected behavior**
both commands `generate` and `deploy should accept ampersand `&` syntax

**Screenshots**
-

**Versions:**
 - Connector: MySQL
 - Prisma Server: -
 - `prisma` CLI: prisma/1.26.6 (linux-x64) node-v8.10.0
 - OS: Elementary OS (based on ubuntu)
 - other dependencies: `prisma-client`, `prisma-binding`

**Additional context**
-

**Comment by pantharshit00** [comment]
I can reproduce this. Here is the reproduction: https://github.com/pantharshit00/prisma-issue-4067


1st bug condition
![image](https://user-images.githubusercontent.com/22195362/53038697-60365d80-34a3-11e9-9cba-347c3035545b.png)

2nd bug condition
![image](https://user-images.githubusercontent.com/22195362/53038762-85c36700-34a3-11e9-9be5-d64d68076bad.png)

**Comment by divyenduz** [comment]
The current datamodel represents the underlying schema declaratively using GraphQL SDL-like syntax and does not implement the whole spec.
