### ISSUE TITLE
Redirect prisma internal server error to client

### ISSUE THREAD

**Issue by israelglar** [prisma/prisma1#4073]
This issue relates to, but not exclusively, [Indexes and Constraints](https://github.com/prisma/prisma/issues/3405)

Right now it's not possible to create compound indexes with the mongo connector. My workaround to this is to create a direct connection to my dabatase and create the index on boot.

```ts
MongoClient.connect(
    config.connectionString,
    {useNewUrlParser: true},
    function(err: any, client: any) {
      const db = client.db('default_default');
      const Element = db.collection('Element');

      Element.createIndex(
        {
          fatherElement: 1,
          name: 1,
        },
        {unique: true},
      );

      client.close();
    },
  );
```

In my case I want to have unique pairs of `['fatherElement', 'name']` in my `Element` collection.

The index is created sucessfully and works, the problem is that when a document is create that fails the constraint, the error message I get is:

```ts
{
  "data": null,
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:cjsd1ktnt00ek09526vrfndow",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createElement"
      ],
      "requestId": "local:cjsd1ktnt00ek09526vrfndow"
    }
  ]
}
```

To know what happened I have to check my docker logs, but I need to warn the user that the pair `['fatherElement', 'name']` is not a valid one.

Since compound indexes are not supported yet, is there a way to not receive that "Whoops" error message, but receive the raw error message? So that I can parse it and create a useful message to my user?

Thanks!

**Comment by pantharshit00** [comment]
cc @do4gr

**Comment by do4gr** [comment]
A whoops indicates an exception that we do not have an internal error for yet. I can look into this next week and check whether this is a common error scenario that we can catch and output as a custom error.

**Comment by israelglar** [comment]
Great, thanks! I can contribute with a PR with some help. I already tried to understand the codebase, but it's a little complex, and I will need some time to understand what's is happening..

About the error, it would be great if for all the "Whoops" errors there was an option or a hidden property on the error that is sent to the prisma-client that was the raw error from the DB or something like that. 
Because if something like his happened again, the client could parse the raw error and handle that.

**Comment by do4gr** [comment]
Hey @israelglar, 

thanks for the offer to help, but at the moment I do not think we have the capacity to walk someone through the code base and accept such big contributions. I think it would be fairly involved to pipe the error all the way through.
