### ISSUE TITLE
MongoDb TTL Indexes

### ISSUE THREAD

**Issue by sandorTuranszky** [prisma/prisma1#4102]
Would be great to have [TTL Indexes](https://docs.mongodb.com/manual/core/index-ttl/#ttl-indexes) feature to set TTL for values so they get removed after some time automatically by MongoDB.

E.g. to ensure that the validation token is removed after 4 hours, It could look like that:

```
  type VerificationToken {
      token: String!
      createdAt: DateTime! @expires(value: "4h")
  }
```

E.g. in Mongoose it can be done this way:

```
var verificationTokenSchema = new Schema({
    _userId: {type: ObjectId, required: true},
    token: {type: String, required: true},
    createdAt: {type: Date, required: true, default: Date.now, expires: '4h'}
});
```

**Comment by bamne123** [comment]
Any update on this?
