### ISSUE TITLE
[1.27] Prisma deploy fails on citext field type

### ISSUE THREAD

**Issue by bartjuh4** [prisma/prisma1#4127]
**Describe the bug**
When executing prisma deploy it fails with error: `Encountered unknown SQL type 1111 with column postal_code. MColumn(MQName(public.addresses),postal_code,1111,"public"."citext",Some(2147483647),Some(0),10,Some(false),None,None,2147483647,4,Some(false),None,None,Some(false))`

**To Reproduce**
1. Add citext column to your table and add this to your prisma model
2. Run prisma deploy
3. Error occurs

**Versions:**
 - Connector: Postgres
 - Prisma Server: 1.27
 - prisma/1.11.1 (darwin-x64) node-v11.6.0

We downgraded to 1.26.6 and everything is working fine.

Full log available:
[prisma 1.27 error.txt](https://github.com/prisma/prisma/files/2930434/prisma.1.27.error.txt)

**Comment by pantharshit00** [comment]
Hi @Bartjuh4 

Currently, citext is not supported in prisma.

Also, are you using introspection or directly changing the column in a normal prisma instance deploy with postgres.

**Comment by epitaphmike** [comment]
@Bartjuh4 I am running into the same issue on 1.28 though for float8.
`message":"Encountered unknown SQL type float8 with column lat. IntrospectedColumn(lat,float8,null,true)"}}`

**Comment by divyenduz** [comment]
@epitaphmike : What command/operation do you run when you encounter this issue?

**Comment by epitaphmike** [comment]
> @epitaphmike : What command/operation do you run when you encounter this issue?

I was running `prisma deploy`

**Comment by divyenduz** [comment]
@epitaphmike : can you share a part of your Postgres schema as SQL that fails with `1.28` but not with `1.23` and create a separate issue [here](https://github.com/prisma/prisma/issues/new?template=bug_report.md) as this issue is different from `citext` issue and would need its own reproduction.

**Comment by Bartjuh4** [comment]
We are changing the columns directly. It's strange that citext is working fine on prisma 1.26 and 1.27 it went broken. Can you tell us when citext is supported?

**Comment by pantharshit00** [comment]
Hi @Bartjuh4 

Can you please tell me how were you able to even deploy this datamodel?

I was trying a reproduction and in the datamodel, we are explicitly marking that we are not supporting citext currently.

![image](https://user-images.githubusercontent.com/22195362/55409721-29fafc00-5580-11e9-951f-7904277eec92.png)

Also, please share your datamodel and maybe a SQL dump of your database(just the structure).

**Comment by Randy1Burrell** [comment]
I'm having this same issue. "message":"Encountered unknown SQL type float8 with column decimals.

**Comment by pantharshit00** [comment]
@Randy1Burrell Ref #4190

**Comment by bartjuh4** [comment]
> Hi @bartjuh4
> 
> Can you please tell me how were you able to even deploy this datamodel?
> 
> I was trying a reproduction and in the datamodel, we are explicitly marking that we are not supporting citext currently.
> 
> ![image](https://user-images.githubusercontent.com/22195362/55409721-29fafc00-5580-11e9-951f-7904277eec92.png)
> 
> Also, please share your datamodel and maybe a SQL dump of your database(just the structure).

We deployed with older version of prisma, then updated prisma server. After the update deploys didn't work anymore. At this moment we are still using Prisma 1.26.6 and everything works fine.
