### ISSUE TITLE
Single queries should be more powerful

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma1#4141]
**Is your feature request related to a problem? Please describe.**
Currently, single queries like .user can only query by unique fields:

![selection_999 1089](https://user-images.githubusercontent.com/5013932/53924635-1d68ae00-407d-11e9-8308-754e02374afa.jpg)

**Describe the solution you'd like**
I want to query by everything, not just unique IDs, just like I can do when querying multiple users:

![selection_999 1096](https://user-images.githubusercontent.com/5013932/53924715-6e78a200-407d-11e9-8730-bb022ede8871.jpg)

**Comment by pantharshit00** [comment]
Hi @steebchen 

I think it really doesn't make any sense to add non-unique value to a single query(any field annotated with `@unique` is available even if it is a relation).

Like if the field is non-unique there is absolutely a chance that we will get more than one match. That is why other non-unique fields are available via another method that will return an array. You can grab the first result if you are sure that one only such entity exist. In the upcoming API there will be `findOne` option that will do this for you.

**Comment by steebchen** [comment]
Makes sense. To rephrase, I was rather asking for a `findOne` method to only return a single result (not guaranteed by SQL, but guaranteed by my schema).
