### ISSUE TITLE
deleting a record with a list field of scalar values always returns empty array

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma1#4197]
**Describe the bug**
Deleting a record with a list field of scalar values always returns an empty array even though this should not be the case.

**To Reproduce**
Use the following datamodel and deploy a prisma instance using it:
```graphql
type Item {
    id: ID! @unique
    name: String!
    description: String
    price: Float!
    quantity: Int! @default(value: "1")
    images: [String!]!
}
```

Run the following and observe the output:
```js
const item = {
    name: 'Some item',
    description: 'Some description',
    price: 273.0,
    quantity: 20,
    images: [
        'http://lorempixel.com/640/480',
        'http://lorempixel.com/640/480/business',
        'http://lorempixel.com/640/480/nightlife',
    ],
}

const { id } = await prisma.createItem({ ...item, images: { set: item.images } })

const itemInDb = await prisma.item({ id })
console.log(itemInDb.images) // prints "['http://...', 'http://....', 'http://....']"

const deletedItem = await prisma.deleteItem({ id })
console.log(deletedItem.images) //  prints "[]"
```

**Expected behaviour**
Prisma should return the deleted object

**Screenshots**
Output of the script
![image](https://user-images.githubusercontent.com/22195362/54435487-9c817480-4756-11e9-9907-126ab6b24aec.png)

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.28.3
 - `prisma` CLI: 1.28.3
 - OS: MacOS 10.14.3

**Comment by do4gr** [comment]
This has to do with the way we are fetching previous values during deletes. We will not fetch related nodes or list values. We might change this at some point, but for now that is intended behaviour in order to speed up the mutation.
