### ISSUE TITLE
Prisma Docker Container should not attempt to connect to check-update.graph.cool

### ISSUE THREAD

**Issue by couchuser12345** [prisma/prisma1#4222]
Testing out / running Prisma via docker container I noticed within docker daemon logs that the container is attempting to connect to various domains in an attempt to what appears to check for updates.

Here is a sample of redacted logs:

```
March 19 18:20:05 <host.internal-domain.com> dockerd[6963]: time="2019-03-19T18:20:05.493123091Z" level=debug msg="Name to resolve: check-update.graph.cool"
...
March 19 18:20:05 <host.internal-domain.com> dockerd[6963]: time="2019-03-19T18:20:05.495748843Z" level=debug msg="Name to resolve: check-update.graph.cool.<internal-domain>.com"
```

Both of these fail since I'm testing this out locally on an isolated box that is running on an isolated network without proxy access to the internet. I was testing Prisma docker container with a local database configured / running via docker-compose.

I wouldn't have expected the running container to "phone home" like this under this scenario.

**Comment by pantharshit00** [comment]
@couchuser12345 

Can you please provide the version of prisma server that you are using

**Comment by pantharshit00** [comment]
@couchuser12345 

I investigated further into this and right now there is no way to disable these calls. In the future, we will allow you to disable this behaviour using a setting in the PRISMA_CONFIG.
