### ISSUE TITLE
Ordering by id_in

### ISSUE THREAD

**Issue by Corjen** [prisma/prisma1#4223]
Hi,

As requested by @schickling, a feature request describing ordering a list by the `id_in` input.

I have the following use case:

```graphQL
enum CompanyRelationType {
  LIKE
  DISLIKE
  WAITING
}

type CompanyRelation {
  type: CompanyRelationType!
  withCompanyId: ID!
  ownerId: ID!
  // etc..
}

type Company {
# ..etc.
relations: [CompanyRelation!]!
}

```  

Companies are able to relate to each other with a certain type (`LIKE`, `DISLIKE`, `WAITING`) where only one relation type can exist between company A & company B and vice versa.

What I want is to be able to retrieve a 'ranked' list, where I first get the companies that this users company hasn't ranked yet, and then the companies that have been ranked in a certain order. The first part is easy, e.g.:
```javascript
prisma.companies({where: {
  relations_none: {
    withCompanyId: "current users company id"
  }
})
```
Now comes the harder part because I would like to return the rest of the companies where the current users company does have a relation with in a specific order of the relation type, `WAITING` first, then `LIKED` and `DISLIKED` last.

I've tried two solutions, the first being just getting the 'no-relation' companies first, then the one with relation type WAITING, and so on. In the end merging them together and returning. This makes it hard (though not impossible) to paginate without skipping items I don't want to be skipped 😄 

The second solution should work better(I think :)) as it works like this:
```javascript
const relations = await prisma.companyRelations({
  where: {
    withCompanyId: "current users company id"
  },
  orderBy: 'type_DESC'
})
```

This gives me a list of relations in the exact order I want to return them, but I need the companies and not the companyRelation, so I need to do this:
```javascript
await prisma.companies({
  where: { id_in: relations.map(relation => relation.ownerId) },
})
```

This returns the companies in a different order then the order of the relations, which is the exact order I need. What would fix it for me is to be able to either: `orderdBy: id_in`, which would mean I still have to get all the relations as per the example above (which isn't a big issue), or be able to `orderBy: companyRelation_type_DESC` or something like that. I know there's an open PR for that last option.  

I hope any of this makes sense 😄 Perhaps I'm overthinking it and there's a better solution or model for my problem. It's probably an edge case pretty specific to my use case, but maybe there are more people who have the same problem.

We absolutely love working with Prisma BTW, thanks very much for a great product! 🎉

**Comment by mavilein** [comment]
Hey @Corjen ,

thanks for such a thorough writeup! 🙏 

May i know why you modeled `CompanyRelation` with fields of type `ID`? My intuition would be to model it like the following. In this case you would not need to do the `id_in` query.
```
type CompanyRelation {
  type: CompanyRelationType!
  withCompanyId: Company!
  ownerId: Company!
  // etc..
}
```

**Comment by Corjen** [comment]
Hi @mavilein,

Thanks for the quick reply! That does indeed make it easier to get the relations connected to a certain company, but still doesn't solve the issue of getting the companies without a relationship first, right?

In your solution, I would have to do something like: 
```javascript
const relations = await prisma.company({id: "my company id"}).relations()

const companiesWithNoRelation = await prisma.companies({where: { 
relations_none: {
   id_not_in: relations.map(relation => relation.id) } })
}
```

And to get the company of a relation, wouldn't I have to loop trough the entire connections list to get each company?
