### ISSUE TITLE
Change deploy timeout

### ISSUE THREAD

**Issue by telaoumatenyanis** [prisma/prisma1#4247]
**Is your feature request related to a problem? Please describe.**
I have to deploy a field on a table containing a lot of lines.

The deployment takes a lot of time (even by sending a ALTER TABLE query without Prisma) and the deploy timeouts.

**Describe the solution you'd like**
Give the ability to set the timeout

```
prisma deploy --timeout=10000
```

**Describe alternatives you've considered**
Timeout=0 may disable timeout. Otherwise a flag --no-timeout could be added.

**Comment by divyenduz** [comment]
Thanks for raising this feature request. Long running alter statements should ideally be done via a online schema migration tool like [https://github.com/github/gh-ost](https://github.com/github/gh-ost)

From Prisma's end, we already have a new datamodal v1.1 in latest beta (1.30.0-beta.3) ready to be tested: [https://github.com/prisma/prisma/issues/3408#issuecomment-475277466](https://github.com/prisma/prisma/issues/3408#issuecomment-475277466)

This datamodel also brings in active/passive unification [https://github.com/prisma/prisma/issues/3022](https://github.com/prisma/prisma/issues/3022)

Which means that now it is possible to do long running migrations using an external migration system and bring Prisma in sync with it.

I will still keep this issue open as a feature request for improving/exposing timeout.
