### ISSUE TITLE
Prisma Introspect generates invalid relation names

### ISSUE THREAD

**Issue by serranoarevalo** [prisma/prisma1#4315]
**Describe the bug**

I have introspected a Django PostgreSQL database with Prisma and the datamodel.prisma file that has been generated cannot be deployed because all the relation fields are not specifying a @relation  directive.

This is the error that I get

![Screen Shot 2019-04-05 at 9 31 28 AM](https://user-images.githubusercontent.com/3612017/55596907-0bfee880-5786-11e9-8bd9-4c6fddfceba5.png)

I'm using prisma@1.30

**Comment by mattdamon108** [comment]
I have exactly same problem, `prisma introspect` generates `datamodel-timetamps.prisma`, but it omits `@relation` directive at all.

![image](https://user-images.githubusercontent.com/36963424/55597657-9d238e80-5789-11e9-899a-cd2d6a6fa70f.png)

related to #3746 #4081 #4090

**Comment by pantharshit00** [comment]
Currently, there is an ongoing PR that will possibly fix this: https://github.com/prisma/prisma/pull/4304

We will try to merge it very soon. cc @ejoebstl

**Comment by timsuchanek** [comment]
Thanks a lot for reporting! Could you post the generated datamodel or give us a small subset of the datamodel that contains the troubling types?

**Comment by mattdamon108** [comment]
https://gist.github.com/mattdamon108/486eb4fb623f27d0e0de94a076e2b9d1
