### ISSUE TITLE
In Queries with empty array returns all entries

### ISSUE THREAD

**Issue by chris-rock** [prisma/prisma1#4324]
**Describe the bug**

I use the go prisma client to determine with an example query like:
```
	data, err := prismaClient.Todos(&prismaClient.TodosParams{
		Where: &prismaClient.TodosWhereInput{
			NameIn: []string{},
		},
	}).Exec(ctx)
```

Everything works correct if the array passed into NameIn is NOT empty. Once its empty, it returns ALL objects. From my understanding Prisma should return 0 objects if the In-Query is empty. 

**To Reproduce**

Use in query with empty array

**Expected behavior**

Instead of returning all objects, it should return 0 objects. It should behave similar to SQL In-Query logic.

**Screenshots**
n/a

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: 1.27
 - `prisma` CLI: n/a
 - OS: n/a 

**Additional context**

**Comment by matthewmueller** [comment]
Note: unassigning myself on things I'm not actively working on. I may pick this up in the future.
