### ISSUE TITLE
Set and create operations, order of execution  

### ISSUE THREAD

**Issue by AndreiBacescu** [prisma/prisma1#4325]
**Describe the bug**
The available operations don't execute in the specified order.

**To Reproduce**
In the attached image I have a set of available operations for an image field. I want to use **set** and **create** at the same time but it seems that **set** is always executed after **create**, no matter if the order is **create** and **set** or vice versa. 

**Expected behavior**
Execute operations in the specified order.

**Screenshots**
![6d09db0e54c035315b2efea966628b7c22cadc76](https://user-images.githubusercontent.com/17107914/55684666-7a92a080-5956-11e9-81d8-5ae3f5940e04.png)

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.25.0`
 - `prisma` CLI: `prisma/1.27.0 (windows-x64) node-v11.9.0`
 - OS: `Windows 10` 
 - other dependencies: `prisma-client`

**Comment by pantharshit00** [comment]
Hi @AndreiBacescu 

We really can't change the order of execution as it will break the existing systems that rely on that order. 

In this situation, you should perform two separate calls. That will ensure set is executed before create

**Comment by brunocascio** [comment]
@pantharshit00 Performing 2 separate calls is not transactional :/

**Comment by pantharshit00** [comment]
I am sorry but we really can't change the order here.
