### ISSUE TITLE
deleteMany happens after update or create

### ISSUE THREAD

**Issue by cesarve77** [prisma/prisma1#4327]
**Describe the bug**

For this model

```
type Family{
  id: ID! @unique
  surname: String!
  pets: [Pet!]!
}
type Pet{
  name: String!
  type: String!
}
```
I want to update pets with all new information in just one sentence

How there is no set for embebed types I have to delete all first and then create a new ones
(please correct me if I am wrong)

Then I need to run  deleteMany and create
But my problem is deleteMany is execute at the end, deleting de previous creation

**To Reproduce**

on the above model execute the following mutation:

```
mutation {
  updateFamily(
    data: {
      pets: { 
        deleteMany: [{}]
        create: [
          { name: "Rocky", type: "Dog" }
          { name: "Cooper", type: "Dog" }
        ]
      }
    }
    where: { id: "cjttntcvk02020718u28s67ra" }
  ){
    id
    username
    pets{
      name
      type
    }
}

```

**Expected behavior**

I hope my record be:

```
{
   id: "cjttntcvk02020718u28s67ra",
   surname: "Ramos",
   pets:[
      { name: "Rocky", type: "Dog" },
      { name: "Cooper", type: "Dog" }
  ]
}

```

But i get:

```
{
   id: "cjttntcvk02020718u28s67ra",
   surname: "Ramos",
   pets:[
  ]
}


```

**Screenshots**

**Versions (please complete the following information):**
 - Connector: `MySQL`
 - Prisma Server: 1.29
 - `prisma` CLI:   1.29.2 
 - OS: [`OS X Mojave 10.14.4 `] 

**Additional context**

One solution is run deleteMany before create or update

Other solution is create a "set" option which works like create but deleting previous records

**Comment by divyenduz** [comment]
Current workaround is mentioned in the additional context section, rewriting them here: 

- One solution is run deleteMany before create or update

- Other solution is create a "set" option which works like create but deleting previous records

**Comment by cesarve77** [comment]
> Current workaround is mentioned in the additional context section, rewriting them here:
> 
> * One solution is run deleteMany before create or update
> * Other solution is create a "set" option which works like create but deleting previous records

There is not a work arround.
```
 updateFamily(
    data: {
      pets: { 
        deleteMany: [{}]
        create: [
          { name: "Rocky", type: "Dog" }
          { name: "Cooper", type: "Dog" }
        ]
      }
    }
```
or 
```
 updateFamily(
    data: {
      pets: { 
        create: [
          { name: "Rocky", type: "Dog" }
          { name: "Cooper", type: "Dog" }
        ]
       deleteMany: [{}]
      }
    }
```
Always execute deleteMany first.

And there is not set option for embebed types.

thanks!

**Comment by cesarve77** [comment]
Do you have an estimate time for solve this?
Im working in a project and depend of this.

Thanks.

**Comment by divyenduz** [comment]
> One solution is run deleteMany before create or update

By this, I meant the following: 

```
updateFamily(
    data: {
      pets: { 
        deleteMany: [{}]
      }
    }

updateFamily(
    data: {
      pets: { 
        create: [
          { name: "Rocky", type: "Dog" }
          { name: "Cooper", type: "Dog" }
        ]
      }
    }
```

**Comment by cesarve77** [comment]
> P.S. This is a feature request I guess, not a bug as different use cases may want different order of execution.

I was trying to think about a real practical use case where you need to create first and delete immediately after, and I did not find any.

I don't know a bout the prisma code (i don't know scala), but it looks like an easy fix.
