### ISSUE TITLE
Use required arrays with non-null items?

### ISSUE THREAD

**Issue by LarsJK** [prisma/prisma1#4335]
**Is your feature request related to a problem? Please describe.**
It's a bit frustrating that we always have to check for null values in _get many entity queries_ and _to-many relationships_.

The return type of a "get many entity query" is `[T]!`, which means the items can be null (i.e `[T, null, T]`)

And for to-many relationships where the relationship is defined `[T!]!` the generated schema is`posts(...): [Post!]`, which means it could return null or an array of Post items.

**Describe the solution you'd like**
Usually when dealing with arrays empty state I prefer `[]` over `null` and `[null]`. Unless the null values have any semantic meaning I would prefer:

The return type of a "get many entity query" to be`[T!]!`
And for to-many relationships where the relationship is defined `[T!]!` the return type to be `[T!]!`.

**Describe alternatives you've considered**
Writing my own resolvers that filter `null` from `[T]!` values, and return `[]` instead of null for `[T!]` values.

**Additional context**

I realize this is how it is defined in OpenCrud and I have cross posted this in opencrud/opencrud#27, but I don't know if that repo is maintained (not much activity..). 

Example:

**Datamodel**
```graphql
type User {
  id: ID! @unique
  name: String!
  posts: [Post!]!
}

type Post {
  id: ID! @unique
  title: String!
}
```

**Generated Schema**
```graphql
type User implements Node {
  id: ID!
  name: String!
  posts(
    where: PostWhereInput
    orderBy: PostOrderByInput
    skip: Int
    after: String
    before: String
    first: Int
    last: Int
  ): [Post!] # Can we use `[Post!]!` here?
  postsConnection(
    where: PostWhereInput
    orderBy: PostOrderByInput
    skip: Int
    after: String
    before: String
    first: Int
    last: Int
  ): PostConnection!
}

type Post implements Node {
  id: ID!
  title: String!
}

type Query {
  users(
    where: UserWhereInput
    orderBy: UserOrderByInput
    skip: Int
    after: String
    before: String
    first: Int
    last: Int
  ): [User]! # Can we use `[User!]!` here?
  user(where: UserWhereUniqueInput!): User
}
```

**Comment by LarsJK** [comment]
This is still relevant. Can we keep it open?

**Comment by Renaud009** [comment]
Really interested in this feature too

**Comment by nadrane** [comment]
Same here. This feels pretty fundamental to me

**Comment by marcosfede** [comment]
any updates on this?

**Comment by otrsk** [comment]
I'd also be interested in this. I've seen that implementing the feature of `[Object!]!` was being considered in Dec 2017 here https://github.com/prisma/prisma/issues/1382 ...

**Comment by marcosfede** [comment]
please don't stale this

**Comment by KayBeSee** [comment]
+1 on this

**Comment by mikeporterdev** [comment]
Any update on this? This ticket has been open quite a while with no response

**Comment by mikeporterdev** [comment]
Please do not stale this ticket. Many of us are still waiting for any kind of update on this.
