### ISSUE TITLE
MySQL connector incorrectly allows UUID on non ID field

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma1#4344]
**Describe the bug**
MySQL does not support UUID but allows us to use that as a type on non ID fields but the deployment always rolls back

**To Reproduce**
1. Try to deploy the following datamodel on mysql:

```
type User {
  id: ID! @id
  name: String!
  zebra: UUID!
}
``` 

2. Try `deploy`, it rolls back

**Expected behavior**
Prisma server should reject this datamodel on any field that has type `UUID` for MySQL or Mongo

**Versions (please complete the following information):**
 - Connector: `MySQL`
 - Prisma Server: `1.30`
 - `prisma` CLI: `1.30`

**Additional context**
CLI should communicate rollbacks better https://github.com/prisma/prisma/issues/4351
Cloud should list rollbacks correctly https://github.com/prisma/prisma-cloud-feedback/issues/262

**Comment by chanlito** [comment]
Yes please show warning, alert or rollback deployment.
It showed me deployment successful but in fact it has problems. 

After I changed UUID to String and it works fine.
@divyenduz I think it's worth mentioning it somewhere in the docs that UUID can't be used with MySQL.
