### ISSUE TITLE
Failed to resolve FK constraint if reference is in on another schema

### ISSUE THREAD

**Issue by ephillipe** [prisma/prisma1#4348]
**Describe the bug**
I'm trying to **init** Prisma with an existing database. But I'm getting this error: _Failed to resolve FK constraint_  because the reference is in on another schema.

**To Reproduce**
```sh
$ prisma init
? Set up a new Prisma server or deploy to an existing server? Use existing database
? What kind of database do you want to deploy to? PostgreSQL
? Does your database contain existing data? Yes
? Enter database host erick.almeida.us-east-1.rds.amazonaws.com
? Enter database port 5432
? Enter database user erickalmeida
? Enter database password [hidden]
? Enter database name (the database includes the schema) karoo
? Use SSL? No
? Please select the schema you want to introspect public
Introspecting database public !
 ▸    Failed to resolve FK constraint usuario.idioma_fk -> idioma.id
```
```sql
    CONSTRAINT usuario_idioma_fk_fkey FOREIGN KEY (idioma_fk)
        REFERENCES i18n.idioma (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
```

**Expected behavior**
Introspection works fine

**Versions (please complete the following information):**
```sh
$ prisma --version
prisma/1.30.0 (linux-x64) node-v11.13.0
```

**Comment by divyenduz** [comment]
Prisma does not support multiple schemas yet in Postgres. I am tagging this as a feature request. The server would also need to implement this, fixing this just in introspection would be incomplete.

**Comment by blazestudios23** [comment]
I have the exact same issue on an AWS Aurora DB. There's are multiple schema on the same DB. I would like to be able to include most of those Schemas in my introspect to be honest, and they reference each other in some instances. 

It seems like this is a common issue for those of us that have huge-data sets.

No idea how to resolve this currently. 

Prisma 1.34.3
