### ISSUE TITLE
Feature Request: Support raw SQL as an input

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma1#4357]
**Is your feature request related to a problem? Please describe.**

Right now we communicate with the Prisma Engine using GraphQL queries and mutations.

We should open this up in the future to support other query languages like SQL. This would allow us to hook into many existing workflows by supporting SQL.

For example, by supporting a subset of ANSI SQL out of the box, [Redshift](https://aws.amazon.com/redshift/features/) is able to hook into existing tools like [psql](https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-from-psql.html) and [postico](https://eggerapps.at/postico/).

This feature would also allow us to accept SQL as an input from our own tools, like [Prisma Admin](https://www.prisma.io/admin/).

**Comment by pantharshit00** [comment]
@matthewmueller Are you aware of the rawAccess flag? We kinda already support this

https://www.prisma.io/docs/1.27/prisma-graphql-api/reference/raw-database-access-qwe4/
