### ISSUE TITLE
[Mongo] introspection asks for schema twice

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma1#4360]
**Describe the bug**
MongoDB asks for schema name even if it is provided in the connection string. 

**To Reproduce**
1. Run `prisma introspect` with a mongo db project

**Expected behavior**
It should ask for schema once, either ask for base mongo url and not whole mongo string OR parse the string ahead of time and optionally ask for schema. 

**Screenshots**
<img width="730" alt="CleanShot 2019-04-11 at 13 52 40@2x" src="https://user-images.githubusercontent.com/746482/55955930-07916e80-5c63-11e9-92c8-f0efbd97e98a.png">

**Versions (please complete the following information):**
 - Connector: `MongoDB`
 - Prisma Server: `1.30`
 - `prisma` CLI: `1.30`

**Comment by timsuchanek** [comment]
This is working as intended. MongoDB differentiates between an authentication database and a database it actually connects to https://docs.mongodb.com/manual/reference/connection-string/

**Comment by divyenduz** [comment]
Maybe we should support this only via the MongoDB connection string. 

Example 1: 
`mongodb://test:testpwd@localhost/test?authSource=admin`

Data DB: test
Auth DB: admin

Example 2: 
`mongodb://test:testpwd@localhost/test`

Data DB: test
Auth DB: test

This way, I can use only the connection string and my information of how to do this in native mongo.
