### ISSUE TITLE
Cannot use a null criteria in Prisma Client "where" filter for relations

### ISSUE THREAD

**Issue by aldarund** [prisma/prisma1#4377]
**Describe the bug**
There should be a possibility to filter for relation based if relation exist or not.  Its possible to filter items with non existing relations like this:

```
prisma.organizations({
      where: {
        consultancy : null
      }
    })
```
But its not possible to invert this filter e.g. filter only one where relation is set.. That`s really limiting..

**To Reproduce**
```
type Organization {
  id: ID! @id
  consultancy: Consultancy @relation(link: INLINE, name: "OrganizationConsultancy")
}

type Consultancy {
  id: ID! @id
}
```

**Expected behavior**

A way to filter out relation that is set. Something like

```
prisma.organizations({
      where: {
        consultancy_not : null
      }
    })
```

**Screenshots**

**Versions (please complete the following information):**
 - Connector:  `Postgres`
 - Prisma Server: 1.31-beta5
 - other dependencies: `prisma-client` 1.31-beta5

**Comment by pantharshit00** [comment]
@aldarund 

Can you please tell me which connector you are using(MongoDB or Postgres or MySQL)?

**Comment by aldarund** [comment]
@pantharshit00 oh, sorry, missed that. I`m using postgresql.

**Comment by ameistad** [comment]
Any updates on this?
