### ISSUE TITLE
Typo in directive name doesn't produce any errors

### ISSUE THREAD

**Issue by ashb** [prisma/prisma1#4410]
**Describe the bug**

I made a typo in the `onDelete` parameter to the relation directive:

```
  roleBindings: [RoleBinding!]! @relationship(onDelete: CASACADE)
```

This led to it not cascading deletes, nor to `prisma deploy` generating an error.

**To Reproduce**
1. Define relation with `@relationship(onDelete: CASACADE)`
2. Run `prisma deploy`

**Expected behavior**
An error should happen here as `CASACADE` is should not be a valid parameter for that directive.

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.25.0
 - `prisma` CLI: [e.g. `prisma/1.31.1 (darwin-x64) node-v11.7.0`
 - OS: [e.g. `Windows 10`, `OS X High Sierra`, `Ubuntu 16.04`] 
 - other dependencies: `prisma-client`, `prisma-binding`, etc. if applicable

**Additional context**

Log of output:

```
Prisma CLI version: prisma/1.31.1 (darwin-x64) node-v11.7.0
Prisma server version: 1.25.1

For further information, please read: http://bit.ly/prisma-cli-server-sync

Deploying service `myapp` to stage `default` to server `local` 146ms
Service is already up to date.

post-deploy:
-
- project database - No changes

Running graphql get-schema --project database...
project database - No changes
Running graphql get-schema --project database ✔
Generating schema 77ms
Saving Prisma GraphQL schema (SDL) at /Users/ash/code/myapp/src/lib/generated/schema/prisma.graphql
Saving Prisma Client (JavaScript) at /Users/ash/code/myapp/src/lib/generated/client
```

**Comment by ashb** [comment]
Okay I've just seem my error - the `@relationship` directive doesn't exist. But why didn't _that_ cause an error?

**Comment by pantharshit00** [comment]
Hi @ashb 

It is called `@relation` NOT `@relationship`. That is why there was no error.

**Comment by ashb** [comment]
So I can do `type Foo {id ID } @someDirectiveThatIJustMadeUp` and not get an error? That is... surprising to say the least.

**Comment by pantharshit00** [comment]
@ashb 

Well, that is the way we are parsing the datamodel using the graphql parser. Right now typos will have no effect as that directive is not implemented. 

We can use this issue as a feature request for better warnings :)
