### ISSUE TITLE
prisma deploy doesn't respect -e / --env-file option when used with -p / --project option

### ISSUE THREAD

**Issue by portpaw** [prisma/prisma1#4419]
**Describe the bug**

The `prisma deploy` command does not respect the `-e` / `--env-file` option when used with the `-p` / `--project` option.

**To Reproduce**

Create a `.env.production` file in your current working directory. For example:

```
PRISMA_SECRET="foo"
PRISMA_ENDPOINT="https://foo.com/foo/production"
```

Create a `prisma.production.yml` file in your current working directory. For example:

```
datamodel: datamodel.prisma
endpoint: ${env:PRISMA_ENDPOINT}
secret: ${env:PRISMA_SECRET}
```

Run `prisma deploy --project prisma.production.yml --env-file .env.production` and observe the output.

```
 ▸    [WARNING] in /path/to/foo/prisma.production.yml: A valid environment variable to
 ▸    satisfy the declaration 'env:PRISMA_ENDPOINT' could not be found.

 ▸    [WARNING] in /path/to/foo/prisma.production.yml: A valid environment variable to
 ▸    satisfy the declaration 'env:PRISMA_SECRET' could not be found.

 ▸    [WARNING] in /path/to/foo/prisma.production.yml: A valid environment variable to
 ▸    satisfy the declaration 'env:PRISMA_ENDPOINT' could not be found.

 ▸    [WARNING] in /path/to/foo/prisma.production.yml: A valid environment variable to
 ▸    satisfy the declaration 'env:PRISMA_SECRET' could not be found.
```

**Expected behavior**

The Prisma CLI respects the environment variables set in my dotenv file.

**Versions:**

```
$ prisma --version
Prisma CLI version: prisma/1.31.1 (darwin-x64) node-v11.13.0
Prisma server version: 1.31.0
```

**Comment by portpaw** [comment]
For what it's worth, here's my crazy workaround:

```
env $(cat .env.production | xargs) prisma deploy -p prisma.production.yml
```

**Comment by pantharshit00** [comment]
I can confirm this. This only happens if you use the `--project` and `--env-file` at the same time.

![image](https://user-images.githubusercontent.com/22195362/56473500-c16db380-6489-11e9-833e-277037f5c174.png)

**Comment by portpaw** [comment]
@pantharshit00 Updated the issue title to match that information.

**Comment by marcus-sa** [comment]
Is this gonna be fixed?
Because I just spend hours creating Bazel rules for Prisma and now I'm stuck because of this.

**Comment by Moro-Code** [comment]
Spent a while scratching my head with this same bug. Is there a timeline to fix this. Workaround is fine but means that only unix based systems will work with projects.
