### ISSUE TITLE
Querying by 1-1 relations for unique queries

### ISSUE THREAD

**Issue by aldarund** [prisma/prisma1#4430]
**Describe the bug**
1-1 relation unique quering/updating not possible

**To Reproduce**
```
type Consultancy {
  id: ID! @id
  organization: Organization @relation(name: "OrganizationConsultancy")
}
type Organization {
  id: ID! @id
  consultancy: Consultancy @relation(link: INLINE, name: "OrganizationConsultancy")
}

```
**Expected behavior**

And then it should be possible to make updates and queries to Consultancy based on organization id, since its 1-1 and so unique
E.g.

prisma.updateConsultancy({
      data: {
        ...
      },
      where: { organization: {id: id}
    })
Currently as i see its not possible. yes, its possible via many filtering, but its less than ideal, e.g. on update it wont return object, on retrieve it return array instead of single object etc

**Screenshots**

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: 1.31.1
 - other dependencies: `prisma-client`

**Additional context**

**Comment by pantharshit00** [comment]
Yes, right now it is not possible to create a unique relationship with the new datamodel syntax.

Thanks for reporting.
