### ISSUE TITLE
Can't filter data by scalaLists fields

### ISSUE THREAD

**Issue by bkstorm** [prisma/prisma1#4454]
**Describe the bug**
Prisma can't filter data by scalaLists fields.

**To Reproduce**
I'm using this repository to reproduce the error: [https://github.com/prisma/datamodel-v1.1-feedback.git](https://github.com/prisma/datamodel-v1.1-feedback.git)
1. Update `Category` type:
```
type Category @db(name: "category") {
  id: ID! @id
  name: String!
  posts: [Post!]! @relation(name: "PostToCategory")
  tags: [String!]! @scalarList(strategy: RELATION)
}
```
2. Run `prisma deploy`
3. Access `localhost:4466` to see the docs
4. `CategoryWhereInput` don't have any fields related to `tags`.

**Expected behavior**
`CategoryWhereInput` should have the fields below:
- `tags_some`
- `tags_every`
- `tags_none`

**Screenshots**
![Imgur](https://i.imgur.com/72At7g0.png)

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.31`
 - `prisma` CLI: `prisma/1.31.1 (darwin-x64) node-v11.10.0`
 - OS: `OS X Mojave`

**Comment by joshhopkins** [comment]
Just came up against this too. Any ETA on a fix?
