### ISSUE TITLE
Importing Prisma Binding in Vue throws Error @ Graceful Fs

### ISSUE THREAD

**Issue by crazymind** [prisma/prisma1#4481]
Prisma Binding seems to have problems with GracefulFS? Pretty easy to reproduce:

1. $ vue create my-project
2. $ npm install prisma-binding
3. In App.vue
`<script>
**import { Prisma } from 'prisma-binding'**

export default {
  name: 'app',
  components: {
    HelloWorld
  }
}
</script>`
4. npm run serve

<img width="812" alt="Image 2019-05-02 at 12 19 57 PM" src="https://user-images.githubusercontent.com/471377/57069361-b3fbc900-6cd4-11e9-8f0c-a8fab45da673.png">

Any suggestion how I can solve this error?

**Comment by pantharshit00** [comment]
@crazymind 

Prisma is NOT a frontend library. You will use it on the server and you can't run prisma in the browser.

So this is expected. Please read more about prisma here: https://www.prisma.io/docs/understand-prisma/prisma-introduction-what-why-how-j9ff/

**Comment by crazymind** [comment]
Thanks for your response @pantharshit00 .

But that's the whole idea behind Primsa, no? To provide a layer between frontend and backend?

Perhaps I didn't clarify my problem clearly:
How do I get the schema generated on the server, to make a query like this on the frontend:  
`const user = await prisma.user({ id })`

**Comment by pantharshit00** [comment]
@crazymind 

No, prisma is an ORM replacement. You will run prisma in your backend fetch data in a typesafe manner:

```js
app.get('/user/:id', async (req, res) => {
 const user = await prisma.user({ id: req.param.id });
 return user;
```

Rough architecture:

[Frontend] -> [Application Server(prisma client lives here)] -> [Prisma Server] -> [Database]
