### ISSUE TITLE
`prisma deploy` implicit generation fails if prisma.yml is in another directory

### ISSUE THREAD

**Issue by larrikinventures** [prisma/prisma1#4494]
**Describe the bug**
When specifying a custom `prisma.yml` with `-p subdir/prisma.yml`, it isn't respected for the implicit `prisma generate` that was added in #3579 

**To Reproduce**
1. move your `prisma.yml` and `datamodel.prisma` into a subdirectory `subdir`.
2. `prisma deploy -p subdir/prisma.yml`
3. See error after successful deploy, and client is not generated.

```bash
> prisma deploy -p subdir/prisma.yml

Deploying service `default` to stage `default` to server `local` 545ms

Changes:

  Blammo (Type)
  - Deleted type `Blammo`

Applying changes 1.1s
 ▸    Couldn’t find `prisma.yml` file. Are you in the right directory?

Get in touch if you need help: https://spectrum.chat/prisma
To get more detailed output, run $ export DEBUG="*"

Your Prisma endpoint is live:

  HTTP:  http://localhost:4466
  WS:    ws://localhost:4466

You can view & edit your data here:

  Prisma Admin: http://localhost:4466/_admin
```

**Expected behavior**
Implicit `prisma generate` respects `-p` option. If I run `prisma generate -p subdir/prisma.yml` it works as expected.

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.32.2`
 - `prisma` CLI: `prisma/1.32.2 (darwin-x64) node-v10.13.0`
 - OS: `OS X High Sierra`

**Comment by larrikinventures** [comment]
Workaround:

`prisma deploy -p subdir/prisma.yml --no-generate` and add a `post-deploy` to your `prisma.yml`:

```yml
hooks:
  post-deploy:
    - prisma generate -p subdir/prisma.yml
```

**Comment by pantharshit00** [comment]
Thanks for reporting 🙏 . I was able to reproduce this.
