### ISSUE TITLE
Columns with foreign keys ordered to reflect datamodel

### ISSUE THREAD

**Issue by joshhopkins** [prisma/prisma1#4495]
Not a massive issue, but it would be nice if the columns in SQL databases were ordered to reflect the datamodel. Currently all columns with foreign keys are ordered last in Postgres.

**Comment by pantharshit00** [comment]
Even though this is nice, I think is now possible as table order is not stored. It is cosmetic to human and the database doesn't care about it.


But I think you can order it the GUI using SQL statements:
```sql
-- This will return the default order that db server has
SELECT * from Users; 

-- This will return your custom order
SELECT col1, col2 FROM Users;
```
 
I think even though if this was possible the migration is not worth it.

**Comment by joshhopkins** [comment]
Yeah, you're probably right in that it's not worth the effort. It just happened that previous versions of Prisma created columns in the same order as fields defined in the data model.

[Postgres Wiki](http://wiki.postgresql.org/wiki/Alter_column_position):

> PostgreSQL currently defines column order based on the attnum column of the pg_attribute table. The only way to change column order is either by recreating the table, or by adding columns and rotating data until you reach the desired layout.

**Comment by pantharshit00** [comment]
I was referencing another SQL server which doesn't support this(sqlite) so that itself fundamentally increases the problem. 


cc @do4gr

**Comment by yassern** [comment]
i am getting some errors because of that wrong ordering, when i try import a csv file to my postgres database. i can resolve that but maybe that behavior should be documented as a postgres specific thing.
