### ISSUE TITLE
Using an *_every filter in a *WhereInput argument does not filter empty lists

### ISSUE THREAD

**Issue by shivamsonidev** [prisma/prisma1#4519]
**Describe the bug**

I have a data model with the following types:

```
type Event {
    id: ID!
    rsvps [Rsvp!]!
}

type Rsvp {
    id: ID!
    user: User!
}

type User {
    id: ID!
}
```

Prisma generates a query for me along with input types, so I can write:

```
 events(where:{
	rsvps_every: {
	    user: {
		id:"abcd"
	    }
    }
}) {
     id
     rsvps {
          id
          user {
               id
           }
     }
}
```

I would expect this to return a list of events that have *at least one* rsvp, where the rsvp has a user with an id matching "abcd"

However, when sending this query, we something like:

```
"events": [
      {
        "id": "1",
        "rsvps": []
      },
      {
        "id": "2",
        "rsvps": [
          {
            "id": "4",
            "user": {
              "id": "abcd"
            }
          }
        ]
      }
]
```

Even though an empty list of rsvps cannot match the requirement that `rsvps_every` has a user id equal to "abcd", it is returned with the query.

Is this expected behavior? Or a bug?

Where can I find the documentation for the *WhereInput and its expected behavior when applied to various queries?

**To Reproduce**
1. Create a Prisma server with the above schema
2. Seed with test data
3. Execute the query written above.

**Expected behavior**

I would expect the result of the above query to instead be:

```
"events": [
      {
        "id": "2",
        "rsvps": [
          {
            "id": "4",
            "user": {
              "id": "abcd"
            }
          }
        ]
      }
]
```

...where events with empty rsvps lists are excluded, since there is no user to match the `rsvps_every` clause

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.29.0`
 - `prisma` CLI: [e.g. `prisma/1.32.0 (darwin-x64) node-v8.11.1`]
 - OS: `OS X Sierra`

**Comment by divyenduz** [comment]
This is the current behavior. 

_every

true for an empty list

_some

false for an empty list

_none

true for an empty list

And

true for an empty list

Or

false for an empty list

Not

true for an empty list

**Comment by piebytwo** [comment]
@divyenduz 

I'm a bit confused. How would I construct a filter which, given a user id "abcd:

- returns only events where the rsvps of that event have rsvp.user.id === "abcd"
- does not return any events where the rsvps of that event are an empty list

?

**Comment by pantharshit00** [comment]
In my opnion, this is a bug. An empty list should not be returned as it doesn't have the matching condition.

Labelling this as a confirmed bug. cc @mavilein @do4gr

**Comment by carlgrundberg** [comment]
Just wanted to share how we solved this.
You can combine some and every, but its not very readable.

```
where: {
  # filter out exact match
  rsvps_every: {
    user: {
      id:"abcd"
    }
  }
  # filter out empty lists
  rsvps_some: {
    id_not: null
  }
}
```
