### ISSUE TITLE
Prisma does not create `WhereUniqueInput` when specifying @unique on relation

### ISSUE THREAD

**Issue by zwhitchcox** [prisma/prisma1#4531]
**Describe the bug**
When you create a type, e.g.

`type Admin {
  id: ID! @id
  user: User! @unique @relation(link: INLINE)
}`

with a user type

```
type User {
  id: ID! @id
  username: String! @unique
  admin: Admin
}
```

it only creates a where unique input with only the id field as being unique:

```
type AdminWhereUniqueInput {
   id: ID
}
```

**To Reproduce**
See above

**Expected behavior**
I would expect you to be able to query by the user as well as by the admin id, e.g.

```
query {
  admin {
    {user: {username: "myusername"}}
  }
}
```

**Screenshots**

Connector: MySql
Prisma Server: 1.32.2
prisma CLI: 1.32.2
OS: Windows 10

**Comment by ezeikel** [comment]
Having the same issue. Would expect to be able to filter on the unique related field but get an error that field does not exist on `XWhereUniqueInput` where `X` in my model.
