### ISSUE TITLE
"Syntax Error: Expected Name, found }" when having embedded type without scalar

### ISSUE THREAD

**Issue by macrozone** [prisma/prisma1#4535]
This has been reported often, but has not been fixed correctly:

given this datamodel:

```
type Address @embedded {
  address1: String
  address2: String
  phoneNumber: String
  zipCode: String
  city: String
}

type Coords @embedded {
  longitude: Float
  latitude: Float
}
type Location @embedded {
  coords: Coords
  address: Address
}

type Store {
  id: ID! @id
  name: String!
  location: Location!
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
}

```

will throw "Syntax Error: Expected Name, found }".

adding a dummy scalar to `Location` fixes the issue

**Versions (please complete the following information):**
 - Connector:MongoDB
 - Prisma Server: ? don't know how to get that
 - `prisma` CLI: prisma/1.32.2
 - OS: mac os

**Comment by philsch** [comment]
The same behaviour occurs if an embedded type only has list of scalars.

Example model:
```
type Meeting {
    id: ID! @id
    name: String
    persons: Persons
}

type Persons @embedded {
    invited: [String]
    attending: [String]
}
```

Generates a schema with syntax error when running `prisma generate` (or `prisma deploy`):

![Screenshot 2019-05-22 at 14 34 58](https://user-images.githubusercontent.com/5527838/58174870-27bf3f00-7c9f-11e9-8ed5-48ac44994936.png)

*Prisma CLI:* prisma/1.33.0 (darwin-x64) node-v8.14.1
Maybe relates to #1981
