### ISSUE TITLE
Still saving data on error on required relation

### ISSUE THREAD

**Issue by Hitabis** [prisma/prisma1#4558]
_Only tested on mongo connector_

When creating a new Element which has a required relation, but points to a missing one, prisma still saves the element, which produces an error on query.

Datamodel
```
type Item {
    id: ID! @id
    subitem: SubItem! @relation(link: INLINE)
}
type SubItem  {
    id: ID! @id
    name: String
}
```
then write an Item
```
mutation {
  createItem(data: { subitem: { connect: { id: "123" } } }) {
    id
  }
}
```
which gives this error as expected `"message": "You provided an ID that was not a valid MongoObjectId: 123",` **but still saves the item**

So when selecting:
```
query {
  items {
    id
    subitem {id}
  }
}
```
returns error (data can't be accessed anymore)
```
"errors": [
    {
      "message": "Cannot return null for non-nullable type (line 4, column 5):\n    subitem {\n    ^",
      "path": [
        "items",
        0,
        "subitem"
      ],
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ]
    }
  ]
```

**Expected behavior**
Not saving anything on error

**Versions:**
 - Connector:  `MongoDB`
 - Prisma Server: `1.33.0`
 - `prisma` CLI:  `prisma/1.33.0

**Comment by do4gr** [comment]
The Prisma SQL connectors provide the guarantee of transactional execution of nested mutations. This means that if any part of the nested mutations fail everything will be rolled back. 

The Mongo connector does not make use of transactions yet. Therefore if a part of a nested mutation fails every query Prisma generated and executed against the MongoDB already to execute that nested mutation will not be rolled back. Therefore there can be partial data in your DB. 

Enabling transactional execution on the Mongo connector solves this problem, but while it works in a prototype already we will need to invest more time to properly implement and test this before we can roll this out.

**Comment by gustawdaniel** [comment]
+ Any estimated time of release? 
+ Is there any temporary workaround for end users?

**Comment by gustawdaniel** [comment]
I fixed deleting `id: ID!` from `@embedded` relation.

**Comment by Hitabis** [comment]
Is there any chance to see the last inserted ids of prisma? So we could do some kind of manual rollback?
