### ISSUE TITLE
Creation fails for types with relational fields only

### ISSUE THREAD

**Issue by danielhopp** [prisma/prisma1#4584]
**Describe the bug**
Prisma server throws SQLSyntaxErrorException on "create" mutations for types with integer id and (one or more) *relations* to other types *only*.

**To Reproduce**
1. Deploy this `datamodel.prisma`:
```graphql
type A {
  id: Int! @id(strategy: SEQUENCE)
  name: String
}

type B {
  id: Int! @id(strategy: SEQUENCE)
  a: A @relation(name: "B2A", link: INLINE)
}
```
2. Create instance of A:
```graphql
mutation {
  createA(data: {name: "a1"}) {
    id
  }
}
```
Result:
```javascript
{
  "data": {
    "createA": {
      "id": 1
    }
  }
}
```
3. Create instance of B, connecting instance of A:
```graphql
mutation {
  createB(data: { a: { connect: { id: 1 } } }) {
    id
  }
}
```
Result:
```javascript
{
  "data": null,
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:cjw5fgf72006207384xyfzquj",
      "path": [
        "createB"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "requestId": "local:cjw5fgf72006207384xyfzquj"
    }
  ]
}
```

**Expected behavior**
Result:
```javascript
{
  "data": {
    "createB": {
      "id": 1
    }
  }
}
```

**Versions**
- Connector: `MySQL`
- Prisma Server: `1.33`, `1.35-alpha`
- `prisma` CLI: `prisma/1.33.0` `(darwin-x64) node-v11.12.0`
- OS: `macOS Mojave v10.14.5`

**Additional context**
- Issue occurs for types with integer id only
- Adding any (non-relational) field on referring type (e.g. "dummy: Boolean") fixes the issue

**Comment by pantharshit00** [comment]
Thanks for the detailed repro! I can confirm this.

This only happens in the MySQL connector. I was unable to reproduce this in Postgres connector.
