### ISSUE TITLE
If one defines field named "subCategories" for self relation, things break!

### ISSUE THREAD

**Issue by scientist1642** [prisma/prisma1#4612]
**Describe the bug**

**To Reproduce**
make a following datamodel 
```
type ItemCategory {
    id: ID! @id
    name: String!
    parent: ItemCategory @relation(name: "ItemRelation")
    subCategories: [ItemCategory!]! @relation(name: "ItemRelation")
}
```
Then add some data. i.e. 1 parent 1 child.
```query
{
  itemCategories {
    id
    name
    parent {
      name
    }
    subCategories{
      id
      name
    }
  }
}
```
<img src="https://i.ibb.co/9gDHy3y/scr.png" alt="scr" border="0" width="500">

Basically **if I replace subCategories with anything** else it works.

**Expected behavior**

**Versions (please complete the following information):**
 - Connector: `Postgres`, `MySQL` tried both 
 - Prisma Server: `1.34`, `1.35-btea`
 - `prisma` CLI: [e.g. `prisma/1.34.0 (darwin-x64) node-v10.4.0`]
 - OS: `OS X High Sierra`

**UPD**: Now I'm really really confused it works for some names like "children, childre" but not for others, I don't have anything else in my schema.

**Comment by pantharshit00** [comment]
You will need to name the relation different for parent and child:
```graphql
type ItemCategory {
    id: ID! @id
    name: String!
    parent: ItemCategory @relation(name: "ItemRelationParent")
    subCategories: [ItemCategory!]! @relation(name: "ItemRelationChild")
}
```

**Comment by scientist1642** [comment]
Well, that would make a separate table and if I add parent of A to be B. A won't appear in B's subcategories.

I made a [screencast ](https://youtu.be/xL1Z2ajH198)

**Comment by pantharshit00** [comment]
@scientist1642 You relation name is still `ParentRelation` which is causing this. Name it differently for parent and child in the `@relation` directive

**Comment by frandiox** [comment]
@scientist1642 I was struggling with this for long, but looks like you just need to handle them as 2 separate relations as @pantharshit00 says. You need to connect them manually:

```
updateItemCategory(
  { where: { id: 'parent' },
  { data: {
     subCategories: {
       create: [{
         ...,
         parent: { connect: { id: 'parent' } }
       }]
     }
  }}
```

**Comment by scientist1642** [comment]
@frandiox Strangely everything works so far as expected without 2 separate relations if I change the names.(like I showed in the recording above).  I haven't understood the reason so far, why should naming matter? I understand what @pantharshit00 says to just proceed with 2 relations. But it shows some mysterious inconsistency in the code.

**Comment by frandiox** [comment]
@scientist1642 wow, that's weird. I didn't see the second part of the video but that's the behavior I would expect -- without relying on 2 different relations. I wonder if I should rename my fields to parentX and childX to use this hidden feature or keep using 2 relations instead.

@pantharshit00 Any comments on the second part of the video? I'm not sure if using that hidden feature will bring some troubles later when upgrading to Prisma 2 or something...

**Comment by pantharshit00** [comment]
That is surely not expected. Marking as a bug.
