### ISSUE TITLE
Prisma deploy error

### ISSUE THREAD

**Issue by BucketLst** [prisma/prisma1#4724]
**Describe the bug**
I have got an error while deploying prisma. I have created a very simple table in relationship which couldn't end in success. I tried multiple sources and multiple table definitions but I always got this error "Duplicate column name".

Database:mysql

type Contact @db(name: "contact") {
  id: Int! @id
  info: String!
  type: String!
  customerid: Customer
}

type Customer @db(name: "customer") {
  id: Int! @id
  contact: [Contact]
  firstname: String!
  lastname: String!
}

Error:

  Contact (Type)
  + Created type `Contact`
  + Created field `id` of type `Int!`
  + Created field `info` of type `String!`
  + Created field `type` of type `String!`
  + Created field `customerid` of type `Customer`

  Customer (Type)
  + Created type `Customer`
  + Created field `id` of type `Int!`
  + Created field `contact` of type `[Contact!]!`
  + Created field `firstname` of type `String!`
  + Created field `lastname` of type `String!`

  ContactToCustomer (Relation)
  + Created an inline relation between `Contact` and `Customer` in the column `customerid` of table `Contact`

Applying changes 27.9s
▸    The Migration failed and has not been performed. This is very likely not a transient issue.
▸    java.sql.SQLSyntaxErrorException: (conn=924) Duplicate column name 'customerid'
▸    at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:163)
▸    at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:106)
▸    at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)
▸    at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224)
▸    at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
▸    at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
▸    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
▸    at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
▸    at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:21)
▸    at slick.jdbc.Invoker.first(Invoker.scala:30)
▸    at slick.jdbc.Invoker.first$(Invoker.scala:29)
▸    at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:15)
▸    at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
▸    at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
▸    at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
▸    at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
▸    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
▸    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
▸    at java.lang.Thread.run(Thread.java:748)
▸    Caused by: java.sql.SQLException: Duplicate column name 'customerid'
▸    Query is: ALTER TABLE `testdb`.`contact`
▸    ADD COLUMN `customerid` int NULL ,
▸    ADD FOREIGN KEY (`customerid`) REFERENCES `testdb`.`customer`(`id`) ON DELETE SET NULL;
▸   
▸    at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
▸    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)
▸    at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
▸    ... 15 more

▸   **Expected behavior**
Should deploy model

**Versions (please complete the following information):**
 - Connector: [`MySQL`]
 - Prisma Server: [e.g. `1.34.0`]
 - `prisma` CLI: [e.g. `prisma/1.34.1 (linux-x64) node-v10.16.0`]
 - OS: [`Ubuntu 18.04`]

**Comment by marcus-sa** [comment]
Same happens to me

**Comment by divyenduz** [comment]
If possible, can you please try to rename the `customerid` column to something else, say, `customer`?

```
type Contact @db(name: "contact") {
id: Int! @id
info: String!
type: String!
customer: Customer
}
```

**Comment by do4gr** [comment]
Do you have some more context for when this error is happening? I tried reproducing it on a fresh service and could not reproduce it.

**Comment by rgauny** [comment]
if you introspect and there is the foreign key between the 2 tables the relationship shows in the generated model but when deploying it it tries to regenerate "alter" the table and add the relationship...idk why it's trying to alter when migrations is set to false.

Query is: ALTER TABLE `portal_beta`.`publishers`
          ADD COLUMN `source_id` int NULL ,
          ADD FOREIGN KEY (`source_id`) REFERENCES `portal_beta`.`sources`(`id`) ON DELETE SET NULL;
        
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
        ... 15 more

**Comment by greguintow** [comment]
Same here

**Comment by JonathanStoye** [comment]
It actually doesn't matter whether there is a foreign key or not. For me it happens on any column. I chose a MySQL with existing data. Introspection and generation was fine but when deploying it seems to try to recreate the whole table even though the structure already exists in the db. When I use the same model to create a fresh db, it works fine.

**Comment by olek37** [comment]
I had the same problem
I found out that _'prisma delete'_ and _'prisma reset'_ don't seem to work very well with remote db servers.
To fix this error, i had to manually drop the schema on my pgsql server.
After that, _'prisma deploy'_ worked fine

**Comment by ruhankhandakar** [comment]
Prisma deploy error.
Refer this post . https://www.prisma.io/forum/t/postgres-deploy-bug-on-existing-database/6802
