### ISSUE TITLE
Prisma server does not recover from queueSize limit

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma1#4735]
**Describe the bug**
Prisma server has an internal queueSize of concurrent request it could be processing. When this limit is hit (with high enough QPS and slower queries), Prisma server starts to reject new queries that it receives. 

Once the load is reduced, Prisma server should "recover" and start accepting queries again. My hypothesis is that Prisma server is not able to recover once it hits the `queueSize` limit once. 

**To Reproduce**

Reduce the `queueSize` available in [1.32.1](https://github.com/prisma/prisma/releases/tag/1.32.1) and [1.30.3](https://github.com/prisma/prisma/releases/tag/1.30.3). The reproduction is in `1.29.2`, so, a high concurrency can be used to reproduce this issue there. 

**Expected behavior**
Once the load is reduced, Prisma server should "recover" and start accepting queries again. 

**Versions (please complete the following information):**
 - Connector: `MySQL`
 - Prisma Server: `1.29.2`
 - `prisma` CLI: `1.29.2`

**Comment by divyenduz** [comment]
This can happen for both the `managementApi` and the query execution API.

**Comment by pantharshit00** [comment]
It was extremely hard for me to crash the server but when I managed to do that server was able to recover easily.

I think the system you were testing might be out of memory

I can't confirm this.

**Comment by seawatts** [comment]
I'm also having this same issue. I'm running on a Heroku Hobby Dyno with 512MB of ram
