### ISSUE TITLE
Vulnerability in dependency `marked` should be upgraded

### ISSUE THREAD

**Issue by tianhuil** [prisma/prisma1#4738]
**Describe the bug**
There is a big with `marked<=0.6.2` that has been documented [elsewhere](https://github.com/raindigi/GraphqlType-API-Registration/issues/1) and is present here:

```
project@0.0.3
└─┬ prisma@1.34.1
  └─┬ prisma-cli-engine@1.34.1
    └── marked@0.5.2
```

**To Reproduce**
Run `npm i prisma`.

**Expected behavior**
We should upgrade `prisma-cli-engine` to use a later version of this package (0.6.2).

**Comment by tianhuil** [comment]
Proposed solution here: https://github.com/prisma/prisma/pull/4739

**Comment by pantharshit00** [comment]
See: https://github.com/prisma/prisma/pull/4739#issuecomment-514092030
