### ISSUE TITLE
Storing Phone Numbers more than 10 digits

### ISSUE THREAD

**Issue by developerk786** [prisma/prisma1#4756]
How to store long integers

I want to store users phone number which are **more than 10** digits in my case and when I tried using Long!

>  ✖ The field `phone` has the type `Long!` but there's no type or enum declaration with that name.

Then I found in this issue that Long is currently no implemented

> note: Long, BigInt, BigDecimal are currently not implemented by Prisma. http://sangria-graphql.org/learn/#scalar-types

[https://github.com/prisma/prisma/issues/1753](https://github.com/prisma/prisma/issues/1753)

then what am I supposed to do in this case except for storing phone numbers as a string?

**Comment by pantharshit00** [comment]
Right now you will indeed need to store them as bigints. 

We are going to consider this for Prisma 2 now.

**Comment by developerk786** [comment]
But there isn't such BigInt type according to this link https://www.prisma.io/docs/datamodel-and-migrations/datamodel-MYSQL-knul/

**Comment by pantharshit00** [comment]
Sorry I accidentally wrote bigints instead of strings 😓
