### ISSUE TITLE
Unique Cluster Support For The @unique Directive

### ISSUE THREAD

**Issue by zzyyzz1992** [prisma/prisma1#4761]
**Is your feature request related to a problem? Please describe.**
Lack of Functionality 
MySQL:
`CREATE UNIQUE CLUSTERED INDEX index_name ON TABLE (col1,col2)`
or
```
ALTER TABLE [dbo].[TABLE] ADD CONSTRAINT
UNIQUE_Table UNIQUE CLUSTERED
(
col1,
col2
) ON [PRIMARY]
```
**Describe the solution you'd like**
Make the @unique directive to support unique cluster.
For example, @unique(constraintKey: "MyUniqueConstraintKey")

**Additional context**
I'm transforming my project from TypeGraphQL to Prisma,
In TypeGraphQL, the unique cluster is defined like this:
```
const BRAND_UNIQUE_KEY = "BRAND_UNIQUE_KEY";

@Entity()
@Unique(BRAND_UNIQUE_KEY, ["name", "factory"])
export default class BaseInfo_Brand extends BaseEntity {
    @PrimaryGeneratedColumn("uuid")
    uuid: string;

    @Column()
    name: string;

    @ManyToOne(() => Relation_Factory)
    @JoinColumn()
    factory: Relation_Factory;

    // ...
}
```

**Comment by pantharshit00** [comment]
Hey @zzyyzz1992 

Can you please open this feature request for Prisma 2 as well? Most likely it will get implemented there.

**Comment by zzyyzz1992** [comment]
@pantharshit00 Sure, right away.
