### ISSUE TITLE
Configure plural names of models

### ISSUE THREAD

**Issue by schickling** [prisma/prisma1#48]
In some cases it might be needed to provide a custom plural name of a model.

Here is how it could be configured in the datamodel:

```graphql
type Person @plural(name: "People") {
  name: String!
}
```

**Comment by JustasPolis** [comment]
Hello, I'll add that it needs fixing, "Todo" becomes "Todoes" :).

**Comment by jvbianchi** [comment]
This is also important for localized model names

**Comment by alistairholt** [comment]
We're using GraphCMS which uses Prisma and this looks really bad in the interface. "WhatWeDoes", "HomepageIntroes" etc.

**Comment by rcy** [comment]
I ran into this today with a model `Person` that generates the query `persons`, but I would prefer `people`.

Is there a third party inflection library being used?

**Comment by alistairholt** [comment]
TBH I don't see why an external pluralisation library isn't being used. No doubt these problems have been solved countless times already. https://yarnpkg.com/en/package/pluralize, for example, with 17.8m downloads in the last 30 days:

```
pluralize('Todo') // Todos
pluralize('Person') // People
pluralize('WhatWeDo') // WhatWeDos
pluralize('HomepageIntro') // HomepageIntros
```

**Comment by cassiopagnoncelli** [comment]
Same problem here.

Postgraphile is a nice reference on how to solve this issue.

**Comment by biels** [comment]
Has this been solved? If not, which library or mechanism is being used by prisma to pluralize?

**Comment by pbassut** [comment]
Any updates?

**Comment by cassiopagnoncelli** [comment]
They know the issue and acknowledge most of the code in the wild is untested. Amending this issue would render a breaking change.

**Comment by jrvidotti** [comment]
Hey people, any updates on this?
