### ISSUE TITLE
Add {relation}Id field for inline relations

### ISSUE THREAD

**Issue by RinatGumarov** [prisma/prisma1#4826]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

I am worried about unnecessary joins when I only need to get field {relation}Id of model. E.g.
I have Author who has many books. In this case I want to easily access authorId field when querying book. 
```ts
(await prisma.book({id})).authorId
```

> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.

As this field exists on the table, it is possible to get it. And add those fields to generated types.

> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

Now I have to do something like this:
```ts
(await prisma.book({id})
    .$fragment('fragment Author on Book { ${bookFields} author { id } }'))
    .author.id
``` 
which loads author table too.

> **Additional context**
> Add any other context or screenshots about the feature request here.

**Comment by pantharshit00** [comment]
I guess this is now solved in Prisma 2 using the select/include API in photonjs.

https://github.com/prisma/prisma2/blob/a17359b6b32137db06972befd9cfbc7e1f9e7c2a/docs/relations.md#eager-loading

**Comment by RinatGumarov** [comment]
Can I eager load more than one level of nesting? e.g. Fetch some books with authors with their address?

**Comment by RinatGumarov** [comment]
> I guess this is now solved in Prisma 2 using the select/include API in photonjs.
> 
> https://github.com/prisma/prisma2/blob/a17359b6b32137db06972befd9cfbc7e1f9e7c2a/docs/relations.md#eager-loading

Can I eager load more than one level of nesting? e.g. Fetch some books with authors with their address?
