### ISSUE TITLE
ERROR: new row for relation 'table' violates check constraint "check_constraint"

### ISSUE THREAD

**Issue by marticrespi** [prisma/prisma1#4833]
**Describe the bug**
Mutations with custom check constraints don't work.

**To Reproduce**

I have this in my datamodel generated with prisma 1.34.5

````
type BookingL2BCost {
  id: Int! @id(strategy: SEQUENCE) @sequence(name: "BookingL2BCost_id_seq", initialValue: 1, allocationSize: 1)
  amount: Float!
  contract: Contract @relation(link: INLINE)
  createdAt: DateTime! @createdAt
  item: Item @relation(link: INLINE)
  maxbookings: Int
  maxl2b: Int
  minbookings: Int
  minl2b: Int
  updatedAt: DateTime! @updatedAt
}
````

And in my table I have this check constraint to avoid an insert with both relations empty, you have to insert one or other.

````
ALTER TABLE billing."BookingL2BCost" ADD CONSTRAINT chk_item_contract CHECK ((((contract IS NULL) AND (item IS NOT NULL)) OR ((contract IS NOT NULL) AND (item IS NULL))));
````

And I try to run the create mutation..

````
mutation testCreate($data: BookingL2BCostCreateInput!) {
  billing {
    createBookingL2BCost(data: $data) {
      id
      createdAt
    }
  }
}
````
Variables

````
{
  "data": {
    "minl2b": 1,
    "maxl2b": 2,
    "maxbookings": 2,
    "minbookings": 1,
    "amount": 5,
    "contract": {
      "connect": {
        "id": 75
      }
    }
}
}
````

But i get this error

````
ERROR: new row for relation "BookingL2BCost" violates check constraint "chk_item_contract"
````

But I'm sending the contract id FK (valid) in the variables.

If I remove the check constraint, from the database, it works.

Response:
````
{
  "data": {
    "billing": {
      "createBookingL2BCost": {
        "id": 14,
        "createdAt": "2019-08-21T11:08:47.972Z"
      }
    }
  }
}
````

Can't we have any constraint? 

**Versions (please complete the following information):**
 - Connector:  `Postgres`,
 - Prisma Server: `1.34.5`
 - `prisma` CLI: prisma/1.34.5 (windows-x64) node-v8.9.4,
 - OS: `Windows 10`,

**Comment by pantharshit00** [comment]
Actually Prisma Server is performing two queries here.

First to create the record without relation. Secondly, it updates the table to set the related item.

```
postgres_1  | 2019-08-23 18:58:49.726 UTC [49] STATEMENT:  update "default$default"."BookingL2BCost"
postgres_1  | 	set "contract" = $1
postgres_1  | 	where "default$default"."BookingL2BCost"."id" = $2`
```

So this basically violates the constraint as the data for the row is initially null.
