### ISSUE TITLE
1000 queued tasks returns internal server error

### ISSUE THREAD

**Issue by brunaaleixo** [prisma/prisma1#4912]
I was previously using the prisma demo server for my application. When I tried to query over 1000 nodes at once, I would receive internal server error. 

I have since deployed my prisma server using heroku where I am using the 2x dynos (memory is sufficient for queries with the amount of data I need). I have tried paginating my requests to query only 200 nodes at a time, but I eventually I still receive an internal server error. 

When searching the logs by the request id, I obtain the following exception:
"payload":{"exception":"java.util.concurrent.RejectedExecutionException: Task slick.basic.BasicBackend$DatabaseDef$$anon$3@60130a01 rejected from slick.util.AsyncExecutor$$anon$1$$anon$2@1d9a74d[Running, pool size = 1, active threads = 1, queued tasks = 1000, completed tasks = 339578]"

It seems as if when the server returns an internal server error when reaching 1000 queued tasks. However, since I am only querying 200 at a time, I can't understand how there are 1000 queued tasks. This behavior persists for a while, and I continue to receive internal server errors after that.

**Comment by brunaaleixo** [comment]
Also, when I run the same query on the playground I receive the data, not an error

**Comment by louisrli** [comment]
Also running into this issue with larger queries. Did you ever figure this out?

**Comment by lastmjs** [comment]
I have this issue sometimes as well. I'm even paginating my queries on my GraphQL application server, I only ask for 100 records at a time from the Prisma server. It doesn't seem to matter. If you have too many concurrent requests, these types of errors seem to get thrown. I have a rather beefy Prisma server running on AWS, but I still run into this issue. A possible solution seems to be to scale out horizontally, adding multiple Prisma servers. This is complicated by the fact that Prisma isn't designed to have multiple instances of itself running, as far as I know. I am using v1.21.1.

The whole Prisma docker instance is rather complicated, and it might be better to just move onto a new system, like Prisma 2 or something like graphback: https://github.com/aerogear/graphback

**Comment by ZainVirani** [comment]
We are running Prisma 1.25 in production and we get inconsistent performance querying ~1000 nodes. Occasionally these requests go through, usually they cannot. We've also noticed Prisma ramping up to max memory usage on our servers when our users are using our products normally (not the large requests I mentioned earlier). This issue occurs both on our cloud provider infrastructure as well as our local development machines, which causes us to think this is not a deployment or infrastructure related issue.
