### ISSUE TITLE
Prisma Demo Servers: The call to the group [username~service@stage] timed out.

### ISSUE THREAD

**Issue by zigzactly** [prisma/prisma1#5024]
Hi there i have been having problems running my queries on the demo servers lately. I am now getting the "The call to the group [username~service@stage] timed out.", while attempting to query data from:
- Graphql playground
- Prisma admin dashboard
- App resolvers
- Prisma export

I understand there is rate limiting and space limitations on the demo servers so ive been trying to extract my data via the above means. But no luck, getting timeouts everywhere.

Any ideas how else i can extract my data?

**Versions (please complete the following information):**
 - Connector:  `Postgres`
 - Prisma Server: `1.32.0 beta`
 - `prisma` CLI: `prisma/1.34.10`
 - OS: Archlinux

**Comment by ahrbil** [comment]
@zigzactly I'm also having this issue since yesterday.

**Comment by adhanji8** [comment]
Same issue
