### ISSUE TITLE
graphql-config is required by prisma-cli-engine but not listed as a dependency

### ISSUE THREAD

**Issue by pranaygp** [prisma/prisma1#5031]
**Describe the bug**
`graphql-config` is required by `prisma-cli-engine` but not listed as a dependency

This causes the `prisma` cli to completely break in yarn 2. For instance, when running `yarn dlx prisma generate`

**To Reproduce**
1. Setup a new yarn 2 project (https://yarnpkg.com/getting-started/install)
2. `cd` to the project directory
3. Run `yarn dlx prisma --help`

**Expected behavior**
The prisma help screen is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/1797812/75739132-b39fd600-5cc9-11ea-92c3-f32ae4b6d63d.png)

**Versions (please complete the following information):**
 - `prisma` CLI: `prisma/1.34.10 (darwin-x64) node-v13.8.0`
 - OS: `macOS Mojave`

**Comment by inlightmedia** [comment]
You can solve this by adding the following to the .yarnrc.yml under packageExtension. Seeing how they are not developing prisma1 anymore this is about all you'll be able to do to solve it.

```
packageExtensions
  "prisma-cli-engine@*":
    dependencies:
      graphql-config: "*"
```
