### ISSUE TITLE
prisma-1 client to use http proxy to work behind corporate firewalls

### ISSUE THREAD

**Issue by mannharleen** [prisma/prisma1#5038]
**Describe the bug**
Using "BatchedGraphQLClient" via "prisma-client-lib" does not allow configuring http(s) proxy. This means if the prisma server is running outside the corporate network, the prisma client will not be able to reach it. causing the following error:

```
FetchError: request to https://us1.prisma.sh/harleen-mann-2fba2c/hackernews-node/dev failed, reason: connect ECONNREFUSED 54.71.187.35:443
    at ClientRequest.<anonymous> (C:\Users\MannH\visualStudioProjects\hackernews-node\node_modules\node-fetch\lib\index.js:1393:11)
    at ClientRequest.emit (events.js:193:13)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

**To Reproduce**
1. Configure "javascript-client" to run behind a corporate proxy
2. Host the prisma server outside the network. e.g: on app.prisma.io
3. Start the graph server that talks to prisma server via this prisma client

**Expected behavior**
The prisma client should be able to use the HTTP_PROXY etc. env variables via an http agent to go via proxy and reach the prisma server

**Versions (please complete the following information):**
 - Prisma Server: app.prisma.io
 - others: 
    - graphql-yoga": "^1.18.3",
    - "prisma": "^1.34.10",
    - "prisma-client-lib": "^1.34.10"
 - OS: `Windows 8`

**My hardcoded solution that worked**
I could solve the error by setting the follwing in `...node_modules\prisma-client-lib\dist\Client.js`
```
this._client = new http_link_dataloader_1.BatchedGraphQLClient(endpoint, {
            headers: token
                ? {
                    Authorization: "Bearer " + token,
                }
                : {},
            agent: process.env.https_proxy 
            ? new HttpsProxyAgent(process.env.https_proxy ) // 'http://a:a@xxxxx:8080')
            : null
        });
```

**Permanent solution**
_I am happy to work on a legit solution (rather than hardcoding it) and submit a PR._
**Are the maintainers keen on adding this support?**

**Comment by mannharleen** [comment]
@nikolasburk @mavilein @do4gr @timsuchanek  - should I spend time to fix this and submit a PR?
(since v1 is in maintenance mode)

**Comment by nikolasburk** [comment]
Hey @mannharleen 👋 apologies for the delay! Unfortunately, we don't work on Prisma 1 any more (this includes merging PRs) unless it's about fixing super critical issues, so we won't be able to spend time reviewing a PR for this 😞

**Comment by mannharleen** [comment]
Thanks for your reply. no worries
