### ISSUE TITLE
Conflicting `gqlgen` interfaces

### ISSUE THREAD

**Issue by science-dude** [prisma/prisma1#5055]
I am starting at `Go` so I might be lacking few core concepts, however let me know what you think of this issue I am facing. One that might related to this issue https://github.com/prisma/prisma-client-go/issues/73, but I thought I will create another one to illustrate the problem. 

I am getting conflicts between generated interfaces on the `gqlgen` side and the `prisma` client. 

```
server/resolvers.go:47:2: cannot use []"github.com/science-dude/go-book-service/db/generated/prisma-client".Post value as type []*"github.com/science-dude/go-book-service/db/generated/prisma-client".Post in return argument
server/resolvers.go:53:2: cannot use []"github.com/science-dude/go-book-service/db/generated/prisma-client".Post value as type []*"github.com/science-dude/go-book-service/db/generated/prisma-client".Post in return argument
```

`server/resolvers.go` 
```golang
func (r *queryResolver) PublishedPosts(ctx context.Context) ([]*prisma.Post, error) {
	published := true
	return r.Prisma.Posts(&prisma.PostsParams{
		Where: &prisma.PostWhereInput{Published: &published},
	}).Exec(ctx)
}

func (r *queryResolver) PostsByUser(ctx context.Context, userID string) ([]*prisma.Post, error) {
	return r.Prisma.Posts(&prisma.PostsParams{
		Where: &prisma.PostWhereInput{
			Author: &prisma.UserWhereInput{
				ID: &userID,
			},
		},
	}).Exec(ctx)
}
```

It looks like the `generated.go` file from `gqlgen` has characterised this interface to be
```golang
type QueryResolver interface {
	PublishedPosts(ctx context.Context) ([]*prisma.Post, error)
	Post(ctx context.Context, postID string) (*prisma.Post, error)
	PostsByUser(ctx context.Context, userID string) ([]*prisma.Post, error)
}
```
This seem to conflict with prisma's return values for `Prisma.Posts`. Any idea how to fix it? Will it always be a problem?

`go.mod`
```golang
go 1.14

require (
	github.com/99designs/gqlgen v0.11.3
	github.com/dgrijalva/jwt-go v3.2.0+incompatible // indirect
	github.com/machinebox/graphql v0.2.2
	github.com/matryer/is v1.3.0 // indirect
	github.com/mitchellh/mapstructure v1.2.2 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/prisma/prisma-client-lib-go v0.0.0-20181017161110-68a1f9908416
	github.com/vektah/gqlparser/v2 v2.0.1
)
```

**Comment by steebchen** [comment]
I've transferred this issue to prisma/prisma, since you're using the old Go client; prisma-client-go is the new Go client.

For the actual issue, did you try importing your models from Prisma into gqlgen? Something like:

```
# gqlgen.yml
models:
  User:
    model: github.com/your/pkg/prisma/prisma.User
```

Then gqlgen uses the Prisma model instead of generating its own model.

**Comment by steebchen** [comment]
@science-dude Can you try setting `omit_slice_element_pointers: false` in gqlgen's yaml config? That should make gqlgen resolvers compatible with prisma.
