### ISSUE TITLE
BIG SECURITY BUG: Return all when undefined is passed

### ISSUE THREAD

**Issue by Riseley** [prisma/prisma1#5065]
**Describe the bug**
Return all when undefined is passed. Using Yoga, this step is not reproduced in Playground, however. Maybe it is a Yoga's problem, maybe it is Prisma's, but this is a huge security risk.

**To Reproduce**
```
return await ctx.db.query.users(
      {
        where: {
          user: {
            id: *undefined*,
          },
        },
      },
      `{ password leakedInformationHere}`
    );
```

**Expected behavior**
It shouldn't return anything.

**Screenshots**
None

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.34.0`
 - `prisma` CLI: `1.34.0`
 - Yoga: `1.18.3`

**Additional context**
Cross-posting to Prisma 2 too because `prisma1` is abandoned.

**Comment by pantharshit00** [comment]
https://github.com/prisma/prisma1/issues/5066#issuecomment-609837706
