### ISSUE TITLE
prisma-yml: ajv Vulnerability

### ISSUE THREAD

**Issue by andrewmcgivery** [prisma/prisma1#5100]
**Describe the bug**
A high severity security issue has been found and disclosed as of July 16 in the `ajv` package in versions < 6.12.3.

see: https://snyk.io/vuln/SNYK-JS-AJV-584908

**To Reproduce**
-Install prisma1

**Expected behavior**
prisma should not have any vulnerabilities.

**Versions (please complete the following information):**
Affecting current versions of prisma-yml

**Additional context**
prisma-yml currently uses version 5 of `ajv`. Upgrading locally breaks the unit test because downstream package `prisma-json-schema` needs to be updated to use an updated schema (`http://json-schema.org/draft-07/schema#`). Once this is updated, the unit tests pass with the latest version of `ajv` installed.

![image](https://user-images.githubusercontent.com/4482878/87833954-2b286900-c857-11ea-929d-e2933716205b.png)
![image](https://user-images.githubusercontent.com/4482878/87833969-37acc180-c857-11ea-94b4-510fb488e3c4.png)
![image](https://user-images.githubusercontent.com/4482878/87833983-41cec000-c857-11ea-9d1b-b4a4dca376e5.png)

I could submit merges for this but would need support from owners of this repo and prisma-json-schema to get these merged in.

**Comment by andrewmcgivery** [comment]
Pull request opened in prisma-json-schema to support this.

https://github.com/prisma/prisma-json-schema/pull/6

**Comment by andrewmcgivery** [comment]
Tagging @nikolasburk to try to get some attention to this. :)

**Comment by JensMadsen** [comment]
any news ?

**Comment by andrewmcgivery** [comment]
@JensMadsen graphql-tools no longer uses prisma-yml/prisma-loader because of the lack of maintenance of this library.

**Comment by JensMadsen** [comment]
@andrewmcgivery is it fixed or is prisma 1 still vulnerable?
