### ISSUE TITLE
Vulnerability updates

### ISSUE THREAD

**Issue by behivetech** [prisma/prisma1#5101]
**Describe the bug**
Could you please make the proper updates to your libraries to remove the security vulnerabilities that are part of this package. The libraries in question are `marked` and `sync-exec`. There still isn't a patch for `sync-exec`, but there is for `marked`.

**Comment by JensMadsen** [comment]
Please take this serious :-) We are getting several vulnerability warnings originating from the packages used in Prisma 1. We went with graphcool and are now stuck for while with prisma 1 so please :-)
