### ISSUE TITLE
Docs for Prisma1 break when searching

### ISSUE THREAD

**Issue by armaandh** [prisma/prisma1#5107]
## Bug description

When visiting the https://v1.prisma.io/tutorials/ docs, typing in the Search For... box generated: "An unexpected error has occured". 

## Expected behavior

Expect to be able to see information relevant to search query filtered out.

## Prisma information

n/a

## Environment & setup

Browser: Chrome 84.0.4147.105
OS: MacOS Catalina

**Comment by janpio** [comment]
Can you post a screenshot of waht you are seeing? Search works for me.

**Comment by armaandh** [comment]
Sorry, it's actually in the input box: "Filter tutorials by":
![image](https://user-images.githubusercontent.com/8894156/91363372-5c2e7e80-e7b1-11ea-894b-0b3b76597e38.png)
I don't get the issue in 1.34 docs link you sent because there is no: "Filter tutorials by" link
