### ISSUE TITLE
Vertical scaling

### ISSUE THREAD

**Issue by peterrogov** [prisma/prisma1#5124]
The current documentation does not explain clearly how to achieve vertical scaling. From what I understand so far, prisma v1 with docker deployment only runs one worker process effectively utilizing only one CPU core / thread. This is also mention here (https://github.com/prisma/prisma1/issues/2850) and it appears that instead of increasing the number of parallel workers (if that is at all possible) one must configure a cluster and use a PubSub mechanism to allow for worker nodes synchronization.

However, there is very little information on how to setup such cluster. It seems that one should use a different docker image (prisma-prod instead of prisma), though not sure if that is still true. You should also configure RabbitMQ connection for PubSub but my own attempts to try to do so have failed. 

Could someone please share more information on how to configure scaling with prisma v1 and probably include that in documentation? 

I could assist with a PR to documentation and make some sort of a guide with key points but first I need to figure it out myself.

**Comment by grimunit** [comment]
@peterrogov Did you ever end up getting your scaling solution figured out? I'm attempting to do the RabbitMQ setup mentioned in this comment by @mavilein https://github.com/prisma/prisma1/issues/2850#issuecomment-409868271. I'm curious if anyone has been successful in doing this approach without having to move over to Prisma 2 or using Kubernetes instead, which seems to be what most people ended up doing.

**Comment by peterrogov** [comment]
@grimunit like many other people I ended up migrating to prisma 2 for this and other reasons. I never managed to setup cluster correctly though it's like I tried really hard.
