### ISSUE TITLE
Prisma1 with Apple M1

### ISSUE THREAD

**Issue by ruskiballer** [prisma/prisma1#5162]
I want to use a Macbook Air M1 in future for the dev tasks at work, but they are using prisma1 with docker. Therefore we're using prismagraphql/prisma which was last updated 2 years ago.
When running docker-compose up I'm getting: 
```
prisma   | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
prisma   | /app/start.sh: line 4:    13 Segmentation fault      /app/bin/prisma-local
```
and the container restarts. 
I can't fix this, do you have a solution for that? I've tried setting platform in docker-compose.yml but this didn't changed anything.

**To Reproduce**
Using a M1 macbook try to create a prismagraphql/prisma container.

**Expected behavior**
Works via emulation or natively.

**Screenshots**
No Screenshots

**Versions (please complete the following information):**
 - Connector: Postgres
- Image: prismagraphql/prisma:1.34.10

**Additional context**
If I don't get this working I need to send the laptop back which will be very sad because the performance is incredible.

**Comment by jperelli** [comment]
You can find more info upstream https://github.com/docker/for-mac/issues/5123

**Comment by santiagorp** [comment]
@ruskiballer I managed to run prisma1 on docker in Mac without issues with the most recent version of docker. However prisma deploy fails in my case. Did you manage to make it work?

**Comment by laeijebor** [comment]
@santiagorp that's great - did you simply run your Docker Compose on the M1 Mac and everything ran as expected? Or did you change any config to get it to run properly?

**Comment by JorgenRe1** [comment]
Got prisma1 to run on docker, however requests are somewhat slow and eventually it just crashes even with plenty ram. More the reason to speed up migration away from prisma1.

**Comment by gopherine** [comment]
you can run it with minikube ... locally ... it works but it takes more resources ... and you will have to make a burstable container. basically exclude readiness and liveliness probe check.
