### ISSUE TITLE
Auto-completion support

### ISSUE THREAD

**Issue by schickling** [prisma/prisma1#614]
<a href="https://github.com/schickling"><img src="https://avatars2.githubusercontent.com/u/1567498?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [schickling](https://github.com/schickling)**
_Sunday Jun 11, 2017 at 11:04 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/92_

----

Packages like `tabtab` are great to implement auto complete functionality: https://github.com/mklabs/node-tabtab

**Comment by kbrandwijk** [comment]
For clink/cmder, I have created a completions file (compatible with the latest CLI version): https://gist.github.com/kbrandwijk/ea94cc9f7a676a9adde8c4179db6f634.

I would also put it somewhere in this repo, just tell me where...
