### ISSUE TITLE
Order by related fields

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#95]
Example: a User has many Posts. Should be possible to order the Posts by User name.

Maybe:

```graphql
query {
  allPosts(orderByRelated: [user_name_ASC]) {
    id
  }
}
```

**Comment by CameronK** [comment]
This would be a lifesaver!

**Comment by edtsech** [comment]
@marktani any workaround we can use for the time being?

**Comment by marktani** [comment]
The best workaround I'm aware of, is to order items client side 🙂

**Comment by shanecav** [comment]
It would be great to be able to order by "to-many" related fields as well (by the count of related items).

For example, to get a list of the top 10 most voted-for links:

```
query {
  allLinks(first: 10, orderBy: votes_DESC) {
    id
    url
    description
    _votesMeta {
      count
    }
  }
}
```

Currently, to get that list you'd have to query for every Link and then sort/slice it on the client, which is potentially a ton of overfetching.

**Comment by kenyk7** [comment]
Another use case would be:

```graphql
query {
  allPosts (
  orderBy: {
    _likedPostsMeta: {
      count: DESC
    }
  }
  ) {
    id
    title
    content
    _likedPostsMeta{
      count
    }
  }
}
```

**Comment by kenyk7** [comment]
A question for when they plan to add this improvement?

**Comment by studentIvan** [comment]
+1 for this

**Comment by jeromeky** [comment]
+1

**Comment by danstepanov** [comment]
+1

**Comment by panzupa** [comment]
I see a lot of 👍 
Dear GraphCool when do you plan to implement that?

**Comment by martinsura** [comment]
Must-have feature!

**Comment by danielrasmuson** [comment]
In my case this table will have thousands of rows. My users won't be able to sort the table by "createdBy" or "dataset" until this feature lands.

<img width="995" alt="screen shot 2018-02-24 at 11 47 25 am" src="https://user-images.githubusercontent.com/4013767/36634387-88405428-1958-11e8-8ca4-b9789d093daf.png">

**Comment by studentIvan** [comment]
@danielrasmuson you can create some sortable index just as temporary solution :)

**Comment by PascalSenn** [comment]
Have a look at #62 
This would solve the issues:
```graphql
query{
  servers(
  orderBy: {
    active: DESC
    assetNumber: ASC
    customer: {
        name:ASC 
   }
  }
  ) {
    id
    active
    assetNumber
    customer {
         name
    }
  }
}
```

**Comment by harrisrobin** [comment]
+1

**Comment by iyeremuk** [comment]
+1

**Comment by mcmar** [comment]
Echoing what @PascalSenn said, but updating `orderBy` to take an array. Arrays have implicit positioning. Objects aren't guaranteed that.
Additionally, every related ordering statement must also take an array, so that we can use multiple sort statements on a related field.
```
query {
  servers(
    orderBy: [{
      active: DESC
    }, {
      assetNumber: ASC
    }, {
      customer: [{
        name: ASC 
      }]
    }]
  ) {
    id
    active
    assetNumber
    customer {
      name
    }
  }
}
```

**Comment by sorenbs** [comment]
This continues to be an important feature for us. I'll update this issue when we have a concrete timeframe. See also [this explanation](https://github.com/prisma/prisma/issues/62#issuecomment-438664572) for why we were unable to ship this feature in Q3 as planned.

@mcmar - I like how your proposal is more powerful than the originally proposed syntax. At the same time I am concerned about the added syntactic complexity compared to the original proposal.
Another consideration is that this syntax would require a breaking change, which might not be worth it for this extra expressiveness.

**Comment by mcmar** [comment]
@sorenbs If you're switching `orderBy` from `FooOrderByInput` to `[FooOrderByInput!]`, wouldn't that be a breaking change anyway? I've noticed there's some magic in my generator that turns `create: [FooCreateWithoutBarInput!]` into `create?: FooCreateWithoutBarInput[] | FooCreateWithoutBarInput` and allows me to actually query with a single `FooCreateWithoutBarInput` even though the schema says otherwise. Maybe you can pull some similar wizardry here?

**Comment by sorenbs** [comment]
@mcmar - see the [Input Coercion section in the spec](https://facebook.github.io/graphql/June2018/#sec-Type-System.List). It's specified behaviour, and quite useful for cases like this :-)

**Comment by valentinbe** [comment]
+1 for this

**Comment by m3hari** [comment]
+1 What is the latest workaround

**Comment by vhuang88** [comment]
+1

**Comment by cormarti** [comment]
Very interesting feature actually... I think a lot of prisma's users would like this implementation !!

Also looking for a workaround if someone has another solution than client side ordering :)

**Comment by dimjohn** [comment]
+1

**Comment by chrisbotmind** [comment]
+1 we need this

**Comment by craigcbrunner** [comment]
Please add this and order by multiple fields!

**Comment by nk1tz** [comment]
+1
I have a need for exactly this.
:)

**Comment by tandriamanga** [comment]
+1 💯

**Comment by terion-name** [comment]
VERY neeed

**Comment by KumarAbhirup** [comment]
is it yet not built???? how do I order my posts by number of upvotes???

**Comment by impowski** [comment]
Would be an amazing feature

**Comment by fenos** [comment]
Any update on this?

**Comment by bkstorm** [comment]
it's a really important feature. This issue was created two years ago and hasn't been fixed.

**Comment by valentinbe** [comment]
Definitely agree, we are patiently waiting for this feature to push Figma to production here :)

**Comment by juliosampaio** [comment]
Any update on this?

**Comment by jvlobo** [comment]
Any update on this??? :(

**Comment by steebchen** [comment]
Can people please stop spamming this thread with "UPDATES????" and instead upvote the first comment? I does not help anything, they are currently working on Prisma 2 (where this feature will be integrated) and that will take a while. In the meantime, you're just notifiying 35 participants with no new information and thus wasting their time. I think they will update us once this feature is implemented.

**Comment by jvlobo** [comment]
> Can people please stop spamming this thread with "UPDATES????" and instead upvote the first comment? I does not help anything, they are currently working on Prisma 2 (where this feature will be integrated) and that will take a while. In the meantime, you're just notifiying 35 participants with no new information and thus wasting their time. I think they will update us once this feature is implemented.

I upvoted the first comment months ago. 
I guess people wouldn't "spam" if the Prisma team was a little bit more communicative, don't you think?

**Comment by iwasingh** [comment]
Another workaround to avoid ordering client-side is to put an index attribute on the model related to another field

```
type Vendor {
 id: ID!
 name: String
} 

type Product {
  _vendor_name: String
 vendor: Vendor
}
```
You have to handle `_vendor_name` updates manually but then you can
```
query {
  products(orderBy: _vendor_name_ASC) {  
   id 
   name
   vendor {
     name
    } 
  }
}
```

Yeah it's cumbersome, but works fine

If you want ordering by multiple fields then do it client side, it's the only solution

**Comment by bkstorm** [comment]
Or write a raw query, then use prisma.$fragment to get the type of data you need.

**Comment by juliosampaio** [comment]
@bkstorm could you provide us an example please?

**Comment by alan345** [comment]
Is this feature will never be launched?

**Comment by cesarve77** [comment]
it is a must to have feature, waiting almost 3 years?

**Comment by alan345** [comment]
Prisma team, Are you working on this feature for Prisma V2?

**Comment by homerjam** [comment]
> Or write a raw query, then use prisma.$fragment to get the type of data you need.

@bkstorm Do you have an example of this please?

**Comment by bkstorm** [comment]
> > Or write a raw query, then use prisma.$fragment to get the type of data you need.
> 
> @bkstorm Do you have an example of this please?

I don't use Prisma 1 any more due to it lacks a lot of features, like this one, but I will try to create an example code for you.

**Comment by AdamErwee** [comment]
> > > Or write a raw query, then use prisma.$fragment to get the type of data you need.
> > 
> > 
> > @bkstorm Do you have an example of this please?
> 
> I don't use Prisma 1 any more due to it lacks a lot of features, like this one, but I will try to create an example code for you.

Sorry, was just wondering if you ever got around an example for this?
